### ISSUE TITLE
Cannot upload large files

### ISSUE THREAD

**Issue by smoothdvd** [localtunnel/localtunnel#104]
The nginx config client_max_body_size need bigger

**Comment by defunctzombie** [comment]
How large of a file? Note that this is a testing tool and not appropriate for any arbitrary tunneling needs. I am unlikely to increase the file upload size for the public version but you can always run your own version.

**Comment by smoothdvd** [comment]
@defunctzombie Ok, I'll try run my own localtunnel server.
