### ISSUE TITLE
Possibility of more than one port?

### ISSUE THREAD

**Issue by SammyM** [localtunnel/localtunnel#109]
Currently I'm running a setup which connects to an API on one port and the rest of the application on another port. Is there a way I can get this working with localtunnel?

**Comment by jackmawer** [comment]
A quick hack might be to just run another instance of localtunnel for each. Inefficient, but it might work.

**Comment by SammyM** [comment]
Wow I'm replying late, sorry.
I tried that but unfortunately it didn't work.

**Comment by jackmawer** [comment]
No problem!
If this didn't work, then I'm a little stuck. It's different localtunnel addresses for each, right? Only one instance of localtunnel can bind to a localtunnel address at once. If you need to do this, you'd have to pay for a service to merge the domains for each.

**Comment by defunctzombie** [comment]
Running a different localtunnel for each should work and would be how I would recommend doing this. The client itself will not be extended to support multiple ports as that will just add more confusing usage for little benefit on the 99% use case.
