### ISSUE TITLE
Localtunnel Crashes as soon as a request is received

### ISSUE THREAD

**Issue by jaydrogers** [localtunnel/localtunnel#110]
I am running `Ubuntu 14.04` using Vagrant (Virtual Box) to run the server. The server has the following versions:

``` sh
root@devbox:/home/vagrant# lt --version
1.8.1

root@devbox:/home/vagrant# node --version
v0.10.25
```

I am running an Apache web server on Port 443, so I start `localtunnel` with the following command (and everything seems to work fine:

``` sh
root@devbox:/home/vagrant# lt --port 443
your url is: https://aneimrehwg.localtunnel.me
```

As soon as anything tries to hit my temporary URL, localtunnel dies with the following error:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

Any thoughts on what this means?

**Comment by jofob** [comment]
Having the same issue, but only seems to affect POST requests in my case.

**Comment by tslater** [comment]
Same issue as well.

**Comment by tslater** [comment]
My process as well, but with no error. Is there a way to set it to report errors?

**Comment by defunctzombie** [comment]
Is this still happening all the time? If this happens for some requests and not others it is likely the localtunnel server being flaky as reported in other issues.

**Comment by jaydrogers** [comment]
I upgraded my `lt` version to `1.8.1` and also upgraded my npm with third party packages. I used these instructions to install latest versions of `nodejs` and `npm`: http://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/#

Seems to be working now, thanks!
