### ISSUE TITLE
the server is not running persistently

### ISSUE THREAD

**Issue by Awfius** [localtunnel/localtunnel#111]
i started the server and it closes after 5-10 mintues, is there is way i can make it persistent?

**Comment by plempert** [comment]
Same problem here. Can't use it if it doesn't persist :(

**Comment by DiegoRBaquero** [comment]
You guys can use forever. Although I support adding it natively.

**Comment by fuzziness** [comment]
Same for me. Console log [here](https://gist.github.com/fuzziness/a264bd07693f8ffd4407a41ccdfd2e61)

**Comment by ArifADS** [comment]
It is sad this have not been fixed, nor I can't find why
