### ISSUE TITLE
Cant use in ubuntu 16.04

### ISSUE THREAD

**Issue by nlug** [localtunnel/localtunnel#119]
Hello there,
Im 1st time use ubuntu and I got a problem when use your package. I can install it normal but can't run it. The terminal said
```
The program 'lt' is currently not installed. You can install it by typing:
sudo apt install looptools
```
I can install sailsjs globally and run it properly but your package doesn't. Can you check it out!
Thank you.

**Comment by jhd124** [comment]
try sudo nodejs lt --port XXXX

**Comment by gamesover** [comment]
https://www.ostechnix.com/localtunnel-make-local-server-accessible-online/
