### ISSUE TITLE
No message after lt run after node manually installed

### ISSUE THREAD

**Issue by mesmariusz** [localtunnel/localtunnel#12]
Hello.

According to: https://github.com/shtylman/localtunnel/issues/9

I do not know why, bud I see node wasn't installed. So I installed it additionaly:
sudo apt-get install node

Now I have no error messages when I try to run lt --port 80.
I have no any feedback:

root@raspberrypi:/home/pi/# lt --port 80
root@raspberrypi:/home/pi/# lt --port 80
root@raspberrypi:/home/pi/# lt --port 80
root@raspberrypi:/home/pi/# lt --port 80
root@raspberrypi:/home/pi/#

Some advices ?

**Comment by RuslanUshakov** [comment]
the same here. Any updates on this?
