### ISSUE TITLE
localtunnel.me is down!

### ISSUE THREAD

**Issue by feross** [localtunnel/localtunnel#123]
<img width="424" alt="screen shot 2016-05-19 at 19 26 53" src="https://cloud.githubusercontent.com/assets/121766/15415455/a8cbe2f6-1df7-11e6-91dc-2d04e24814b2.png">

**Comment by defunctzombie** [comment]
fixed

**Comment by connectdotz** [comment]
@defunctzombie, looks like it's down again, will you be able to look into it at your earliest convenience... thx

**Comment by vedmant** [comment]
And it's down again right now.

**Comment by piotr-s-brainhub** [comment]
it's down right now

**Comment by xalakox** [comment]
and now

**Comment by zenril** [comment]
its been off an on all day today
`Problems... Error: localtunnel server returned an error, please try again`
and
`tunnel server offline: connect ETIMEDOUT 138.197.63.247:443, retry 1s`
and
`Error: connection refused: localtunnel.me:42067 (check your firewall settings)`

**Comment by eliaskg** [comment]
+1 down for me

**Comment by robertDurst** [comment]
+2 for me and my buddy

**Comment by Jmsheth** [comment]
tunnel server offline: connect ECONNREFUSED 138.197.63.247:80, retry 1s

**Comment by Jmsheth** [comment]
tunnel server offline: connect ECONNREFUSED , retry 1s

**Comment by fabioimpe** [comment]
+1

**Comment by davidranich** [comment]
Can confirm, still down.

**Comment by iamarunv** [comment]
still down, any alternate? can't get localhost.run working for either!

**Comment by faizalzakaria** [comment]
I confirm this is still down.

**Comment by dap1995** [comment]
Can confirm, still down 💃
