### ISSUE TITLE
Bad Gateway Response

### ISSUE THREAD

**Issue by jgrauel** [localtunnel/localtunnel#125]
I have setup Localtunnel, and have successfully received the sub domain, however any attempt to test my api with the url results in a "502 Bad Gateway" response. 
Is there something i didn't set up correct? I can confirm my localhost:5000 is working, and that is the port I provided.
Thanks

**Comment by defunctzombie** [comment]
Known issue. Sometimes localtunnel is flaky. Looking into it when time permits.

**Comment by kwoxer** [comment]
Still same issue here with the latest version. Any update?

Tested in Firefox/Chrome.

**Comment by mcaphasia** [comment]
Still not fixed?

**Comment by filipworksdev** [comment]
still getting this
