### ISSUE TITLE
Subdomains return incorrect URL (http vs https)

### ISSUE THREAD

**Issue by coreybutler** [localtunnel/localtunnel#126]
Example code:

``` js
tunnel = new localtunnel(this.port, {
  subdomain: 'mysubdomain'
}, function (err, sshtunnel) {
  console.log(sshtunnel.url)
})
```

I expected this to return `https://mysubdomain.localtunnel.me`, but it actually returns `http://mysubdomain.localtunnel.me`... notice it's missing the **s** in the protocol.

**Comment by poplav** [comment]
I am seeing this too.  Is there any explanation around this issue?

**Comment by coreybutler** [comment]
Why was this closed?

**Comment by mhluska** [comment]
I'm having this issue too.
