### ISSUE TITLE
Not returning https URL

### ISSUE THREAD

**Issue by saulshanabrook** [localtunnel/localtunnel#127]
Is it possible to force this to return an `https://...` URL?

If I run `lt --port 8000` or `lt --port 8000 -h https://localtunnel.me` it will return something like `http://wnorewfygi.localtunnel.me` instead of `https://wnorewfygi.localtunnel.me`.

**Comment by defunctzombie** [comment]
hm, wonder if this is a recent regression or if it always did this. Probably best to return https by default and have a flag for `--insecure` or some such.

**Comment by saulshanabrook** [comment]
I got around this by using https://github.com/rase-/zuul-localtunnel/pull/1 in Zuul
