### ISSUE TITLE
lt --port 9000 does not return https but http

### ISSUE THREAD

**Issue by dtuyenle** [localtunnel/localtunnel#128]
I was trying to setup a https proxy. Is there a way to do that ?

**Comment by bfred-it** [comment]
Even though it returns an http url, the `https` version works.

**Comment by Coaxial** [comment]
Yes, but it would be nicer to have `https` right away so you can just Cmd-click in iTerm2 instead of highlight, copy, paste, add the missing `s`, and press enter.
