### ISSUE TITLE
security issue found.

### ISSUE THREAD

**Issue by calidion** [localtunnel/localtunnel#130]
Message:
    (+) 1 vulnerabilities found
┌───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ ReDoS via long string of semicolons                                                                       │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ tough-cookie                                                                                              │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 2.2.2                                                                                                     │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ >=0.9.7 <=2.2.2                                                                                           │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Patched       │ >=2.3.0                                                                                                   │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Path          │localtunnel@1.8.1 > request@2.65.0 > tough-cookie@2.2.2                       │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/130                                                                    │
└───────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by denji** [comment]
@defunctzombie

> "request": "2.65.0",
https://github.com/request/request/blob/v2.65.0/package.json#L35
