### ISSUE TITLE
https://nodesecurity.io/advisories/130

### ISSUE THREAD

**Issue by blaggacao** [localtunnel/localtunnel#136]
https://nodesecurity.io/advisories/130

**Comment by blaggacao** [comment]
is this a wontfix for a security issue?

**Comment by blaggacao** [comment]
Or do you hereby request further explanation?

**Comment by defunctzombie** [comment]
Would be nice to get a PR or more explanation or if this is even an issue for this module; just saying "security issue" doesn't instantly make it a fire that needs putting out. Ideally some sort of proof of issue would be shown against this module otherwise this is just drive-by security on your part where you found some notice on a website about a module in our dependency tree and didn't bother giving any additional details or checking if it is actually a concern.

**Comment by blaggacao** [comment]
Alright, sorry for that.
I'm not able to further investigate or judge, as I don't know the implementation details of localtunnel nor the referenced library.

As this error showed up during installation, I was assuming that linked site is well known common ground in the node world and that my observations would be imminent to posting just the link.

-------------

What I can tell:

- tough-cookie seems to be a dependency of localtunnel
- tough-cookie is tagged at @2.2.2
- the linked site supports a possibility of ReDoS via long string of semicolons
- This issue was reported for >=0.9.7 through <=2.2.2 on July 22nd, 2016 by David Kirchner
- It's CVSS score is high at 7.5
From the description:
>Versions 0.9.7 through 2.2.2 contain a vulnerable regular expression that, under certain conditions involving long strings of semicolons in the "Set-Cookie" header, causes the event loop to block for excessive amounts of time.

Version bump to 2.3.0 is recommended.

In the case that localtunnel is compatible with 2.3.0, as to my (humild) judgment, bumping the version would be a no brainer and does not require further argumentative support.

`npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130`

**Comment by defunctzombie** [comment]
Thank you for following up. We don't directly depend on that module so it
must be a dependency of some other dependency. Do you know what that is and
which of our dependencies would need to be updated?

**Comment by lebolo** [comment]
Any update on this?

In your package.json, this module depends on `"request": "2.65.0"`. You should either change that to `"request": "2.74.0"` (which is where they [bump](https://github.com/request/request/pull/2295) their _tough-cookie_ dependency) or just loosen your version restriction to `"request": "^2.65.0"` which would allow updates that are not breaking. I would recommend the latter for all (dev)dependencies, honestly.
