### ISSUE TITLE
Crash every 2 mins ?

### ISSUE THREAD

**Issue by HasanY1989** [localtunnel/localtunnel#137]
`>lt -p <mylocalport>
your url is: https://<mysubdomain>.localtunnel.me
/usr/local/lib/node_modules/localtunnel/bin/client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:46437 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1265:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

Whats going ?

**Comment by sergeyganago** [comment]
I have same problem.

**Comment by Kevinclon** [comment]
i have similer problem, i turned my firewall off, still happens

**Comment by sergeyganago** [comment]
Ok so I find a working replacement - finch (meetfinch.com) (ngrok has 20 connections / min limit and bans after it)

**Comment by Kevinclon** [comment]
yea but 60 min/month is way to little

**Comment by sergeyganago** [comment]
No, it's unlimited. So my connection working non-stop for a day now.

**Comment by pprimm** [comment]
Same issue

**Comment by defunctzombie** [comment]
Am aware of stability issues and am trying some things to figure out why. If this is a show-stopper for you, there are a number of other similar projects or hacks around this that have been pointed out in this issue and other similar issues.
