### ISSUE TITLE
[Question] Fix for Crashes

### ISSUE THREAD

**Issue by Lionir** [localtunnel/localtunnel#138]
What is the easiest way to fix the crashing problem?

**Comment by defunctzombie** [comment]
See other issues for tips.

**Comment by Lionir** [comment]
@defunctzombie I don't understand Loz's Batch file (I can only use this since I'm on windows), could you give me exactly what the batch file would need? (I'm not experienced with Batch nor with programming in general so sorry if this seems dumb) Also, since there seems to be an option for each OS, why not try to implement it in LocalTunnel as a whole?

**Comment by Lionir** [comment]
Got it working. Thank you.
