### ISSUE TITLE
lt: Command Not Found

### ISSUE THREAD

**Issue by TackyBrad** [localtunnel/localtunnel#139]
I have been running the tunnel successfully for a couple weeks now. Been using teamviewer to restart it if out. However, today it just up and quit working altogether. I input the same code I always have "lt -p 5000" and it returns lt not found. I did an npm uninstall globally and reinstalled, same issue.

If it is of any note, it did seem to go down when I downloaded the watch.exe port from Linux to watch the tunnel and put it back up whenever it goes down. Doesn't seem like a coincidence, but I'm not sure how it could have caused it either.

![image](https://cloud.githubusercontent.com/assets/21032785/17657464/8e4b589c-6291-11e6-92a0-53d27c01a219.png)

Image shows fresh install immediately followed by command not found. And yes, I am typing lt as in LT not IT.

**Comment by Freeque** [comment]
I have the same issue, have You worked it out yet?

**Comment by TackyBrad** [comment]
I fixed it, but I had to completely uninstall node, uninstall localtunnel,
then reinstall.

**Comment by RobsonTargz** [comment]
did you installed with **-g** param?
