### ISSUE TITLE
how to use vhost?

### ISSUE THREAD

**Issue by hartjo** [localtunnel/localtunnel#140]
how to use my custom vhost? example hcareweb.dev

is this right?

lt --port 80 --local-host hcareweb.dev --subdomain hcareweb

it is redirecting to localhost im using nginx...

**Comment by vistiyos** [comment]
Same problem here

**Comment by coldlamper** [comment]
Same here

**Comment by coldlamper** [comment]
I think the problem is here https://github.com/localtunnel/localtunnel/blob/master/lib/HeaderHostTransformer.js#L27

The regex need to be case insensitive or 'Host' should be 'host'

I'll make a pull request if I get time.

**Comment by vistiyos** [comment]
@hartjo but the problem is not solved at all! why this issue is closed?

**Comment by hartjo** [comment]
@vistiyos i solve the problem by editing the file HeaderHostTransformer.js direct from my composer files as @coldlamper  suggest temporary but it works thats why i close this issue im sorry not to inform you

**Comment by vistiyos** [comment]
@hartjo but it's not solved in the repository, so it shouldn't be closed until some PR solves this problem

**Comment by hartjo** [comment]
@vistiyos if thats the case i will reopened it im sorry peace :+1:

**Comment by defunctzombie** [comment]
fixed in master
