### ISSUE TITLE
Nested subdomains

### ISSUE THREAD

**Issue by anthonator** [localtunnel/localtunnel#141]
I know that you can't support secure nested subdomains because of the way SSL wildcard certs work (https://github.com/localtunnel/localtunnel/issues/77) but could it be possible to support nested subdomains with the stipulation that it's not secured?

**Comment by defunctzombie** [comment]
Wont be supporting that because it isn't a use case that I think is useful for the target purpose of this tool. You are welcome to fork the server code tho and add any functionality you might need if this is something you want to run for a group of developers yourself.
