### ISSUE TITLE
Localtunnel appears to be extremely broken on Linux

### ISSUE THREAD

**Issue by chrismamo1** [localtunnel/localtunnel#149]
I decided to try out Localtunnel today to demo a small REST service to some students at my local ACM club, and I don't think the client ever went more than fifteen minutes without throwing a fit and crashing:

```
/usr/local/lib/node_modules/localtunnel/bin/client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:35340 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This happened on the university's WiFi, my apartment's wifi, and my cell phone's mobile hotspot. It did not matter if the server was actually receiving requests, or if it was just idling.

I am running Ubuntu, although I forget which version (I think it's the most recent LTS). I'm not a javascript developer, so there may be an easy solution that I don't see, but at the moment I am incredibly frustrated, having just had to run across the campus twice to restart a downed localtunnel.

**Comment by sebastienbarbier** [comment]
Exact same issues for me on OSX. I used it quite intensively to work with Facebook messenger chatbot, and if I had almost no issues a month ago, the past few weeks have been quite complicated.

**Comment by stonecold123** [comment]
I use a ruby script to automatically restart the script when it crashes, and it keeps crashing almost every second today!

**Comment by defunctzombie** [comment]
Closing in favor of the other issue about localtunnel crashing periodically.
