### ISSUE TITLE
Localtunnel Server Down

### ISSUE THREAD

**Issue by TackyBrad** [localtunnel/localtunnel#151]
This is merely to inform you of what you may already know. The localtunnel server has been nearly perpetually offline for the last 12ish hours. It keeps retrying but is never able to connect and says the server is offline.

Thank you for a wonderful, free product. This is not a complaint, but a notice on the off chance that the developer(s) is/are unaware.

Regards

**Comment by yatishb** [comment]
I'm experiencing this as well. Thanks in advance

**Comment by defunctzombie** [comment]
Should be back online now.

**Comment by TackyBrad** [comment]
It is currently online. Thank you so much. You beat me to the close though! :P
