### ISSUE TITLE
Feature request: allow redirection for a specific url

### ISSUE THREAD

**Issue by vshymanskyy** [localtunnel/localtunnel#154]
For example, I have hosted a server locally, and gave the localtunnel link to some friends.
After few days testing, moved it to some proper hosting.
It would be great if I could assign auto-redirect from localtunnel to the new server, even if it is time limited feature, say for 2 weeks.

**Comment by defunctzombie** [comment]
Not within scope of what localtunnel is designed to do; it is an ephemeral service for exposing your site while doing local testing.
