### ISSUE TITLE
laravel valet with localtunnel.me 

### ISSUE THREAD

**Issue by shiroamada** [localtunnel/localtunnel#157]
are you able to work 
laravel valet with localtunnel.me?

by using `valet share`, it is using `ngrok` services which cannot set the subdomain.
I like localtunnel.me can set the subdomain. 

However, I am not able to set it correct. Do you have any idea?

**Comment by vesper8** [comment]
@shiroamada 

this guy here made an awesome pull request that implements localtunnel.me with valet. Unfortunately it got rejected which I don't agree it but whatever

https://github.com/laravel/valet/pull/81/files

Give it a try?

**Comment by shiroamada** [comment]
Thanks @vesper8 !

**Comment by vesper8** [comment]
Btw I just installed his PR in the latest Valet and it worked immediately! So simple! Free subdomains! Yay
