### ISSUE TITLE
Data not passing through

### ISSUE THREAD

**Issue by jcumminsr1** [localtunnel/localtunnel#16]
Hi there. Awesome product.

Unfortunately, at the moment I cannot get any output from my tunnel in my browser. Instead it just seems to sit and spin with no data every getting returned. I get a url back when I run the client from the shell. I can ping that url. It resolves to the same IP as localtunnel.me. I assume this is correct. 

Some background: I am using the built in PHP server on my local computer and am using port 8080.

Thanks!

**Comment by 9mm** [comment]
Thanks for putting your answer, this was driving me nuts!
