### ISSUE TITLE
node-uuid is deprecated, update request dependency to 2.79

### ISSUE THREAD

**Issue by marcvangend** [localtunnel/localtunnel#162]
When installing [browser-sync](https://github.com/browsersync/browser-sync) 2.18.8, I was warned:

    npm WARN deprecated node-uuid@1.4.7: use uuid module instead

The node-uuid package was installed as dependency of [request](https://github.com/request/request) 2.78, which is a dependency of localtunnel. Updating the localtunnel dependency to request 2.79 would solve the issue.

Thank you.

**Comment by defunctzombie** [comment]
Will get around to it one day :)
