### ISSUE TITLE
yet another golang client

### ISSUE THREAD

**Issue by jonasfj** [localtunnel/localtunnel#163]
Hi,

Awesome project... I particularly like that the API is so reasonable to work with :)
It's really neat for CLI utils or test-suites that needs expose a webhook.
The existing golang client was a bit lacking, so I wrote one that implements `net.Listener` on top of localtunnel, that way it's possible to expose  webhook without even listening on a local port.

If anyone is interested I shared it at:
https://github.com/jonasfj/go-localtunnel

**Comment by defunctzombie** [comment]
👍  Awesome!! Please make a PR to add this to the README. I am sure many will find it useful.

**Comment by jonasfj** [comment]
Proposed in PR #206.

I'm not sure how useful it is since websockets doesn't seem to work over localtunnel.
