### ISSUE TITLE
net::ERR_SPDY_PROTOCOL_ERROR - static js (300kb) not fully loading

### ISSUE THREAD

**Issue by olup** [localtunnel/localtunnel#164]
I couldn't say if it's my set up or localtunnel, but my server is working fine locally, and using the localtunnel adress i get this spdy (net::ERR_SPDY_PROTOCOL_ERROR) error. Any idea where that comes from ?

To be more specific, my api adress seems to work fine, but my html+js files served by my node server never get rendered. It is some react webpack bundled app. Sometime it works, but most of the time not.

Actually, i get this error because the 300kb file vendor.js bundled by webpack fails to load completely. When i try to access the file alone i get various result, the loading always getting to different points of the file.

**Comment by narin** [comment]
Having the same issue using [Next.js](https://github.com/zeit/next.js/), which also uses Webpack and Hot Module Reload.  URL resolves but page is completely blank.

**Comment by defunctzombie** [comment]
Sounds like it could be a network connection error with localtunnel server stability. If you have a specific example case which I can reproduce then I can look into it; as currently described there is not enough information to debug this.
