### ISSUE TITLE
lt command do nothing.

### ISSUE THREAD

**Issue by azharmalik3** [localtunnel/localtunnel#165]
Hi,

When I run command `lt --port 3000` it does not give any virtual url.

Output:

```
azhar@azhar-Inspiron-7548:~$ lt --port 3000
azhar@azhar-Inspiron-7548:~$
```

Is there anything wrong with my installation?

**Comment by brodycas3** [comment]
Mine doesn't even recognize it as a command.

**Comment by mababio** [comment]
Experiencing the same issue as well. tried `lt --port 5000` in a docker container too

**Comment by defunctzombie** [comment]
This issue needs a lot more information. It is impossible to reproduce such issues just based on "does not work in my environment". There are simply too many factors that could lead to something "not working".

**Comment by mababio** [comment]
Sorry @defunctzombie, I should of included some supportive data to aid in a troubleshooting session. At the moment it appears the reported issue isn't an issue anymore. In the future I will make sure not to make the same mistake.
