### ISSUE TITLE
Can it work with the ports blocked ?

### ISSUE THREAD

**Issue by sksar** [localtunnel/localtunnel#166]
My ISP blocks all the ports so that no one can set up a server or something to run any kind of web service.
They have NAT so it is blocking all the ports.
I have checked and found that all 65536 ports are blocked.

So can localtunnel help me bypass this ??
Suppose i set up a website and connect to localtunnel, then will it work or I need to have open ports on my connection ??

Also is this something like a background VPN connection which i think can help me bypass my problem?

**Comment by Sebazzz** [comment]
We use this on our business laptops where all incoming connections are blocked. Localtunnel reverses the connection so this does work with firewalls blocking connections,

**Comment by defunctzombie** [comment]
Localtunnel is a development tool and will allow for _some_ exposure of your local site to the open internet but it **SHOULD NOT** be used to host permanent websites or considered a secure system in any way. The hosted localtunnel server is intercepting **ALL** of the traffic.
