### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by Ryccoo** [localtunnel/localtunnel#168]
http://localtunnel.me/ the default server of localtunnel is unavailable, disconnecting all devices.

Resulting with:
502 Bad Gateway

**Comment by JohannUlbrich** [comment]
+1

**Comment by TiagoCerqueira** [comment]
+1

**Comment by InfernoCoder** [comment]
+1

**Comment by ralekna** [comment]
+1

Is this service discontinued?

**Comment by hoodsy** [comment]
Server down

**Comment by c0llar** [comment]
Server is down again

**Comment by sebworks** [comment]
Server is down again

**Comment by hoodsy** [comment]
Would love to chip in to get this awesome service back online! Anything we can do to help?
