### ISSUE TITLE
Doesn't handle sub-domains of host name

### ISSUE THREAD

**Issue by brightonmike** [localtunnel/localtunnel#173]
Let's say my hostname is set to websiteaddress.dev
And this site also pulls in an api, api.websiteaddress.dev

Localtunnel will handle websiteaddress.dev by specifying a localhost override - but not the subdomain. So when you visit the URL, the site loads, but the site is still trying to pull in from api.websiteaddress.dev

Any way around this?

**Comment by defunctzombie** [comment]
Needs more information. Are you running your own localtunnel server or just using the client? I don't follow what you are trying to do here.
