### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by claudioldf** [localtunnel/localtunnel#174]
Hi folks

Is it possible to use with TCP tunnel connection like ngrok?
If not, is it possible to implement?

**Comment by GlaucioAlmeida** [comment]
That would be very good!

**Comment by defunctzombie** [comment]
It is not currently possible. Not in scope for this project at this time.

**Comment by airjordan93** [comment]
> It is not currently possible. Not in scope for this project at this time.

Does it support now? 27/11/2021 .  Please let us know!
