### ISSUE TITLE
Tunnel crashes randomly after 20-30 Minutes

### ISSUE THREAD

**Issue by Scarwolf** [localtunnel/localtunnel#177]
```
abc@bcd-GL MINGW64 ~
$ lt -l grumberg.app -p 80
your url is: https://zsmhwraqtc.localtunnel.me
C:\Users\abc\AppData\Roaming\npm\node_modules\localtunnel\bin\client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:33399 (check your firewall settings)
    at Socket.<anonymous> (C:\Users\abc\AppData\Roaming\npm\node_modules\localtunnel\lib\TunnelCluster.js:47:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1295:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

Any idea?

**Comment by Kosmonaft** [comment]
I'm having the same issue

**Comment by buckett** [comment]
Happening here too, same error different port number. Stack trace is the same. Version 1.8.3.

**Comment by hoover456** [comment]
Getting the same error.

**Comment by igorstimoli** [comment]
Got the same error

**Comment by D3X** [comment]
Same here. Running on a macOS. A _slightly_ different stack trace.

```
your url is: https://<redacted>.localtunnel.me
/usr/local/lib/node_modules/localtunnel/bin/client:58
        throw err;
        ^

Error: connection refused: localtunnel.me:45733 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by k9t9** [comment]
Same issue

**Comment by gaetansenn** [comment]
Hi guys,

Any news about that issue ?

**Comment by k9t9** [comment]
Somehow i have a deeling it has to do with dna queriea or changes from isp

**Comment by devhyunjae** [comment]
Same here

**Comment by defunctzombie** [comment]
The service is not the most reliable and such crashes will sometimes happen. Localtunnel is a development focused tool meant for use over short bursts of time rather than long hosting periods.

**Comment by D3X** [comment]
@defunctzombie it happens after a few minutes, sometimes even shorter. Also, the crash is caused by an uncaught exception. It should at least be handled gracefully. Of course, ideally, it would recover and reconnect.

**Comment by kirillshevch** [comment]
@Scarwolf @hoover456 @igorstimoli @gaetansenn @D3X
As a hotfix you can use [localtunnel-restarter](https://github.com/kirillshevch/localtunnel-restarter)

**Comment by christroutner** [comment]
I'm seeing this same issue with the latest code.
