### ISSUE TITLE
Localtunnel is down

### ISSUE THREAD

**Issue by Flarp** [localtunnel/localtunnel#179]
Tested from downforeveryoneorjustme, can't access any subdomain, and the main one redirects to the github page. 504 Gateway timeout when using.

**Comment by renatonascalves** [comment]
It seems to be up now.

**Comment by Flarp** [comment]
Still have a 504 gateway timeout. Could you post an example lt site? It might just be on my end.

**Comment by jboulhous** [comment]
Hello,

This is the case for me too, i am trying since 2 days ago to run localtunnel on node 8, node 7 and node 6 without success, using the `lt` cli or using `localtunnel` in my program, using a custom subdomain or the provided subdomain.

I have not a server of mine to test it the localtunnel server.

And thank you for this software, i have used it so much the last year and that was of much help.

**Comment by Flarp** [comment]
502 bad gateway now. Any updates?

**Comment by mod807** [comment]
I am also getting 504 Bat gatewa error 
Plz give solution 
Help 
....

**Comment by piotr-s-brainhub** [comment]
localtunnel is currently down

504 Gateway Time-out

**Comment by piotr-s-brainhub** [comment]
now it's up

**Comment by benwinding** [comment]
local tunnel is down again, giving me 504 Gateway timeout

Are there any other servers that we can use if this happens?

**Comment by Taggotty** [comment]
502 bad gateway, right now.

**Comment by benwinding** [comment]
For anyone else experiencing connection problems, I've found: [http://localhost.run/](http://localhost.run/) works pretty well it simply uses `ssh` to create a tunnel.

**Comment by Crazy-Drew** [comment]
I too am getting '502 bad gateway' right now.

**Comment by Flarp** [comment]
@benwinding Thanks! That look much better than having a seperate install.

**Comment by Flarp** [comment]
@benwinding Thanks! Looks better than a separate install.

**Comment by jboulhous** [comment]
Hello,  
Thanks again for this awesome software and service.  
I tried `localhost.run`  too and did not succeed to make it work. it turns out i have a corrupted /etc/hosts and my machine cannot resolve localhost.
Thanks again.

**Comment by kwoxer** [comment]
Still same issue here with the latest version. Any update?

Tested in Firefox/Chrome.
