### ISSUE TITLE
-bash: lt: command not found for raspberry pi zero w

### ISSUE THREAD

**Issue by gamesover** [localtunnel/localtunnel#183]
> test@raspberrypi:~ $ npm install -g localtunnel
> /opt/nodejs/bin/lt -> /opt/nodejs/lib/node_modules/localtunnel/bin/client
> /opt/nodejs/lib
> └── localtunnel@1.8.3
> 
> test@raspberrypi:~ $ lt --port 80 --subdomain gamesover
> -bash: lt: command not found

**Comment by ritiek** [comment]
Is this still a problem?

**Comment by gamesover** [comment]
@ritiek , no, I install it in another location.

**Comment by amrithmmh** [comment]
@gamesover how did you solve the problem ..i have the same issue

**Comment by gamesover** [comment]
I go to a specific folder and run `yarn add localtunnel`. Since then, I only run `lt` from that folder.
