### ISSUE TITLE
Ruby client

### ISSUE THREAD

**Issue by lloeki** [localtunnel/localtunnel#188]
Hey, thanks for this project!

Turns out I implemented a no-dependency localtunnel.me client in Ruby [over here](https://github.com/lloeki/local_tunnel) so that I can create tunnels both from the command line and straight from Ruby code. Feel free to add it to `other clients` in `README.md` as you see fit :)

**Comment by defunctzombie** [comment]
Awesome! Sorry I missed this issue before but I would gladly accept a PR adding it to the README!
