### ISSUE TITLE
localtunnel server offline - try again

### ISSUE THREAD

**Issue by brookisme** [localtunnel/localtunnel#19]
looks like this issue had existed several months ago but i've been getting this for an hour or so...

$ lt --port 3000
your url is: http://msbx.localtunnel.me
    localtunnel server offline - try again

└── localtunnel@0.1.0 

great service though. thanks.

**Comment by Kunal8195** [comment]
This could be also because you are offline i.e. you are not connected to the internet. mine was that case.
