### ISSUE TITLE
Feature Request: Readable Names

### ISSUE THREAD

**Issue by FranzSkuffka** [localtunnel/localtunnel#190]
I think we could optimize the subdomain names.
This means that rather than `https://lehtlixtxh.localtunnel.me` the URL would be `https://grub-snot-2ka.localtunnel.me` or something along these lines.

If we pick short words I think it's easier to memorize and type URLs.

**Comment by defunctzombie** [comment]
👍 To enhancement. If you make a PR I will _try_ to make time and look at it.

**Comment by FranzSkuffka** [comment]
See my PR.

**Comment by defunctzombie** [comment]
Implemented on the server side. Service is now returning readable name urls. Thank you!

**Comment by FranzSkuffka** [comment]
Thank you too :)
