### ISSUE TITLE
504 Gateway timeout after client exits

### ISSUE THREAD

**Issue by ForsakenHarmony** [localtunnel/localtunnel#192]
The localtunnel server still seems to look for the old client which is no longer active and starting it again doesn't change anything (custom subdomain)

**Comment by defunctzombie** [comment]
The server has undergone a refactor; if this issue persists please post steps to reproduce in the localtunnel/server repository.

**Comment by jayadrathamondal** [comment]
Same happening to me. Last day I restarted my server & from then I'm not getting my custom domain again. And when Im opening the url in browser it says 504.
