### ISSUE TITLE
504 gateway timeout when my IP changes

### ISSUE THREAD

**Issue by ethaniel** [localtunnel/localtunnel#194]
I am on a very slow 3g internet connection. My internet dies and reconnects every few minutes. Localtunnel is still running, but my guest sees the 504 timeout error.

Localtunnel needs to track IP address changes / loss of connection and automatically reconnect under the same subdomain name.

**Comment by defunctzombie** [comment]
If your network drops it is best to restart localtunnel to ensure it reconnects properly.
