### ISSUE TITLE
how to expose myself to the internet world without localtunnel, ngcrok or any framework?

### ISSUE THREAD

**Issue by anlexN** [localtunnel/localtunnel#197]
my home ip is dynamic

**Comment by mfresonke** [comment]
Do it the old fashioned way: forward a port from your router to your local computer and set up Dynamic DNS. A free dynamic dns provider is available at: https://freedns.afraid.org/

**Comment by anlexN** [comment]
@mfresonke , why do you recommand this freeedns website? how often do you use it ? anything else?

**Comment by akasranjan005** [comment]
You need a public IP for that @anlexN

**Comment by defunctzombie** [comment]
Outside of the scope of this project.
