### ISSUE TITLE
Localtunnel.me is down

### ISSUE THREAD

**Issue by manodupont** [localtunnel/localtunnel#199]
ITs down.

**Comment by damaneice** [comment]
+1

**Comment by jonathanarbely** [comment]
The website or the service? The latter is down for me too.

**Comment by manodupont** [comment]
Well

Both for me

Manuel Dupont

On 13 Nov 2017, at 18:34, Jonathan Arbely <notifications@github.com<mailto:notifications@github.com>> wrote:


The website or the service? The latter is down for me too.

**Comment by qnstie** [comment]
Same for me...

**Comment by jayadrathamondal** [comment]
The localtunnel.me site is also giving 502. Service is also giving error in nodejs err event
`Error: localtunnel server returned an error, please try again`

**Comment by jonathanarbely** [comment]
All services have been restored. This can be closed.

**Comment by qnstie** [comment]
Thanks @jonathanarbely, indeed everything works fine now.

**Comment by emmanuelmacharia** [comment]
Its down for me, gives me a status of 502 and a `tunnel server offline` error

**Comment by nicklesscs** [comment]
is localtunnel.me down right now?

**Comment by TheBoroer** [comment]
Hey @nicklesscs
Nope the service seems to be up just fine

**Comment by nicklesscs** [comment]
Yeah, it was my school wifi blocking it.> Hey @nicklesscs
> 
> Nope the service seems to be up just fine

**Comment by nicklesscs** [comment]
Yeah, it was my school Wi-Fi blocking it.
