### ISSUE TITLE
Error: no active client for xxxxx

### ISSUE THREAD

**Issue by smohankarthik** [localtunnel/localtunnel#200]
Hi,
I'm facing the _**no active client error**_ . Not sure what this really means , i tried the restarting the tunnels but it didn't help me either. Both my domain and sub-domain are also active (DNS resolvable). 

Please find the image attached which contains the process as a reference.

![image](https://user-images.githubusercontent.com/8954328/32770613-3c173046-c95b-11e7-83f0-fa25ac867003.png)

Let me know if you guys need further more info. from my end. Also, it would be great if you guys can mention the process to fix this issue. 

Thanks in advance..!!

**Comment by defunctzombie** [comment]
On the surface what you have looks correct. No active client would indeed indicate that the server does not have a client in its list. Since you have a client and server setup I would recommend digging in and trying to debug why this is.
