### ISSUE TITLE
Bug: lt command illegal option

### ISSUE THREAD

**Issue by glevha** [localtunnel/localtunnel#202]
Hello,

I just installed localtunnel through npm on my machine (mac OS).
When I try tun run the command `lt --port 3000`, I have a strange error message: 

```
ls: illegal option -- -
usage: ls [-SOMEKEY] [file ...]
```

I dont get it, when I only run `lt` I have the same result as `ls -l` or `ll` commands.

Any idea on how I could fix this issue ?

Thanks a lot

**Comment by vanessaholland** [comment]
it's because `lt` is aliased to `ls -tr`
i fixed this by doing `unalias lt` 
it will work for the current session but the next time that you open the terminal it will be aliased again
so I also added `unalias lt` to my .zshrc

**Comment by defunctzombie** [comment]
Would welcome a PR to enhance the README if this is a common issue for zshell users.

**Comment by blombard** [comment]
Hello @defunctzombie, 4 years later I still had this issue whit zshell.
```bash
> which lt
> lt: aliased to ll -tr
```

Adding `unalias lt` in my .zshrc fixed this issue.

Do you think it still adds value to put a _troubleshooting_ section for this specific issue in the README?
