### ISSUE TITLE
Is it possible to set up secured connection with self-signed ssl certificate?

### ISSUE THREAD

**Issue by pm-str** [localtunnel/localtunnel#204]
I've started server locally and configured reverse-proxy on Nginx server and there is opened 443 port. 

Nevertheless, when I start `lt --host https://server.example.com --port 8000`
The response is  `tunnel server offline: self signed certificate, retry 1s`.

Should I install _*letsencrypt*_ certificate or there are possible solutions with self-signed one?

**Comment by pm-str** [comment]
As I figure out, most appropriate approach is either install [let's encrypt](https://github.com/certbot/certbot) certificates - 
- `./certbot-auto certonly --standalone -d server.example.com`

and use them for nginx configuration or enable port forwarding via pure ssh 
- `ssh -f -N -R remote_port:localhost:local_port server.example.com`

**Comment by defunctzombie** [comment]
👍 Sounds like you got it figured out.

**Comment by kevinelliott** [comment]
@defunctzombie How can I use Let's Encrypt certs generated from `certbot certonly` with the `localtunnel-nginx` docker image?

**Comment by PwccaCode** [comment]
> @defunctzombie How can I use Let's Encrypt certs generated from `certbot certonly` with the `localtunnel-nginx` docker image?

good question
