### ISSUE TITLE
localtunnel.me website & service both down

### ISSUE THREAD

**Issue by jayadrathamondal** [localtunnel/localtunnel#205]
Getting ERR_CONNECTION_REFUSED from both the site & service

**Comment by nkprince007** [comment]
Same here. It was working fine for me an hour ago. But, it is completely offline now.

**Comment by zavoluk** [comment]
Same.

**Comment by Nainterceptor** [comment]
+1

By the way, I think it's not easy to purpose this service free AND scalable. If you want to host this service by yourself, server is opensource too.

**Comment by sils** [comment]
@defunctzombie anything we can do to help restore the service?

**Comment by defunctzombie** [comment]
> By the way, I think it's not easy to purpose this service free AND scalable. If you want to host this service by yourself, server is opensource too.

👍 

I have restarted the service. Apologies for the downtime. I don't have the same amount of time to commit to this service day-to-day as I use to so there will be periods of downtime until I realize it. I'll put the call out to those who may wish to help maintain the codebase and service.

**Comment by sils** [comment]
@defunctzombie hey please mention me in your call for help or mail me; we might be able to support you. I've not subscribed to your repository cause my mailbox is glowing already.

**Comment by gyandeeps** [comment]
is it again down?

**Comment by Alex0007** [comment]
Down again

**Comment by uri3000** [comment]
Is it down again now?

**Comment by damianobarbati** [comment]
@uri3000 yes, it's down
