### ISSUE TITLE
localltunnel.me appears to be down

### ISSUE THREAD

**Issue by mangvlad** [localtunnel/localtunnel#21]
Any one knows of any other domains that have localtunnel-server hosted?
Any node.js hostings that will work for installing it there on my own (registering my own domain) (Joyent? Nodester?) ?

Thanks!

**Comment by wernight** [comment]
Seems down again.

**Comment by devill** [comment]
I keep getting "504 Gateway Time-out". I worked fine until a few minutes ago. Could this be the same issue?
