### ISSUE TITLE
Replace 'request' library

### ISSUE THREAD

**Issue by cktang88** [localtunnel/localtunnel#213]
It seems the only place the `request` library is used is in `lib/Tunnel.js`, where it's only used for a simple task.
The `request` library is 52 packages, which take up around 4.22 MB, which seems unjustified for the small one-time usage that it gets included for. Would a PR be welcome to replace it with a lightweight alternative, such as [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) or [simple-get](https://www.npmjs.com/package/simple-get) or something similar?

**Comment by defunctzombie** [comment]
I'd be hame with replacing it with something simpler. Also worth considering is the axios package. If you make a PR I would review it. The biggest thing to look out for is that there is good error handling.

**Comment by cktang88** [comment]
@defunctzombie PR made.
