### ISSUE TITLE
localtunnel is offline.

### ISSUE THREAD

**Issue by thomas-jones** [localtunnel/localtunnel#215]
I get this error when I try to execute the command -

tunnel server offline: connect ECONNREFUSED 138.197.63.247:80, retry 1s

**Comment by bentonwong** [comment]
Getting the same error as above. Localtunnel was working yesterday

**Comment by jaeyun0623** [comment]
The same problem I found when newly restarting today.

**Comment by jojo-** [comment]
Same problem here. Localtunnel was working this morning.

**Comment by csimpi** [comment]
still doesnt work. I cant do my job, I should test webhooks in Vagrant environment. Whats up guys?

**Comment by JamesMGreene** [comment]
For me, it stopped working relatively shortly after `2018-01-09T20:59:07.320Z`.

**Comment by ckl8964** [comment]
Same problem. 

When will be the service resume ?

**Comment by cmirallesp** [comment]
The same error, please could you give any feedback?

**Comment by Whispers12** [comment]
+, same error

**Comment by Dan-Ross** [comment]
@defunctzombie Any updates about the tool?

**Comment by chrisns** [comment]
Hey. Is there anything we (the community) can do to help make it more resilient or just pitch in putting some coins in the meter to keep the lights on?

**Comment by Whispers12** [comment]
But now everything is OK

**Comment by defunctzombie** [comment]
@chrisns I have upgraded the localtunnel server which should help with it being able to handle the load better.

**Comment by yuliwna1** [comment]
Hey @chrisns, seems like it's down again. Can you please assist?

**Comment by chrisns** [comment]
@yuliwna1 not my project. you want @defunctzombie.

to that end @defunctzombie are you ready yet to take some contributions towards that upgraded server?

**Comment by defunctzombie** [comment]
@chrisns I suspect there are some bugs in the localtunnel server itself that contribute to downtime - tho larger servers mitigate this. Currently the server is a 1GB DigitalOcean instances.

**Comment by chrisns** [comment]
@defunctzombie happy to have a dig in the code for bugs or at least a write a healthcheck to cycle the instance when it breaks if you can share the detail of how its deployed and what breaks with some logs etc

**Comment by defunctzombie** [comment]
@chrisns Deployment is setup via the method described here: https://github.com/localtunnel/server#deploy - largely I [think] the issue stems from long lived connections (not closing tunnels) and possibly leading to OOM.

The logs themselves are not always helpful; the latest set contain a lot of:

```
[error]	server:60 null == true
AssertionError [ERR_ASSERTION]: null == true
    at Socket.socketOnData (_http_client.js:423:3)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Socket.Readable.read (_stream_readable.js:489:10)
    at Socket.socketCloseListener (_http_client.js:327:10)
    at Socket.emit (events.js:187:15)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at TCP._handle.close [as _onclose] (net.js:598:12)
{ Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:835:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
```

Which probably means there are more instances of error handling that need to be done in the server code.

**Comment by chrisns** [comment]
to clarify, you're deploying with docker?
if so, if I make a PR to the server with a HEALTHCHECK in the `dockerfile` and you run it with `--restart=always`
at least then it'll cycle without manual intervention.

ideally if i can give you a `docker-compose.yml` with a `3.x` schema which would allow multiple instances to run, load balancing and more managable memory limits
if you can let me know the docker engine version running, I can tailor to match.

thoughts?

**Comment by defunctzombie** [comment]
> if so, if I make a PR to the localtunnel/server with a HEALTHCHECK in the `dockerfile` and you run it with `--restart=always`
> at least then it'll cycle without manual intervention.

If docker has this feature now then yes that sounds about right.

> ideally if i can give you a `docker-compose.yml` with a `3.x` schema which would allow multiple instances to run, load balancing and more managable memory limits

This won't "just work" due to how the backend is designed. There is no capability for horizontal scaling of the instances.

**Comment by chrisns** [comment]
@defunctzombie https://github.com/localtunnel/server/pull/98 when you time
