### ISSUE TITLE
How to use ssh access the URL which localtunnel return ?

### ISSUE THREAD

**Issue by huangteng1220** [localtunnel/localtunnel#217]
I have succeeded to install localtunnel and get url. But how to use ssh access the URL which localtunnel return ?   I try to use this command: ssh ht@XXXX.localtunnel.me，but I get the error: Permission denied (publickey). How do fix this error.

**Comment by defunctzombie** [comment]
You cannot. This is an http/s only tunnel for exposing websites to clients for demos, webhooks for testing, etc. This is not a one-size-fits-all tunnel.
