### ISSUE TITLE
Cant access wordpress site

### ISSUE THREAD

**Issue by superh1k** [localtunnel/localtunnel#218]
I cant access access my wordpress site over localtunnel. Im using xampp and my localhost is on port 80.
I used command: lt --port 80 and turned off my firewall, even installed plugin to convert wordpress links to relative ones.

https://github.com/optimizamx/odt-relative-urls
http://wordpress.org/plugins/relative-url/

I can access Xampp dashboard just by pasting the link that i get from localtunnel but cant access any wordpress site.

**Comment by karlg-code** [comment]
I'm facing the same problem at the moment.How did you solve it?
