### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by lastday154** [localtunnel/localtunnel#221]
I have tried to create a local tunnel link but the link always gives me the 404 error.

**Comment by jstrugnell** [comment]
Me too. Did you resolve this?

**Comment by vaibhavsingh97** [comment]
Me too. Did anyone resolved?

**Comment by jstrugnell** [comment]
It worked for me when I was outside of my company's network. So I assumed it was firewall restrictions causing it to not work.

**Comment by vaibhavsingh97** [comment]
Thanks a lot @jstrugnell 😄 
You saved my time ❤️

**Comment by jstrugnell** [comment]
Glad I could help :smiley: :thumbsup:

**Comment by ryancwalsh** [comment]
I'm super confused. I'm trying to use LocalTunnel as part of BrowserSync within Laravel: https://laravel.com/docs/5.6/mix#browsersync-reloading

I see on the [LocalTunnel homepage](https://localtunnel.github.io/www/) "Localtunnel allows you to easily share a web service on your local development machine **without messing with DNS and firewall settings**."

So why would I ever get this error message that tells me to check my firewall? 

```
      Tunnel: https://kvbss.localtunnel.me
 -----------------------------------------
          UI: http://localhost:3001
 UI External: http://169.254.32.237:3001
 -----------------------------------------
[BS] Watching files...
[BS] Localtunnel issue: connection refused: localtunnel.me:36626 (check your firewall settings)
[BS] Oops! The localtunnel appears to have disconnected. Reconnecting...
```
(And why are the comments above in this ticket about firewalls if the point of LocalTunnel is to not need to worry about what the firewall settings are?)

Like the original poster of this ticket, all I see at my site (https://kvbss.localtunnel.me) is "404".

Please forgive my naivete; I'm completely new to LocalTunnel and just have never gotten it to work yet.

Thanks in advance for any suggestions.

**Comment by defunctzombie** [comment]
That error message can sometimes be misleading. It basically means the localtunnel client was not able to connect to the localtunnel server. Because of the way localtunnel client and server interact (high numbered tcp ports) these are sometimes blocked by firewalls.

The 404 when visiting the site means that localtunnel does not know about your tunnel connection (and thus there is no page for it to display).

**Comment by laukstein** [comment]
Why not to ReOpen this issue since it happens almost always?

    Error: connection refused: localtunnel.me:40049 (check your firewall settings)
        at Socket.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\localtunnel\lib\TunnelCluster.js:47:32)
        at Socket.emit (events.js:182:13)
        at emitErrorNT (internal/streams/destroy.js:82:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    localtunnel server crashed
    your url is: https://me.localtunnel.me
    C:\Users\Me\AppData\Roaming\npm\node_modules\localtunnel\bin\client:65
            throw err;
            ^

    Error: connection refused: localtunnel.me:42372 (check your firewall settings)
        at Socket.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\localtunnel\lib\TunnelCluster.js:47:32)
        at Socket.emit (events.js:182:13)
        at emitErrorNT (internal/streams/destroy.js:82:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
        at process._tickCallback (internal/process/next_tick.js:63:19)
    localtunnel server crashed

**Comment by holdenla** [comment]
@laukstein Did you find a way to fix this problem? Thank you.

**Comment by laukstein** [comment]
@holdenla, no, I stopped using localtunnel. Must localtunnel issues are caused by localtunnel server downtime, can't relay on it.

**Comment by holdenla** [comment]
@laukstein In meantime I tried using ngork and I get the same error . Not sure if it is because of the firewall, but I need to find a way to test my project from localhost on web.

**Comment by japostigo-atsistemas** [comment]
> It worked for me when I was outside of my company's network. So I assumed it was firewall restrictions causing it to not work.

Me too. Then I really don't know the propose of localtunnel if it doesn't work in these scenarios...

**Comment by KrishnaSharma000** [comment]
me too. Do anyone knows an working alternative to localtunnel.

**Comment by jsavari** [comment]
I'm also receiving the 404 error so I started using Ngrok.

**Comment by TheBoroer** [comment]
Hey all, if you get a plain 404 page, it usually means the tunnel dropped (so eithe rthe server or client disconnected or ISP issues).

**Comment by jsavari** [comment]
Is there any way to resolve this issue?

**Comment by TheBoroer** [comment]
Usually restarting the client on your side should fix it

**Comment by XtechInf** [comment]
i did 
`sudo apt install npm`
and then
`sudo npm install -g localtunnel`

**Comment by XtechInf** [comment]
i did
`sudo apt install npm`
and then
`sudo npm install -g localtunnel`
then
`lt --port <_whatever port_> -s <_whatever subdomain_>`
or if youre using a tool just use localtunnel

**Comment by XtechInf** [comment]
i did
`sudo apt install npm`
and then
`sudo npm install -g localtunnel`
then
`lt --port <_whatever port_> -s <_whatever subdomain_>`
or if youre using a tool just use localtunnel
<img width="479" alt="image" src="https://user-images.githubusercontent.com/108958247/188748768-a1f4c87e-0c89-4bc2-9657-972a86ea0d03.png">

**Comment by XtechInf** [comment]
i did
`sudo apt install npm`
and then
`sudo npm install -g localtunnel`
then
`lt --port <_whatever port_> -s <_whatever subdomain_>`
or if youre using a tool just use localtunnel
<img width="479" alt="image" src="https://user-images.githubusercontent.com/108958247/188748768-a1f4c87e-0c89-4bc2-9657-972a86ea0d03.png">

**Comment by XtechInf** [comment]
i did
`sudo apt install npm`
and then
`sudo npm install -g localtunnel`
then
`lt --port <_whatever port_> -s <_whatever subdomain_>`
or if youre using a tool just use localtunnel
<img width="479" alt="image" src="https://user-images.githubusercontent.com/108958247/188748768-a1f4c87e-0c89-4bc2-9657-972a86ea0d03.png">
<img width="957" alt="image" src="https://user-images.githubusercontent.com/108958247/188748976-8a5a03c0-6d71-4c2c-bc50-e4e65c1cd68d.png">
