### ISSUE TITLE
-bash: lt: command not found

### ISSUE THREAD

**Issue by manojjenago** [localtunnel/localtunnel#224]
Hi ,

Thanks for a good solution. However when I do the lt --port 5000 . I am getting this error that lt : command not found. Please help. Am I running from a different folder. 

Thanks,
Manoj

**Comment by manojjenago** [comment]
Sorry, I guess it was not added to path for some reason. I added it and its working.

**Comment by manojjenago** [comment]
Hi @amrithmmh  , please set the path variable. I guess if you are using linux or raspberry PI then you have to add permanently (.profile or so)

**Comment by amrithmmh** [comment]
@manojjenago thank you
