### ISSUE TITLE
Cannot use unreserved custom subdomain after quickly opening and closing two sessions in a row

### ISSUE THREAD

**Issue by RoboticMind** [localtunnel/localtunnel#227]
Whenever I quickly close a session and reopen one I cannot use the same custom subdomain even though nothing else is using the subdomain. This stays even after rebooting.

**Comment by ricardobarantini** [comment]
+1

**Comment by vladminsky** [comment]
The tool is great but this is very annoying issue.
+1

**Comment by defunctzombie** [comment]
This sounds related to https://github.com/localtunnel/localtunnel/issues/220. Closing this; please continue discussion there.

I suspect in your case you are hitting the _grace period_ of subdomains. A subdomain is not handed back out immediately after all tunnel connections to it are dropped to allow the client that created it to reconnect; however if you exit the client and start it again it will no longer remember the internal connectivity information and you will not be able to re-use the same subdomain for a short period. I'll think about dropping the grace period altogether as there is unlikely to be sniping occurring :)

**Comment by sanchitbh** [comment]
>  I'll think about dropping the grace period altogether as there is unlikely to be sniping occurring :)

Yes, that would be great. The biggest advantages of localtunnel is being able to use custom sub-domains and hard-coding them for testing. Thanks!
