### ISSUE TITLE
subdomain doesn't work

### ISSUE THREAD

**Issue by julianusti** [localtunnel/localtunnel#233]
Hey, I always had an issue with subdomain (i.e. not always subdomain has been up and running).

But, this time I have this issue for the second day. When trying to run localtunnel with custom subdomain, random subdomain returned instead.

**Comment by jarontai** [comment]
Same problem here.

**Comment by Dan-Ross** [comment]
Likewise. The subdomain flag stops working entirely.

**Comment by defunctzombie** [comment]
Please provide an example to reproduce when posting issues. The more specific (including what you expect to happen and how you are using the module) the more it helps me reproduce and resolve.

**Comment by Dan-Ross** [comment]
For me, I had localtunnel running when i put my machine to sleep. when I came back later, the tunnel had closed (fair enough). I would hope to be able to reuse the domain in a few hours and could use another one in the meantime. 

However, any attempt to create a new tunnel using the subdomain flag did not work as expected. it would always assign a random value for the subdomain (as if the subdomain flag was not used), even if i specified a different one.

**Comment by defunctzombie** [comment]
I am tracking the issue here https://github.com/localtunnel/localtunnel/issues/248.

I can reproduce the issue however have not tracked down the root cause for all cases. In some cases the domain is re-usable - leading me to believe there is a logic and/or connectivity error on the server side.
