### ISSUE TITLE
Tunnel doesn't end after client stopped

### ISSUE THREAD

**Issue by TangRufus** [localtunnel/localtunnel#236]
#### Steps to reproduce

1. Start `localtunnel` client
    ```bash
    ➜ lt -p 443 -l my-site.test -s my-site
    your url is: https://my-site.localtunnel.me
    ```
1. `https://my-site.localtunnel.me` works as expected
1. Press <kbd>control</kbd> + <kbd>c</kbd> to quit the client
1. `https://my-site.localtunnel.me` still available
1. Shut down the local server(`my-site.test`)
1. `https://my-site.localtunnel.me` returns timeout errors.
1. Start the local server(`my-site.test`)
1. `https://my-site.localtunnel.me` becomes available again

#### Info

macOS 10.13.4

```bash
➜ node -v
v8.11.1

➜ yarn --version
1.6.0

➜ lt --version
1.9.0
```

I tried:
- install `localtunnel` via `yarn` and `npm`
- use and not use subdomain (`-s`)

They all give the same result.

Any solution to stop tunneling?
Thanks!

**Comment by defunctzombie** [comment]
If you shutdown your localtunnel client (i.e. `lt`) there is _no way_ that your site would still be available. Either you are seeing a cached version or you did not actually shutdown the client.

Separately - I have deployed a refactored localtunnel server which addressed different issues around subdomains and timeout so maybe you will have better luck with that.
