### ISSUE TITLE
I can't seem to install it,

### ISSUE THREAD

**Issue by LWFlouisa** [localtunnel/localtunnel#237]
npm http GET https://registry.npmjs.org/openurl/1.1.1
npm http GET https://registry.npmjs.org/axios/0.17.1
npm http GET https://registry.npmjs.org/debug/2.6.8
npm http GET https://registry.npmjs.org/yargs/6.6.0
npm http GET https://registry.npmjs.org/axios/0.17.1
npm http GET https://registry.npmjs.org/yargs/6.6.0
npm http GET https://registry.npmjs.org/openurl/1.1.1
npm http GET https://registry.npmjs.org/debug/2.6.8
npm http GET https://registry.npmjs.org/axios/0.17.1
npm http GET https://registry.npmjs.org/yargs/6.6.0
npm http GET https://registry.npmjs.org/openurl/1.1.1
npm http GET https://registry.npmjs.org/debug/2.6.8
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-93-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "localtunnel"
npm ERR! cwd /home/sarah
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sarah/npm-debug.log
npm ERR! not ok code 0

NPM doesn't seem to work for me, is there an alternative way to install it?

**Comment by defunctzombie** [comment]
This is not a problem with localtunnel. Upgrade to a newer version of nodejs.
