### ISSUE TITLE
Nginx Config

### ISSUE THREAD

**Issue by Immortalin** [localtunnel/localtunnel#239]
Hi, good work on building this! It's really awesome. I have a rather interesting problem that I am trying to solve using this. I am trying to expose `netdata` through nginx (for basic auth) but with a domain so as to use tls for security. Is it possible to connect nginx to the localtunnel server directly without having to install the `lt` client?

For a lot of server clusters (e.g. Kubernetes), the underlying p2p system uses either `tinc` or `wireguard` etc. but since I am interested in using localtunnel, it requires lower overhead than installing `npm` + `lt` client.

**Comment by defunctzombie** [comment]
I can't really figure out what you are asking but I think you want the server part of localtunnel https://github.com/localtunnel/server
