### ISSUE TITLE
Can't keep tunnel up more than ~15min

### ISSUE THREAD

**Issue by mougel** [localtunnel/localtunnel#241]
Hey guys,

Everytime the tunnel is active for more than ~15minutes it crashes and I get the following error report:
<img width="629" alt="screen shot 2018-05-06 at 13 08 09" src="https://user-images.githubusercontent.com/11598852/39672242-f55102f2-512e-11e8-8edf-8b885eff5ca1.png">

The time frame isn't precise, sometimes it crashes after just 2-3min, sometimes it takes up to 25min.

Not sure what's going on, I just know it's not my firewall (I disabled it completely to test)

**Comment by defunctzombie** [comment]
I have recently deployed a re-written backend for the service which I am hopeful will be more robust.
