### ISSUE TITLE
Is there an option for Header rewriting?

### ISSUE THREAD

**Issue by thepian** [localtunnel/localtunnel#243]
Here is how you fix getting `Invalid Host Header` with ngrok.

```
ngrok http 4200 -host-header="localhost:4200"
```

**Comment by moeinrahimi** [comment]
i need this too for a react project

**Comment by roccomuso** [comment]
good point

**Comment by defunctzombie** [comment]
There is a `--local-host` option which can be used in conjunction with custom `/etc/hosts` entries to _maybe_ accomplish what you want. Without more details in your original issue I can't say if that will actually do what you want - I don't know what ngrok does as I don't use it.
