### ISSUE TITLE
--domain no longer work?

### ISSUE THREAD

**Issue by zhengdavid5222** [localtunnel/localtunnel#246]
I think there were an implementation where now it's automatically generating a sub-domain instead of setting a static sub-domain?

**Comment by defunctzombie** [comment]
Please provide an example to reproduce what is not working when filing issues.

**Comment by zhengdavid5222** [comment]
when starting $lt --port "port" --domain "domain" the domain does not get set

**Comment by defunctzombie** [comment]
`--domain` is not an option - please see the CLI help text.

**Comment by zhengdavid5222** [comment]
miss type it's --subdomain

**Comment by zhengdavid5222** [comment]
it was working until today

**Comment by defunctzombie** [comment]
I gave this a go with some subdomains and the feature is working with some of them - there times when it does get stuck. I am making a separate issue in this repo describing the behavior.
