### ISSUE TITLE
Subdomain issue

### ISSUE THREAD

**Issue by LWFlouisa** [localtunnel/localtunnel#249]
Not sure if this is a reincarnation of the older subdomain issue, but I seem to keep getting this error:

`tunnel server offline: Request failed with status code 403, retry 1s`

**Comment by LWFlouisa** [comment]
Turns out, I needed to write my subdomain in lowercase.

**Comment by adipascu** [comment]
I have also faced a similar issue, the client should prompt if the subdomain is taken or incorrect.
