### ISSUE TITLE
redirect to localhost fails

### ISSUE THREAD

**Issue by carlituxman** [localtunnel/localtunnel#252]
I'm doing:

lt --port 80 --subdomain mysubdomain --local-host myapp.loc

When I open at browser: https://mysubdomain.localtunnel.me 
redirects to https://myapp.loc then not work from another machine

**Comment by ElijahLynn** [comment]
I just ran into this too. What is happening is that local host "myapp.loc" is issuing a redirect, checkout your browser Network panel to confirm. It seems like what may be happening is that you are saying it is port 80 and your app says, I hear you, but we need https on 443, and then redirects you to https://. I would try `lt --port 80 --subdomain mysubdomain --local-host myapp.loc`.

**Comment by carlituxman** [comment]
I try:
lt --port 80 --subdomain mysubdomain --local-host myapp.loc
and
lt --port 443 --subdomain mysubdomain --local-host myapp.loc

But in my in the browser changes to https://myapp.loc

myapp.loc is served by laravel valet

**Comment by defunctzombie** [comment]
As noted by @ElijahLynn you app itself might be doing a redirect. I recommend debugging a bit locally and seeing if you can figure out more details about what is happening.
