### ISSUE TITLE
Crashing a lot in 5-10 minutes 

### ISSUE THREAD

**Issue by prateekrastogi** [localtunnel/localtunnel#253]
Hi,
Thanks a lot for quite helpful utility. But, as of now it is barely able to run stably and crashing a lot, showing firewall error, while there are no such issues with my firewall. I am using node 10 on windows.

**Comment by calebboyd** [comment]
I notice this if I'm running a development server behind a localtunnel that restarts frequently. The restart will cause the error.

**Comment by prateekrastogi** [comment]
My scenario includes running an express server in which resources are being watched for changes but server is not restarting. May be this additional information can help to more accurately pinpoint the issue.

**Comment by BerndErnst** [comment]
@calebboyd Yeah, it restarts frequently, since it crashes frequently.
I wouldn't complain if localtunnel just keep open

**Comment by BananaAcid** [comment]
Server of overloaded it seems - see #258

**Comment by defunctzombie** [comment]
The server experiences high load given that it is a free public service. Often retrying helps. You can also deploy your own localtunnel server (see the server repo) if you need a more stable solution.
