### ISSUE TITLE
504 Gateway Time-out 

### ISSUE THREAD

**Issue by sushant1727** [localtunnel/localtunnel#259]
So, I followed the steps installed localtunnel.

I am using Flask to run my app in Python. After I run my python code I start the `lt --port 8000 --subdomain shan --local-host "127.0.0.1" -o --print-requests`
When I run the URL on the other/local computer on same/different network I get 504 Gateway Time-out
nginx/1.10.1 error.

Is there a way to fix this issue ?

**Comment by abhinaykumar** [comment]
Are you sure your app is already running on the same port?

tried the same command, it works fine for me
![screen shot 2018-07-25 at 10 59 50 am](https://user-images.githubusercontent.com/4496810/43181289-fb704a08-8ff9-11e8-8b19-bb9ddf23ff5d.png)

So, you might wanna do something like:

1. `http-server -p 3000`
2. `lt --port 3000 --subdomain shan --local-host "127.0.0.1" -o --print-requests`
