### ISSUE TITLE
'lt' Command not found

### ISSUE THREAD

**Issue by amanharitsh123** [localtunnel/localtunnel#260]
'lt' doesnt seem to be in PATH

**Comment by mx1010** [comment]
I'm having this problem too. I installed localtunnel globally, but no success. In troubleshooting, I've read that it's not added to `$PATH` correctly... but when I try to find the binary for it, the search yields no results :( 

```
$ lt --port 3000
bash: lt --port 3000: command not found
$ whereis lt
$ whereis localtunnel
```

**Comment by flotwig** [comment]
localtunnel uses `bin` in `package.json` to automatically add `lt` to the PATH.

It should be installed in your `node_modules` `bin` directory, wherever that is. It depends on if you've installed globally or locally. The `package.json` docs explain:

https://docs.npmjs.com/files/package.json#bin

**Comment by mx1010** [comment]
> localtunnel uses bin in `package.json` to automatically add `lt` to the PATH.
This isn't true... I've checked my path after repeatedly uninstalling and reinstalling. The location isn't added to my path. 

Not sure why you'd close this since neither of us have resolved our problems here ?

**Comment by flotwig** [comment]
The `bin` entry tells npm to copy `./bin/client` to `<bin folder>/lt`, so if it's installed globally, it's in your global `node_modules` folder's `bin` subdirectory.

If it's not in your PATH, it's probably an issue with your node setup, not an issue with this specific repository.

**Comment by mx1010** [comment]
Hey, looks like you were right on the 💵 💪 

My `npm config get prefix` was set to my home directory (not sure how that happened).
So used, `npm config set prefix /usr/local` and now it works. 

Thanks for that! ✨

**Comment by flotwig** [comment]
Np. Glad I could help :)

**Comment by pcl392578** [comment]
how to run cmd command  lt --port 8000 --subdomain mydomain in background i dont want to show this command prompt to see users but it should run in background please reply
