### ISSUE TITLE
⚠️Still under active development? ⚠️

### ISSUE THREAD

**Issue by BerndErnst** [localtunnel/localtunnel#261]
A lot of errors for common use cases.
No replies for existing issues.
Last commit roughly 4 months ago.

Let be this a warning for everyone who need something reliable

**Comment by flotwig** [comment]
Not sure either. At first glance it looks abandoned, but then again there have been issues closed, etc. and the maintainer is active on GitHub.

@defunctzombie What's the status of localtunnel? This is a super super super useful project, I'd be sad to see it disappear because of a lack of spare time on your or @courseoff's part.

**Comment by BananaAcid** [comment]
Agree, we here at Cheil (for Samsung) in Germany, are watching the project as well. I actually tried to implement it into a project for a fair next month.  Evaluation failed. Unfortunately.

**Comment by flotwig** [comment]
It seems like the project works fine, but the public instance is having availability issues. If I had to guess it's just getting hammered into oblivion with requests. If you stand up your own localtunnel instance, it ought to work fine.

**Comment by defunctzombie** [comment]
I am glad to hear this project is useful! However, I must also note that this project is a low priority side project for me. I come back to it from time to time (this is why some issues get closed, etc) but generally I would not expect a fast response from me here.

For those that do find the project useful but suffer from the flaky public server; the server is open source https://github.com/localtunnel/server and I recommend that if you have serious needs you set it up yourself. The client has a command line argument to use other servers.

I will continue to run the public server and make small tweaks here or there if I desire - however I would not consider this project _actively maintained_.

**Comment by andrewmiller1** [comment]
@defunctzombie Thank you for the free service. It's mighty convenient for all developers around the world. This project is absolutely wonderful and well executed.

I feel compelled to give an unsolicited suggestion. To keep issues from popping up, I recommend adding on the website and READMEs that it's not actively maintained. A bonus would be to mention anybody can make their own localtunnel server by following the instructions on the server's github page.

When you go to https://localtunnel.me/, some expectations are set. It looks like an inviting site that's simple and easy to use. Despite the connection issues, I'd say we're still on target. But then you notice on the right hand side it says it's maintained by someone. This makes one think it's actively maintained. Furthermore, just above this, it says it's sponsored. Now it seems as though this is something prominent enough that an organization wants to ensure it's reliable. Without any note of it's connection issues, someone coming in has the expectation solidified. Even though it's completely free, the expectation is set to this should work.

With that said, there still isn't an obligation to do anything here. But managing the expectation up front (the front page of the website/repositories) might be at your own benefit. At the very least it may prevent many developers spending time initially facing the same issue then keep opening issues.

This project rocks and makes sharing my work much simpler of a process. Thank you again for providing a public server and this system for everyone for completely free without getting anything in return.

**Comment by BananaAcid** [comment]
just as a side note: I wish, it would be clear on the homepage, that most user's troubles are related to the localtunnel.me server being overly used.

btw: I added a project to get the project running on IIS quickly - https://github.com/BananaAcid/localtunnel-server-iis  ...  @defunctzombie you might check if this is of interest to your homepage

**Comment by hanzlahabib** [comment]
starting bash or command with admin privileges solves my problem
