### ISSUE TITLE
Localtunnel with subdomain not working after several restarts

### ISSUE THREAD

**Issue by Dmdv** [localtunnel/localtunnel#263]
Steps to reproduce :

Start localtunnel with subdomain parameter and cancel with Ctrl-Z several times and then it will start with a random subdomain or failing with error that something wrong with firewall. 
Usually it takes about three times, I need to restart my server during development and have no opportunity to stick to random subdomains

**Comment by siburny** [comment]
Why are you using CTRL-Z? It's not a cancel command; it's "put the app into background" command. So my guess it doesn't close the connection, thus server holds onto that sub-domain. Next time you start localtunnel it cannot use the same sub-domain because server thinks it's taken.

**Comment by Dmdv** [comment]
I've tried it several times with Ctrl-C, indeed it just is working. Thank you.
With Ctrl-Z I used to manually kill the process and started it again.
