### ISSUE TITLE
Got 404 on every request

### ISSUE THREAD

**Issue by isnifer** [localtunnel/localtunnel#265]
Tried globally installed run and via nodejs api

![image](https://user-images.githubusercontent.com/1788245/43524112-1663a9b0-95a7-11e8-8fe3-90b663914a03.png)
![image](https://user-images.githubusercontent.com/1788245/43524121-1c987612-95a7-11e8-9ac3-cd623ea7aa7d.png)

**Comment by isnifer** [comment]
Opened server on 8080 — and it works

**Comment by gauravc311** [comment]
@isnifer How did you open the server on port 8080? I'm pretty much a noob for this. Thanks in advance.

**Comment by isnifer** [comment]
@gauravc311 https://github.com/localtunnel/localtunnel#use
