### ISSUE TITLE
Is the server alive?

### ISSUE THREAD

**Issue by panlina** [localtunnel/localtunnel#276]
I just tried but I kept getting:
`tunnel server offline: socket hang up, retry 1s`
I also tried `--host https://localhost.run` as suggested in #203 , but this time I got: 
`your url is: undefined`
Is the server working?

**Comment by panlina** [comment]
Today I tried it again and it changed. It returned me url, but gave `connection refused: localtunnel.me:43766 (check your firewall settings)` just as #258 . Maybe it's stability issue?

**Comment by Un-knownCoder** [comment]
I encountered this problem too...
Probably because i was writing it wrong:
```lt -p 8080  (this gave me the same error)```

But I solved it by doing this:
```lt --port 8080```
or
```lt --subdomain mydomain --port 8080```

---

Here's the response:
```your url is: https://mydomain.localtunnel.me```

**Comment by Un-knownCoder** [comment]
I hope it works for you too

**Comment by panlina** [comment]
I believe it's nothing to do with `-p` vs. `--port` because they are equivalent as the help message says. I think it's just because the server was back normal the 2nd time you try. :)

**Comment by Un-knownCoder** [comment]
Well, if i write the comand woth `-p` it doesn't work, but if i re-write the comand with `--port` it works well in my pc...

*(i tried multiple times to verify it)*

**Comment by panlina** [comment]
I deployed my own instance on my server. Now it works normally. So I think it's stability issue for the public one the author hosts.
