### ISSUE TITLE
NET::ERR_CERT_INVALID

### ISSUE THREAD

**Issue by rm-rf-etc** [localtunnel/localtunnel#285]
HTTPS doesn't work for me on mobile browsers, Chrome and Safari (over wifi). Interesting, HTTPS works fine on my laptop on the same wifi network. The browser says the connection is not private and shows the error, NET::ERR_CERT_INVALID. The connection works if I change to HTTP.

**Comment by triton086** [comment]
Hi @rm-rf-etc 

It seems that the SSL certificate was revoked.

> NET::ERR_CERT_REVOKED
Subject: *.localtunnel.me
Issuer: COMODO RSA Domain Validation Secure Server CA
Expires on: 11 Dec 2018
Current date: 1 Dec 2018

**Comment by valerauko** [comment]
Now to hoping that @defunctzombie renews their certificate soon

**Comment by stephencross** [comment]
Same issue here!

**Comment by triton086** [comment]
yep. it seems that the renewal process will take some time.

Meanwhile, I found this server.

> lt -h https://d3v.cc  --port 1234

free to use :)

**Comment by defunctzombie** [comment]
I've updated the certificate - should be resolved now.

**Comment by wmeligy** [comment]
Issue is now happening again

**Comment by neomvll** [comment]
yep, same here

**Comment by arielrahmane** [comment]
**Failed to load resource: net::ERR_CERT_REVOKED**

Same here! 

@defunctzombie hope you can fix it ASAP 🙏

**Comment by Y2theK** [comment]
on Nov 24, 2019
Failed to load resource: net::ERR_CERT_REVOKED
Same here !
