### ISSUE TITLE
localtunnel is currently down

### ISSUE THREAD

**Issue by rajeshmSTS** [localtunnel/localtunnel#286]
localtunnel is currently down...showing certificate error
![screen shot 2018-12-05 at 10 46 23 am](https://user-images.githubusercontent.com/43290296/49491668-1f9f4e80-f87b-11e8-9501-3aa30ab7d3a0.png)

**Comment by triton086** [comment]
Hi @rajeshmSTS 
localtunnel is not down. 
check https://github.com/localtunnel/localtunnel/issues/285

**Comment by rajeshmSTS** [comment]
ok. thanks
