### ISSUE TITLE
localtunnel.me limitations

### ISSUE THREAD

**Issue by sungdzda** [localtunnel/localtunnel#288]
I understand that localtunnel.me is a free service, and it consumes network resources on the server in order to run. So I'd like to know if there are currently any limitations or restrictions in terms of service quality, ie. connection speed , # of tunnels, or duration. In a related vein, how do you prevent abuse?

Thank you.

**Comment by DiegoMarrero** [comment]
I don't think there is any limitation. I was looking for information about that and I didn't find anything that mention it.

**Comment by defunctzombie** [comment]
There are no limitations - abuse happens, server goes down, comes back up sometime later :)
