### ISSUE TITLE
WORK AS SHIT

### ISSUE THREAD

**Issue by tayurus** [localtunnel/localtunnel#292]
It constantly crashes when you try to go to link

**Comment by Cranite** [comment]
Do you have any pastes of errors, error codes, logs? It'd help with debugging.

**Comment by normanjoyner** [comment]
This is disrespectful and unuseful. Show some respect for the maintainers of open source software. If you’re having an issue, minimally provide useful information to aid in the debugging and resolution of the issue you’re having, or, alternatively, submit a patch to help fix the issue.

**Comment by tayurus** [comment]
I apologize for my rudeness.
Recently I had to show my work to a client. I chose localtunnel, but it fell over and over again. I got the URL, but when I tried to navigate through it, I got the Node.js error exception.
