### ISSUE TITLE
tunnel server offline

### ISSUE THREAD

**Issue by jorenjamar** [localtunnel/localtunnel#293]
I get the message that the servers are offline when I try to make a tunnel.
`tunnel server offline: connect ETIMEDOUT 138.197.63.247:443, retry 1s`
I get a connection after a lot of time but this connection only remains for a few seconds. I think there is something wrong with the servers of Localtunnel. Is this possible?

**Comment by mattkelly** [comment]
I can confirm I've also been seeing this for about a week.

**Comment by thesmart** [comment]
I was blocked by this, and a colleague recommended I try [ngrok](https://ngrok.com/). So far so good.

**Comment by johnhunter** [comment]
With `localtunnel@1.9.1`
I get a 404 response intermittently from the service. `lt` command run initially with no errors. Then the following error is thrown:

```
/usr/local/lib/node_modules/localtunnel/bin/client:65
        throw err;
        ^

Error: connection refused: localtunnel.me:39674 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by przano** [comment]
@johnhunter I'm getting same exact error

**Comment by Djedjeska** [comment]
yeah...

**Comment by mattkelly** [comment]
FWIW, we ended up just setting up our own [localtunnel server](https://github.com/localtunnel/server) with the recommended [nginx setup](https://github.com/localtunnel/nginx) on the cheapest DigitalOcean droplet available. It was easy enough and now we don’t have to rely on an external service.

**Comment by defunctzombie** [comment]
The server experiences times of high load and instability due to the free public nature of the service. Often if you retry it will work.

Setting up your own server is another option if you must have a more reliable setup.
