### ISSUE TITLE
Can I use localtunnel server/client for TCP raw tunneling?

### ISSUE THREAD

**Issue by Varooneh** [localtunnel/localtunnel#297]
Hi, 
localtunnel server support TCP raw tunneling?

Example: ngrok tcp 3389, public local port 3389 over 0.tcp.ngrok.io:3389.
Can I use localtunnel line ngrok tcp?

**Comment by doganmurat** [comment]
Same question.
Can I use localtunnel for vnc or rdp connection?

**Comment by sleirsgoevy** [comment]
No, it's HTTP only. It doesn't even support WebSockets. See https://github.com/localtunnel/server/blob/master/server.js

**Comment by defunctzombie** [comment]
It is http only.

**Comment by brandonros** [comment]
What would need to be done to add TCP support? Would it be a high level of effort?

**Comment by airjordan93** [comment]
> What would need to be done to add TCP support? Would it be a high level of effort?

+1 Badly need it!

**Comment by teknixstuff** [comment]
+1

**Comment by twisted-nematic57** [comment]
+1

**Comment by Lalit64** [comment]
+1

**Comment by teknixstuff** [comment]
> What would need to be done to add TCP support? Would it be a high level of effort?

I've realized it's pretty much impossible, as localtunnel relies on the HTTP HOST header to route requests.
The only way I can see this working is if someone makes a tool that runs on the tunnel client (the device accessing the tunnel) that listens on a local port and reroutes it to the tunnel server with a HOST header or something.
