### ISSUE TITLE
Unable to start LocalTunnel

### ISSUE THREAD

**Issue by ikumargaurav** [localtunnel/localtunnel#298]
I tried running localtunnel with command `lt --port 2019` but it didn't work. It didn't show any error message, any success/warnings. Absolute blank. I had to use `Ctrl + C` to come out of it.

I used `npm i -g localtunnel` to install it.

Can anyone help me??

**Comment by gegham1** [comment]
I have the same problem :(

**Comment by ikmrgrv** [comment]
> I have the same problem :(

Not able to resolve yet. I guess the project is not active anymore.

**Comment by BalliMontero** [comment]
I just did a fresh install and i have the same problem. I am running npm 6.4.1 on Windows 10 Pro x64, and I literally just did a fresh install but I can't seem to figure out what is wrong

**Comment by GhostRB47** [comment]
same here i cant even view help with `lt --help` and I always get this error
`C:\Users\<USER>\AppData\Roaming\npm\node_modules\localtunnel\bin\lt.js:8 `
`const { version } = require('../package');`
`      ^`
`SyntaxError: Unexpected token {`
`    at exports.runInThisContext (vm.js:73:16)`
`    at Module._compile (module.js:443:25)`
 `   at Object.Module._extensions..js (module.js:478:10)`
`    at Module.load (module.js:355:32)`
 `   at Function.Module._load (module.js:310:12)`
`    at Function.Module.runMain (module.js:501:10)`
 `   at startup (node.js:129:16)`
`    at node.js:814:3`

**Comment by pcl392578** [comment]
how to close a tunnel in command prompt ?? i want to close localhost tunnel which is created to use lt --port 8000 --subdomain mydom

**Comment by Yavor-Ivanov** [comment]
I'm getting the same behaviour. It used to work when I tried it a few weeks ago using the localtunnel.me. I haven't touched the localtunnel installation, so I don't know why it would refuse to give any output now.

I've tried both connecting to the default localtunnel.me server and hosting my own localtunnel server and connecting to it. Both times the `lt` command gave no output and just hanged until I terminated it.

**Comment by DevineJasper** [comment]
I have the same issue today. Yesterday, it worked all fine

**Comment by Hassancxpm** [comment]
I face the same problem today. I have tried every options like --allow-invalid-cert but it returns nothing on my terminal

**Comment by sebastiansommer** [comment]
Same issue here...

**Comment by Chaphasilor** [comment]
same here. using npx and also lt with a global npm install...
I see the travis tests fail with the last commit, but only for node 10, I'm on 12...
@defunctzombie any idea what's going on here? any workarounds?

**Comment by etoler1841** [comment]
Same issue. It was working fine a couple weeks ago, but now it hangs on init.

**Comment by etoler1841** [comment]
Same issue. It was working fine a couple weeks ago, but now it hangs on init.

**Comment by wabilin** [comment]
Same issue. Reproduced with `npx`.
Tried default server and my server.

**Comment by ReCoN-96** [comment]
same issue on MacOS 10.15.2 :(

**Comment by iljaiwjew** [comment]
same issue

**Comment by Ivanca** [comment]
same, tried to use an old version 1.9.2 but that just throws "tunnel server offline: certificate has expired, retry 1s"

**Comment by jannikbuschke** [comment]
Im having the same problem, I get no ouput (tested with npx and global install)

**Comment by mulaiko** [comment]
Same issue (On ubuntu)...No one to help?

**Comment by davidmwhynot** [comment]
I am also experiencing this issue on Windows 10 Pro. After running `npm i -g localtunnel`, then starting a new Powershell instance, running `lt --port 7000` produces no output and just hangs.
Some indication/verbose mode would be nice to find out (if anything) is actually happening. Where is the tunnel failing to connect? Is it stuck in some kind of inifite loop? There is no option I see to enable some kind of debug mode.

**Comment by A7madSab** [comment]
Same issue here.  No solution yet ?

**Comment by Ivanca** [comment]
I'm fearing this project has been abandoned.

**Comment by otsork** [comment]
This used to work on my computer just few days ago when my friend asked me to deploy something for him to see. Unfortunately I had this issue (https://github.com/facebook/create-react-app/pull/8079) which I thought was a problem with the localtunnel.

Today I deployed the app to heroku and I had the same problem that I linked above, which lead me back to localtunnel with the solution to the actual problem and now Im experiencing exactly the "hanging" issue you guys are talking about.

I dont think I have added any node modules since then, so I dont think its a dependancy issue. I'm just baffled.
I'd really appreciate if anyone finds a solution for this.

**Comment by sasagr** [comment]
I found this workaround. Add -h http://localtunnel.me/ and use the url with http instead of https

**Comment by Kikobeats** [comment]
Enabling debug logs with `DEBUG=*` show some related information


```
  localtunnel:client tunnel server offline: connect ECONNREFUSED 92.51.164.34:443, retry 1s +1s
  follow-redirects options {
  protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/?new',
  method: 'GET',
  headers: {
    Accept: 'application/json, text/plain, */*',
    'User-Agent': 'axios/0.19.0'
  },
  agent: undefined,
  auth: undefined,
  hostname: 'localtunnel.me',
  port: null,
  nativeProtocols: {
    'http:': {
      _connectionListener: [Function: connectionListener],
      METHODS: [Array],
      STATUS_CODES: [Object],
      Agent: [Function],
      ClientRequest: [Function: ClientRequest],
      IncomingMessage: [Function: IncomingMessage],
      OutgoingMessage: [Function: OutgoingMessage],
      Server: [Function: Server],
      ServerResponse: [Function: ServerResponse],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request],
      maxHeaderSize: [Getter],
      globalAgent: [Getter/Setter]
    },
    'https:': {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function: get],
      request: [Function: request]
    }
  }
}
```

**Comment by igauravsehrawat** [comment]
https://github.com/localtunnel/localtunnel/issues/343

**Comment by LukeZzzHD** [comment]
The Server isn't offline though, ping 92.51.164.34 works fine

**Comment by Chaphasilor** [comment]
@sasagr this isn't working for me, which is no surprise as browsing http://localtunnel.me or 92.51.164.34 doesn't respond with a web page. The server responds to pings, but there doesn't seem to be a server running.

I'm guessing what happened is that first the ssl certificate expired, resulting in the tunnel not opening, and now either the domain expired as well or the server that was used to host the backend isn't rented anymore. I guess this project is dead :/

But, over at https://github.com/localtunnel/server you can find the backend, so you could set it up yourself :)

**Comment by igauravsehrawat** [comment]
It was great while it was running. But free stuff can't last forever. 
We should donate for server and domain hosting. Sign me up.

**Comment by przano** [comment]
I thought @Pirngruber had taken over hosting #338

**Comment by Chaphasilor** [comment]
ahh I see, I guess then we'll have to wait until localtunnel.me is back up

**Comment by dz-s** [comment]
@igauravsehrawat or at least make PR displaying error/notification when smth went wrong.

**Comment by przano** [comment]
So I am guessing this project is now dead. Combination of original #332  @defunctzombie host certificate expiring, @Pirngruber taking over for a while now absent, looks like this is over. Bummer.

**Comment by defunctzombie** [comment]
I recommend folks use https://ngrok.com/.

**Comment by igauravsehrawat** [comment]
I have seen lot of corporate network blocking ngrok and similar sites.

If you have your own person domain.
Checkout my blog post for building your ngrok in 4 easy steps 
https://igauravsehrawat.com/build-your-own-ngrok-4-easy-steps/

**Comment by oxihormesis** [comment]
Yep serveo is down too. Bugger

**Comment by Kikobeats** [comment]
A minute of silence for a great project with terrible maintainers

**Comment by hayashi-ay** [comment]
workaround is here https://github.com/localtunnel/localtunnel/issues/344

**Comment by Smit12345** [comment]
please try below code:

 "webhook": "lt -h 'http://serverless.social' -p 5000"

**Comment by Smit12345** [comment]
add in package.json file

**Comment by adnankhankhadukhel** [comment]
lt -h "http://serverless.social" -p 3000  
this worked for me.

**Comment by OtacilioN** [comment]
F for respect

**Comment by marvinahv** [comment]
> lt -h "http://serverless.social" -p 3000

It doesn't seem to be working anymore.

**Comment by PhilzAce1** [comment]
I feel the project has been abandoned ... that is why it is not working

**Comment by PhilzAce1** [comment]
> lt -h http://serverless.social -p 3000 

this is the fix i found that works well

**Comment by felipemarques** [comment]
> please try below code:
> 
> "webhook": "lt -h 'http://serverless.social' -p 5000"

thankyou so much!!

**Comment by Joshuauche** [comment]
> please try below code:
> 
> "webhook": "lt -h 'http://serverless.social' -p 5000"

thanks

**Comment by douglasulmer** [comment]
Use lt -h "https://serverless.social" -p PORT

**Comment by TheBoroer** [comment]
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain *.loca.lt instead of *.localtunnel.me (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

**Comment by jehkinen** [comment]
> I recommend folks use https://ngrok.com/.

this soft ask 60$ for even one tunnel, free version is very bad to use

**Comment by dluc** [comment]
The service works fine, but I had to use `-l 127.0.0.1` to make it work, also for custom installations.

`curl http://127.0.0.1:8000/` => works
`curl http://10.0.0.100:8000/` => works
`curl http://localhost:8000/` => works

`lt -p 8000 --print-requests -o` => **doesn't work**
`lt -p 8000 -l 127.0.0.1 --print-requests -o` => works
`lt -p 8000 -l 10.0.0.100 --print-requests -o` => works

**Comment by MohammedMostafaWebDeveloper** [comment]
Try this:
install local tunnel using npm
`npm i -g localtunnel`
run your node JS file using `node ` + filename
Open another command or terminal then run `lt --port 2019`

**Comment by Hermanverschooten** [comment]
@dluc I had a similar issue and using the `DEBUG=*` I noticed that it was trying to connect to my webserver using IPv6 on `::1:4040`. I changed my server to also listen on IPv6 and it worked again.
```
 localtunnel:client local error connect ECONNREFUSED ::1:4040 +0ms
```

**Comment by GitXpresso** [comment]
Refreshing the tab when you get the nginx error worked for me

**Comment by WilliamDEdwards** [comment]
Running the client 'hangs' (?) for me when using IPv6 on the server. Hello, 2026?

Specifying `--address ::` (defaults to `0.0.0.0`) makes the server listen on IPv6, but the server doesn't seem to be taking connections.

Tried working around this by directly specifying the IPv4 address (blegh), but it seems like `--domain` (server) gets ignored then, because I end up with this 'URL':

http://rotten-grasshopper-57.185.233.175.188:1234
