### ISSUE TITLE
High severity vulnerability: axios

### ISSUE THREAD

**Issue by limonte** [localtunnel/localtunnel#302]
https://snyk.io/vuln/SNYK-JS-AXIOS-174505

https://github.com/sweetalert2/sweetalert2/network/alert/yarn.lock/axios/open

https://github.com/axios/axios/issues/2183

**Comment by gaards** [comment]
Fixed by https://github.com/localtunnel/localtunnel/commit/be3dc1a4cc8bf55ac3918ee51611979d1895e986, included in the 1.9.2 release. This issue can be closed.

**Comment by limonte** [comment]
Yup, all good now, thank you @gaards
