### ISSUE TITLE
tunnel server offline with status code 502

### ISSUE THREAD

**Issue by Liliano1044** [localtunnel/localtunnel#313]
Since this morning (in France), I have this error when I launch localtunnel :
tunnel server offline: Request failed with status code 502, retry 1s.

Same thing when I want to connect to the site https://localtunnel.me/

It's really problematic because I am using this solution for my scheduled tests and they are KO because this issue.

Thx for your response

**Comment by nikolasok** [comment]
I have the same problem, it appeared only today

**Comment by rahulspace** [comment]
I'm showing this error
`tunnel server offline: Request failed with status code 502, retry 1s`
Same problem (in India)
![Screen Shot 2019-06-27 at 2 09 44 PM](https://user-images.githubusercontent.com/34391727/60250980-4b505780-98e5-11e9-8377-50f7f9ed73c2.png)
The site is down for ~19 hours

**Comment by jandspace** [comment]
I have the same problem in UK which has suddenly happened as it worked even yesterday.
How to fix it?
![image](https://user-images.githubusercontent.com/8191832/60266271-a2532e00-98df-11e9-8f0d-c2b852ad2153.png)

**Comment by pablolopesk8** [comment]
Same problem in Brazil!
Anyone have an position or answer about this?

**Comment by appsolut-jahn** [comment]
Server is still down. Is there anybody working on it?

**Comment by BaharaJr** [comment]
Anybody worked around localtunnel? It is still down for everyone

**Comment by aethanol** [comment]
same, you can host your own which would solve your problem: https://github.com/localtunnel/localtunnel/issues/293#issuecomment-473659941

**Comment by ian** [comment]
Still down

**Comment by zaplachinsky** [comment]
Still down

**Comment by fzs111** [comment]
Same issue, Hungary. 😢

**Comment by MarkPartlett** [comment]
I've set up my own localtunnel server : http://www.leadmetomy.computer/ , it is easy to do.

**Comment by fabrizioPucci** [comment]
@MarkPartlett , I have tested leadmetomy ... but there is no documentation.
I am in the place where I should insert Username & Password but of what account?
What username?
What account?

**Comment by fzs111** [comment]
@MarkPartlett I've tried it just now, for me, it shows a blank page with a 404 text on it

**Comment by ian** [comment]
Everyone: Just use ngrok. Doesn't seem like this is going to get fixed.

**Comment by victorgmp** [comment]
Same issue, Venezuela T-T

**Comment by ananda604** [comment]
Why are the developers not answering ?! Im  kinda stuck here in the middle of a project!

**Comment by arunarn2** [comment]
Is it possible to get a resolution on this ASAP?

**Comment by fzs111** [comment]
You could look at [this page](https://alternativeto.net/software/localtunnel/).
It says, that *localtunnel is **discontinued***. Not too good outlook...
It also lists some alternatives, but none of them offers unlimited service for free, as localtunnel did :(

What we can do, is to pay, accept limitations, or hope, that localtunnel comes back.

I do the third!

**Comment by ian** [comment]
@defunctzombie are you looking for a maintainer?

**Comment by jandspace** [comment]
> Is it possible to get a resolution on this ASAP?

If you dont mind a temporary solution...
I use it to run gulp, so what i did is that at first I disconnected the internet. Then run gulp, gulp works (do not quit it). Then connected the internet again. Browsersync will probably work, unless you close running gulp. I am not sure if it works to your case, mine works though.

**Comment by MarkPartlett** [comment]
Sorry, I wasn't suggesting using http://www.leadmetomy.computer/  , as it is a paid subscription based service. The username/password is supplied with the subscription.

I was suggesting setting one up using : https://github.com/localtunnel/server 

Sorry the the confusion.

**Comment by momoduoladapo** [comment]
Same issue here with localtunnel, running the command from Nigeria

**Comment by momoduoladapo** [comment]
Hey it finally worked for me, i just left the terminal running and look your url is: https://momoduoladapo.localtunnel.me

**Comment by arunarn2** [comment]
The issue seems to be resolved. https://localtunnel.me is now loading too

Thanks @defunctzombie  for taking care of this.

**Comment by fzs111** [comment]
Yes! It's working again! Thank you, *localtunnel*!

**Comment by Liliano1044** [comment]
Hi! ok it is solved but because I couldn't wait, i found a solution with ngrok and a command line to get the generate url and use it in my scripts. And it seems ngrok is less unstable. I tried the solution with localtunnel-server but without success

**Comment by defunctzombie** [comment]
The localtunnel server experiences times of high load and instability because it is a free public service. Often retrying (as suggested in the comments) helps.

If you need a reliable test server you can setup your own localtunnel server backed (see the server repo).
