### ISSUE TITLE
tcp port range

### ISSUE THREAD

**Issue by mynameismaxz** [localtunnel/localtunnel#316]
I want to use the limit TCP proxy port because on the localtunnel-server, I just forward port around 100 TCP ports. how can I adjust the parameter to use this?

**Comment by mvhirsch** [comment]
The [localtunnel/server](https://github.com/localtunnel/server) only publishes one port, often this is 80 (HTTP). I don't think, you want to use localtunnel for your use-case, instead just use any TCP proxy of your choice, opening multiple ports on one domain.

**Comment by mynameismaxz** [comment]
in `localtunnel/server`, I just forward port 80 only but in the client of localtunnel when start to custom server it shown `connect refuse`. How can I fixing it?

**Comment by defunctzombie** [comment]
Localtunnel does not support port ranges.
