### ISSUE TITLE
tunnel crashes within 5 mins of starting

### ISSUE THREAD

**Issue by CSRaghunandan** [localtunnel/localtunnel#320]
I was using the default host for localtunnel and running `lt` on a raspberry pi for testing purposes and observed that the tunnel does not stay active for more than 5 minutes. `lt` mentions that the link is active, but when I open the link on the browser, nothing happens. The server on the box is configured properly (tested to work fine with ngrok)

Any idea what is causing this? Is this a known problem? How do I debug this issue?

**Comment by defunctzombie** [comment]
Known problem - server is a bit unstable given that it is a free service open to the public.
