### ISSUE TITLE
Unhandled 'error' event after creating a tunnel

### ISSUE THREAD

**Issue by dhavalhparikh** [localtunnel/localtunnel#321]
Hi @defunctzombie,
I receive the following error after creating the tunnel using the node.js API:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: localtunnel.me:39204 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

The time it takes to error out is not constant. Sometimes it errors out as soon as it creates a tunnel and sometimes it takes a few minutes or even hours.

What could be the issue here?
How do I debug it?

Thank you,
Dhaval

**Comment by dhavalhparikh** [comment]
@defunctzombie Any insights on what could be going on?
Thanks!

**Comment by defunctzombie** [comment]
The localtunnel server sometimes has issues. The error message is not ideal - I might get around to making it better it in a later version.

**Comment by dhavalhparikh** [comment]
@defunctzombie Ok. But how do I handle that issue?

**Comment by defunctzombie** [comment]
Try again. It should eventually work.

**Comment by dhavalhparikh** [comment]
@defunctzombie I want to catch that error and reconnect automatically and not do it manually everyday.

**Comment by defunctzombie** [comment]
Please see other issues that have tips on how to handle retrying. Practically - localtunnel is designed for short ephemeral testing rather than long lived sessions that you keep open for a long time.
