### ISSUE TITLE
Tunnel not starting

### ISSUE THREAD

**Issue by iMichaelOwolabi** [localtunnel/localtunnel#322]
I tried to create a tunnel on my local port but the tunnel never gets created and it just hangs on the lt --port screen
Is anyone experiencing this same issue currently?

<img width="566" alt="Screenshot 2019-09-10 at 1 38 13 PM" src="https://user-images.githubusercontent.com/20207295/64614392-4ffab700-d3d0-11e9-9b36-1479b7dbf9d3.png">

**Comment by defunctzombie** [comment]
Not enough info here to debug - maybe the server was experiencing a temporary issue.
