### ISSUE TITLE
Localtunnel is very slow

### ISSUE THREAD

**Issue by GalaxJann** [localtunnel/localtunnel#328]
I have a problem with localtunnel. I have a Raspberry Pi 4B (OS: Raspbian) installed and i will use NextCloud on this. Our Network is a CG-NAT, which means that it is impossible for me to host this Cloud without an tunneling Service.

Localtunnel is installed from Node (npm) and it is generally working. But the connection is **very** slow. I have Response Times >130ms and a Download Rate about 0.8Mbps* and a Upload Rate <0.5Mbps*.

I have used Serveo (serveo.net) before and it was such fast as our Internet Speed (about 30Mbps* Download and 8Mbps* Upload) when i accessed my Cloud from Outside. The Problem is that Serveo is very "unstable", which means that this Service has an Uptime from  a half a day, and after this an downtime from 2-3 days. I am searching for free alternatives where i can select my own Subdomain (like Serveo and localtunnel).

How i can solve this problem with the speed?

*Mbps = Mega**bit** per second, not Mega**byte**.

**Comment by TheBoroer** [comment]
Closing stale issue.

For the future readers; if you need better performance then your best bet is to get a cheap VPS and self-host a private instance of [localtunnel server](https://github.com/localtunnel/server).
