### ISSUE TITLE
Crashes when data comes in

### ISSUE THREAD

**Issue by mhornbacher** [localtunnel/localtunnel#330]
When traffic comes in from the web the tunnel seems to crash

Error message thrown:

```
$ lt --port 2990 --subdomain jira-slack
your url is: https://jira-slack.localtunnel.me
C:\Users\mende\AppData\Roaming\nvm\v12.11.0\node_modules\localtunnel\bin\lt.js:81
    throw err;
    ^

Error: connection refused: localtunnel.me:43943 (check your firewall settings)
    at Socket.<anonymous> (C:\Users\mende\AppData\Roaming\nvm\v12.11.0\node_modules\localtunnel\lib\TunnelCluster.js:52:11)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Screenshot of page on localtunnel:**

![image](https://user-images.githubusercontent.com/12478828/69399248-66b86680-0cbb-11ea-84f6-59aab5d2f3fc.png)

**Notes**

1. The server running on localhost:2990 (jira) does not receive any incoming traffic. Also this was replicated on 2 machines and 3 networks (1 commercial 2 residential) and the same error occurred on each one so it is likely not the firewall....
2. With the localtunnel running Jira cannot start as port 2990 is claimed, is this perhaps the problem in reverse? If so what is the point of `localtunnel`
3. Worked with Jira 7 a month ago

**Details:**

Port: 2990
OS: Windows 10
NodeJS version: 12.11
Server on Port 2990: Jira (atlas-run)

**Comment by jakubhomoly** [comment]
try running it via npx

```
npx localtunnel --port 2990 --subdomain jira-slack
```

🤷‍♂

**Comment by fatihhidiroglu** [comment]
Thanks @jakubhomoly . Your solution worked for me.
