### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by bargenson** [localtunnel/localtunnel#332]
Hey 👋 
The certificate seems to have expired. Could you renew it?
Here the message I get from the `localtunnel` command:
```
tunnel server offline: certificate has expired, retry 1s
```
The certificate of localtunnel.me:

![image](https://user-images.githubusercontent.com/433287/70582188-a02c1580-1b87-11ea-8da0-e24535a3b66e.png)

Thanks!

**Comment by arunarn2** [comment]
Experiencing the same issue. Can this be fixed ASAP?
thanks

**Comment by andrewralon** [comment]
What's the current status?

**Comment by Lauren-penner** [comment]
I am assuming the issue I am experiencing is related. Local tunnel hangs when trying to initialize.

**Comment by WBDC** [comment]
> I am assuming the issue I am experiencing is related. Local tunnel hangs when trying to initialize.

Same here, I think its related to it. Can't be a coincidence. 

I'm just exploring ngrok as looking the number of open issues and the dev's (lack) of replies I think I will move to somewhere more stable.

**Comment by rrigoni** [comment]
Same here. Any estimation on a fix?

**Comment by daniml3** [comment]
Same here, localtunnel not working, i supose that's the reason.

**Comment by mybottt** [comment]
Facing same issue.
A workaround is to use _-h http://localtunnel.me_ when initializing (notice http instead of https)
and open http link instead of https in browser

**Comment by devjones** [comment]
> Facing same issue.
> A workaround is to use _-h http://localtunnel.me_ when initializing (notice http instead of https)
> and open http link instead of https in browser

Thank mybott.  To anyone doing this, just make sure you're not sending any sensitive data over localtunnel from a coffeeshop.

**Comment by arunarn2** [comment]
still seems to be connecting to https
```

/usr/bin/lt --port 4567 -h http://localtunnel.me --subdomain mydomain
your url is: https://mydomain.localtunnel.me

```
Am I missing something here?

**Comment by devjones** [comment]
@arunarn2 You need to remove the replace the `https` to `http` in the url localtunnel returns if you're using this workaround.

**Comment by arunarn2** [comment]
@devjones Yes i am using the http in the url

`/usr/bin/lt --port 4567 -h http://localtunnel.me --subdomain mydomain`

**Comment by devjones** [comment]
@arunarn2 What I'm saying is ignore the stated output and replace the https in the output to http

**Comment by arunarn2** [comment]
@devjones got it 
thanks

**Comment by arunarn2** [comment]
Hi @defunctzombie ,
Is it possible to get the certificate updated?

thank you for your immediate assistance.

**Comment by arielrahmane** [comment]
Hi @defunctzombie 
I need to present a work on Tuesday and you can save me from paying 60 bucks to ngrok. I need the custom subdomain 🙏

Thank you!

**Comment by arielrahmane** [comment]
@defunctzombie 
If you are not willing to renew the certificate, would be useful to be notified. 

Thank you again. And sorry for the pressure.

**Comment by WBDC** [comment]
> @defunctzombie
> If you are not willing to renew the certificate, would be useful to be notified.
> 
> Thank you again. And sorry for the pressure.

Completely agree with you. I am sure the certificate doesn't cost more than $30 and we all would chip in. If he doesn't want to renew it then we should be notified so we can move on and find another solutions, but waiting is not an option in most cases. 

I've now moved to ngrok. Its actually lovely and its free to a certain level. If need a bit more resource then $5/month is not a biggie. Nice API as well.

**Comment by ricardodantas** [comment]
Yeah, the fast solution was to move to Ngrok, they also have a nice node client and API.

**Comment by pociej** [comment]
We went with self hosted solution.

**Comment by nicolapalavecino** [comment]
Having the same issue. @defunctzombie you could set up a button for donation in https://localtunnel.github.io/www/, I'm sure many of us will donate some money for this awesome tool

**Comment by LWFlouisa** [comment]
That explains everything!

**Comment by tzahari** [comment]
Why not using the free Lets Encrypt Wildcard certificate? 
https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates

**Comment by pardini-net7** [comment]
The http workaround doesn't seem to work, please update the certificate!

**Comment by nicolapalavecino** [comment]
> Why not using the free Lets Encrypt Wildcard certificate?
> https://letsencrypt.org/docs/faq/#does-let-s-encrypt-issue-wildcard-certificates

The certificate used was a wildcard actually, the problem here was that it expired some days ago and there is no automatic mechanism for issuing a new certificate, I think @defunctzombie does it manually.

> The http workaround doesn't seem to work, please update the certificate!

The http workaround works but not using chrome. I tested it on safari and seems to work. I think this is because Google has some sort of blacklist of domains that change their whole layout periodically and tags them as phishing sites, which Apple does not. I didn’t check this information, but could explain why it doesn’t work on chrome.

**Comment by shoaibmal** [comment]
I managed to get it working after adding  `-h http://localtunnel.me --local-https false`

**Comment by LWFlouisa** [comment]
Observation: It seems to periodically switch between http and https depending on some unknown factors.

**Comment by georgevlad42** [comment]
@shoaibmal is it possible to use this workaround inside a JavaScript function?

**Comment by shonubijerry** [comment]
`-h http://localtunnel.me --local-https false --allow-invalid-cert true` worked for me

**Comment by Pirngruber** [comment]
hi,
still no info :(
if you need to you guys can use mine in the meanwhile, just connect to 

-h https://tunnel.datahub.at

**Comment by LWFlouisa** [comment]
@Pirngruber What are the specs on it? Would it be able to fit a Gitea hub? I tried using normal localtunnel for it, but it just comes up blank for that port.

**Comment by Pirngruber** [comment]
@LWFlouisa should be fine for that, just watch out your local config since localtunnel will only map one port per localtunnel instance

**Comment by alexmassicott** [comment]
@Pirngruber you are the real mvp, thank you

**Comment by krazy707** [comment]
> 
> 
> hi,
> still no info :(
> if you need to you guys can use mine in the meanwhile, just connect to
> 
> -h https://tunnel.datahub.at
Just tested the server,  it's working ,  also https worked,   I tried to deploy own server, but stuck at http only,   can you please provide the modification or steps to enable https

**Comment by krazy707** [comment]
@Pirngruber

Just tested the server, it's working , also https worked, I tried to deploy own server, but stuck at http only, can you please provide the modification or steps to enable https

**Comment by Pirngruber** [comment]
@krazy707 yeah the localtunnel server itself is running on some port like 3000 and in front of that i‘ve set up a nginx reverse-proxy just for the ssl for *.tunnel.datahub.at with wildcard cert from letsencrypt and tunnel.datahub.at with normal ssl cert also from letsencrypt.  With auto renewal through certbot.

**Comment by krazy707** [comment]
@Pirngruber   good idea thanks.

**Comment by Pirngruber** [comment]
Ah and forget docker for that, thats completely senseless since you‘ll have to switch to „networkmode host“ to get the tcp tunnels from outside to the docker container.
big security issue and like i already said senseless

**Comment by rahulmathews** [comment]
Any update over it. I am facing the same issue.

**Comment by TiagoSilvaPereira** [comment]
Any update?

**Comment by alexeyoganezov** [comment]
It looks like public localtunnel server is abandoned but it's totally understandable: it costs money, requires efforts on maintaining and in the meantime generates no profit at all. 

So I have a suggestion to everyone who uses it: please setup your own localtunnel server, it's more or less easy and you won't depend on @defunctzombie and limited bandwidth (public server was slow anyway). Localtunnel is a absolutely great tool that helped me a lot in my job and 100% sure it's worth of 5$ on some VPS.

**Comment by l4jos** [comment]
> Facing same issue.
> A workaround is to use _-h http://localtunnel.me_ when initializing (notice http instead of https)
> and open http link instead of https in browser

Does not make difference.

**Comment by Pirngruber** [comment]
I‘ve just asked @defunctzombie on twitter if he wants me to host and maintain the localtunnel.me server... lets see

**Comment by metinavc1** [comment]
it still doesn't work. is there any solution?

**Comment by Aissaoui-Ahmed** [comment]
> it still doesn't work. is there any solution?

[See comment ](https://github.com/localtunnel/localtunnel/issues/332#issuecomment-567226542)

**Comment by mahnunchik** [comment]
Hi @defunctzombie Any news?

**Comment by mahnunchik** [comment]
Thank you @Pirngruber https://github.com/localtunnel/localtunnel/issues/332#issuecomment-567226542

I am able to connect. Just for the information of users: custom server must be without a landing slash `lt --host=https://tunnel.datahub.at` not `lt --host=https://tunnel.datahub.at/` 😉

**Comment by Pirngruber** [comment]
HEY HEY ;) 

localtunnel.me is now up and running again ;) i'm hosting it now.

also if you want to support it to not go down again, feel free to donate and support with the hosting fees ;) Donation possible at https://localtunnel.me

**Comment by przano** [comment]
Hi @Pirngruber , thanks for taking over hosting. Quick question, is the https version of this working? Or only the http version?

**Comment by Pirngruber** [comment]
@przano yes https is working too

**Comment by siideffect** [comment]
hi, is it possible to supply self signed certificates when running the server to avoid this type of issue? Im facing many problems with the current certificates due to ATS during iOS development. SSL labs reveals a "Certificate name mismatch " error

**Comment by przano** [comment]
I think my problem might be tied to/related to @siideffect. While it appears launching a localtunnel with custom subdomain is returning an https url, my application using a webhook is returning an error (Dialogflow). Reading the "malformed response" and googling indicates an issue with the cert. Is there something different with this certificate as compared to the previous one used by @defunctzombie and/or @Pirngruber 's temporary tunnel.datahub.at? Both of those worked. Now this doesn't. I'm a noob, so go easy on me :)

**Comment by Kacper1263** [comment]
Does anyone know why the tunnel in the node.js script currently works only without a custom subdomain? Before the problems with the certificate, everything was ok.

**This code works, tunnel is starting with random subdomain**
`const tunnel = await localtunnel({port: tunnelPort})`

**This code isn't working, tunnel is not starting**
`const tunnel = await localtunnel({port: tunnelPort, subdomain: tunnelSubdomain})`

**Comment by georgevlad42** [comment]
Do you guys get a 504 Gateway Time-out now?

**Comment by Pirngruber** [comment]
soo @georgevlad42 & @przano everything should be up and running finally. 

both names localtunnel.me & tunnel.datahub.at are up and have valid certs on all endpoints. the other problems like the 504 were because of the last updates which had to be done :)

let me know if something doesn't work like expected

**Comment by georgevlad42** [comment]
The issue is still occurring, it worked like 5 minutes ago, but now it doesn't

**Comment by przano** [comment]
It is working now @Pirngruber ! Thank you so much. I love learning, and i'm not very knowledgeable on these things, so what exactly was the issue that you corrected? Just curious.

**Comment by Pirngruber** [comment]
@przano 

Localtunnel is running and waiting for new clients on port 443 of the domain localtunnel.me therefore there has to be a valid ssl-cert for localtunnel.me 
If a new client connects there, the server tells him the port (for example 4315) and a subdomain like abc.localtunnel.me so now the reverseproxy (nginx in our case) has to serve the correct ssl-cert for *.localtunnel.me and terminate the tls to let the https request of your browser connect to the correct port.

The wildcard (*.localtunnel.me) certificate was the problem. 

And remember: it‘s not a problem if you’re not experienced right now, try to ask as much as you can and try things by yourself

**Comment by Pirngruber** [comment]
@georgevlad42 do you still have those issues or is it stable now? Let me know

**Comment by mkupiniak** [comment]
Great job @Pirngruber!

**Comment by Tamapw** [comment]
> @georgevlad42 do you still have those issues or is it stable now? Let me know

Yesterday everything worked fine and the tunnel was being created. Today does not want to be created in any way. 
From the console just hangs without a response. 
The js-library returns the error " localtunnel server returned an error, please try again"

If i use ` lt -p 3001 -h http://localtunnel.me --local-https false` i get the link, but my local server don't show on the link, i'm getting the `502  Bad Gateway`

http://localtunnel.me is off?

**Comment by mahnunchik** [comment]
> 502 Bad Gateway
> nginx/1.14.0 (Ubuntu)

😭

**Comment by Pirngruber** [comment]
Since there still are some issues occuring, I’ll turn off the tunnel.datahub.at instance and focus on the localtunnel.me one

I think localtunnel/server is not designed for a multiinstance environment ;)

**Comment by mahnunchik** [comment]
https://sweet-walrus-9.localtunnel.me/

`Invalid Host header` 😢

**Comment by bboure** [comment]
@Pirngruber 
localtunnel.me seems have been down for several days now. 
Are you still running it?

**Comment by kylerchin** [comment]
Is this place dead? my plugin is giving me `tunnel server offline: unable to verify the first certificate, retry 1s`
I'd be happy to chip in for the certificate cost.

**Comment by susenj** [comment]
can someone just confirm or deny that this service still being maintained or no?
```
504 Gateway Time-out
nginx 1.14.0 (Ubuntu)
```

**Comment by Kacper1263** [comment]
I can confirm that localtunnel domain is still not working but I'm using serverless domain and its working without problems.
You can start tunnel on this domain by setting host to: https://serverless.social.

Example
`lt -s tunnel-test -p 5000 -h https://serverless.social`

**Comment by susenj** [comment]
@Kacper1263 , doesn't seem to be working still.
![image](https://user-images.githubusercontent.com/291550/91632537-1666f580-e9ff-11ea-9b7c-9aff36c1cf11.png)

**Comment by Kacper1263** [comment]
@susenj , for me its working right now. I'm starting my server on port 5000 then I'm starting tunnel on port 5000 and subdomain next-test and as You can see in background i have access to my server. 
![obraz](https://user-images.githubusercontent.com/43702481/91633326-a600aa00-e9e7-11ea-9c05-586906cfdc2c.png)

**Comment by TheBoroer** [comment]
Hey everyone,
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain *.loca.lt instead of *.localtunnel.me (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

**Comment by TheBoroer** [comment]
@defunctzombie feel free to close this issue.
