### ISSUE TITLE
things working fine till now localtunnel is not even starting

### ISSUE THREAD

**Issue by hardik7290** [localtunnel/localtunnel#335]
things working fine till now localtunnel is not even starting and look like it got stuck

and i waited about 15 minutes and long.

![image](https://user-images.githubusercontent.com/19410263/70850765-08466880-1eb4-11ea-9ddc-f2423deb159d.png)

what happen?

**Comment by hardik7290** [comment]
same issue closed #322 and i try ngrock for testing and it worked

**Comment by thesunRider** [comment]
Same with me the screen goes blank

**Comment by MatissJanis** [comment]
The server is still unresponsive :(

**Comment by dariatsenter** [comment]
Same for me :(

**Comment by benheb** [comment]
Same...

**Comment by smithki** [comment]
Same here :(

**Comment by vensauro** [comment]
Hello, the problem is with the certificate, see the solution in the issue #332 
```
$ lt -p 8000 -h http://localtunnel.me --local-https false
```

**Comment by vlatri** [comment]
bump.

**Comment by proflinksgh** [comment]
Same issue here oo.... Currently on ngrok but session terminates every 7hrs

**Comment by GeorgeWillaman** [comment]
Bump.. Still not working for me

**Comment by noriellecruz** [comment]
Is this issue will ever be fixed? The author seems to be inactive for long.

**Comment by GeorgeWillaman** [comment]
For all interested, I've moved over to https://holepunch.io/
Working great for me for the time being (+ positive is I can reserve and use subdomains of my choosing)

**Comment by adis-io** [comment]
> Hello, the problem is with the certificate, see the solution in the issue #332
> 
> ```
> $ lt -p 8000 -h http://localtunnel.me --local-https false
> ```

If you need https, you can use @Pirngruber's server temporarily:
```
lt -p 8000 -h https://tunnel.datahub.at
```

**Comment by uditalias** [comment]
still not working with:
`lt -p 8080 -h http://localtunnel.me --local-https false`

**Comment by yohane55** [comment]
https://localtunnel.me/ is down as of now. :(

**Comment by smithki** [comment]
Is this the end? 😢

**Comment by lozzoc** [comment]
> same issue closed #322 and i try ngrock for testing and it worked


uhh im developing web app and ngrok did not work for. i kept getting errorslike "wrong host headers"

farewell localtunnel! looks like we reached theend.

**Comment by Pirngruber** [comment]
localtunnel.me is now up and running again :)
i took over the hosting and maintenance part from @defunctzombie so feel free to use it as before.

let us know if you have further questions

**Comment by DannyvanderJagt** [comment]
@Pirngruber It down again. Any plans on making it more stable and do something about the uptime?

**Comment by cjancsar** [comment]
Ah, that is why this library doesn't work....

**Comment by wrabit** [comment]
down and out

**Comment by lozzoc** [comment]
I used to use localtunnel to test out my web sites on my mobile and desktop devices, but now i just use the proxy in package.json with my react project, and use the local ip 10.0.0.27. How else have people used to use localtunnel?

**Comment by DavidOlawale** [comment]
I had the same issue, localtunnel no longer works, you can try ngrok

**Comment by TheBoroer** [comment]
I am now hosting localtunnel.me for this project so it should work like before. The only difference is that I'm handing out subdomains under the domain *.loca.lt instead of *.localtunnel.me (that's because I don't have full DNS control and without it can't get a free wildcard cert for the domain without). Let me know if you run into any issues.

**Comment by TheBoroer** [comment]
@defunctzombie feel free to close this issue.
