### ISSUE TITLE
Using localtunnel to set up a port-slave

### ISSUE THREAD

**Issue by IngwiePhoenix** [localtunnel/localtunnel#342]
Hey!

I am usually working on projects locally and want to share them with my friends, or sometimes just outright run applications on my server at home as they do not need all the bandwidth - and, in fact, my bandwidth is really really good (400mbit/s down, 20mbit/s up) for Germany. So, I want to take advantage of that.

I would like to create a setup where I am using my dedicated server (`ingwie.io`) and it's configured reverse-proxy to act as an access point to my homeserver (`home.ingwie.io`). The reason why I am giving this subdomains has two reasons:

1. `home.ingwie.io` is supposed to be what localtunnel is reachable at.
2. `ingwie.io` is just a reference to the dedicated server itself.

Now, what I would like to be able to do is to create a tunneled port from my homeserver's `8080` port to my dedicated server - let's say `127.0.0.1:668080`, with the `66` part acting as a prefix. Now, I could configure NGINX to `proxy_pass` requests to that local 668080 port, which would in turn go back to my homeserver and effectively serve the page there.

Seeing as localtunnel provides a public REST API, I would rather have this protected, as only I want to be able to open and close ports. In fact, I would set up launchd services on the homeserver - it's a 2008 Mac Mini, thus runs macOS - to autostart and connect to the dedicated server to re-connect on startup.

Would a setup like this be possible, and does it only work with HTTP or also TCP? I do not really care for UDP, but HTTP and raw TCP would be handy to have.

I did figure that I would have to run a localtunnel server at `home.ingwie.io`, make that publicy available and later pass that to the localtunnel client to connect to. But, from there on out, my firewall won't allow those ports by default anyway. So how can I tell localtunnel to:
- Bind the tunnel-ports on `127.0.0.1` instead to `0.0.0.0`?
- Password/Passphrase protect it, so that only maschines I want to open ports can do so?

Configuring NGINX is the smaller problem; I do have a template for that myself.

Would that be possible, and if so, how? :)

Kind regards,
Ingwie

**Comment by TheBoroer** [comment]
Old issue but still posting a potential solution if anyone else wonders this.
You can't use localtunnel for this. 
A bit more complicated solution would be to use a VPN connection between the home server to the Public VPS server, and then do some port forwarding rules on the vps to direct the public vps port through the vpn to the home server / port.
