### ISSUE TITLE
Can't access localtunnel

### ISSUE THREAD

**Issue by nitingupta220** [localtunnel/localtunnel#346]
I have installed the localtunnel globally on my laptop and run the command ```lt --port 8000``` but in the terminal I got nothing. The command just runs and did nothing. Even I tried using the localtunnel API but still the same thing happened to me.
Can anyone help? @dscape @adammck @davej @joshuaxls @TooTallNate

**Comment by ChristopherLMiller** [comment]
just tried using myself and same thing,  proxy down?

**Comment by nitingupta220** [comment]
Is the service up or not?

**Comment by gauravbhaskar84** [comment]
Looks like it has been down for a few days.

**Comment by yukulele** [comment]
https://github.com/localtunnel/localtunnel/issues/343

**Comment by TheBoroer** [comment]
@defunctzombie feel free to close this issue.
