### ISSUE TITLE
Support for minecraft server protocol

### ISSUE THREAD

**Issue by khrj** [localtunnel/localtunnel#359]
Hi!
I'm trying to tunnel a minecraft server, but I get "Unknown host" in minecraft.

However, I've successfully managed to run the minecraft server using [ngrok](https://ngrok.com/):
```
❯ ngrok tcp -region in --log=stdout 1025
```

Is it possible to support the minecraft protocol?
Thanks for making the project!

**Comment by TheBoroer** [comment]
What kind of protocol does minecraft use? standard tcp connections?
If you have a quick example minecraft server that I can setup locally and an easy way for me to test if it worked or not (without having to install tons of tools), I could take a look and see whats stopping it from working.

**Comment by KhushrajRathod** [comment]
Yes, it uses standard tcp connections.
Here's a script I've written to quickly make minecraft servers

```sh
#!/bin/bash

set -e

if [ $# -ne 1 ]; then
    echo "Usage: $0 server-name"
fi

mkdir -p $1
cd $1

if [ ! -f "server.jar" ]; then
    echo "Downloading PaperMC"
    wget -O server.jar "https://papermc.io/api/v1/paper/1.16.3/latest/download"
    echo "eula=true" > eula.txt
    echo Agreed to Mojang EULA 
fi

# logs
mkdir -p ./logs
touch ./logs/temp # avoid "no such file or directory"
rm ./logs/*
touch logs/latest.log

# Start minecraft
echo "Running server..."
java -Xmx2G -Xms2G -jar server.jar nogui
echo "Exit code $?"
```

Run as 
```
./mc.sh servername
```

A `servername` directory will be created and the script should start the server. To start the server again, just rerun the script, it won't redownload stuff

**Comment by KhushrajRathod** [comment]
I think the issue is https://github.com/localtunnel/localtunnel/issues/297

**Comment by SirDankenstien** [comment]
https://github.com/SirDankenstien/Dank.ServerBuilder

**Comment by nicermak** [comment]
`server-ip=127.0.0.1`
