### ISSUE TITLE
[*] Alternatyve to localtunnel - fresh clone: sharetunnel.work

### ISSUE THREAD

**Issue by iamrekas** [localtunnel/localtunnel#370]
Cuz localtunnel often is down, just cloned and released on other name.

**Comment by derwaldgeist** [comment]
Doesn't work for me. Also, does it support https?

**Comment by derwaldgeist** [comment]
Awesome, works! Let's see if this is more reliable than the "official" server.

**Comment by yeguacelestial** [comment]
Thank you fam!

**Comment by mansoorsiddiqui** [comment]
@iamrekas are you planning on keeping this up reliably for public use? I'm having a lot of trouble with localtunnel going down a lot for my projects. How can I switch over to your server?

**Comment by yeguacelestial** [comment]
@mansoorsiddiqui it's a clone of localtunnel, so it's quite reliable. 

I used it for echoing a local Flask web server, and it's pretty smooth.

**Comment by iamrekas** [comment]
@mansoorsiddiqui i probably will leave it online for ever, maybe upgrade it even more in feature. Any with any question, issue or suggestion please post in that project github issues board

**Comment by efraimbart** [comment]
@iamrekas sharetunnel.work still references the `lt` command

**Comment by yeguacelestial** [comment]
no, you should replace it with `st`

**Comment by efraimbart** [comment]
I'm aware of what it should be, I'm commenting on what it is. See 
![image](https://user-images.githubusercontent.com/8098171/104530804-cd44c600-55da-11eb-83e4-e9a308e48375.png)

**Comment by iamrekas** [comment]
hello, @efraimbart, please every issue on that project github page. Thank you.

**Comment by CarterSullivan** [comment]
Hi, does this still work for anyone? It's not working for me at the moment...

**Comment by iamrekas** [comment]
Hi, @CarterSullivan, sometimes it's require to restart the server, so i am very sorry. i will in near feature upgrade client for this issue solve, you can just try to relaunch and it's must work as excepted. thank you.

**Comment by CarterSullivan** [comment]
Sorry, it doesn't seem to work. When will this be fixed?

**Comment by iamrekas** [comment]
@CarterSullivan i guess in next 3 months will try to fix that issue. But until what as i told before, you can just restart in few minutes then connection closed, then everything should work normally. This client has not ability to close lost connections, like network disconnect and etc.. So for special prefix i must restart server, because i use it for personal projects. Again i am sorry for that, but pls be patience

**Comment by Marvin-Brouwer** [comment]
This no longer seems to work.
@efraimbart I searched on github and I tried going to `sharetunnel.work` but that also doens't exist.
I found the npm package https://www.npmjs.com/package/sharetunnel and the github link there results in a 404.
What's the status?

**Comment by efraimbart** [comment]
@Marvin-Brouwer Wrong guy? 

Perhaps you can try cloudflare tunnels

**Comment by Marvin-Brouwer** [comment]
Yes wrong guy, sorry.
