### ISSUE TITLE
localtunnel certificate expired?

### ISSUE THREAD

**Issue by suzanne-stathatos** [localtunnel/localtunnel#372]
Getting the following error message in chrome when I navigate to it

This server could not prove that it is horrible-emu-8.serverless.social; its security certificate expired 2 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Tuesday, December 8, 2020. Does that look right? If not, you should correct your system's clock and then refresh this page.

**Comment by TheBoroer** [comment]
Looks like the expired cert was fixed by the serverless.social admin.
Just a reminder, the regular localtunnel server also works so feel free to use that as your backup in the future.

**Comment by rsoury** [comment]
+1 

Seems the domain name Cert has expired again

**Comment by TheBoroer** [comment]
Apologies, this should be fixed now.

I'll have to check why my nginx config reload script didn't do it's job after renewing the cert 😓
