### ISSUE TITLE
ping a localtunnel address?

### ISSUE THREAD

**Issue by omarcostahamido** [localtunnel/localtunnel#373]
Hi there,
Newbie here.
I'm still trying to understand how this works.
I tried pinging my auto generated address but I always get:
> ping: cannot resolve https://autogen-92.loca.lt: Unknown host

**Comment by TheBoroer** [comment]
You can't ping a URL, you can only ping a hostname (so the thing you were trying to ping but without the https:// at the front). 

Even then, it's pointless to ping a localtunnel subdomain because it pings our server, not your local server

**Comment by omarcostahamido** [comment]
Hi @TheBoroer 
Thank you for the clarification.
I guess what I am trying to understand is how much slower it is to access through localtunnel.
Excuse me from my very stupid question: all traffic is routed through loca.lt server, correct?

**Comment by TheBoroer** [comment]
> Hi @TheBoroer
> Thank you for the clarification.
> I guess what I am trying to understand is how much slower it is to access through localtunnel.
> Excuse me from my very stupid question: all traffic is routed through loca.lt server, correct?

Not a stupid question at all. Yep! everything is routed through the loca.lt server.

You can look at the HTTP request timings in the network tab of chrome developer tools. Compare the request time for a localhost url vs a loca.lt url. Keep in mind that not all that added time is my server's fault, it also includes the time the data takes to travel through your ISPs network, over the internet and back (something you don't have with localhost urls)

If you can open ports in your firewall, then setup dynamic dns, and point your domain name to it you'll have a direct connection to your computer and can ping and do all sorts of other things :)

**Comment by omarcostahamido** [comment]
Ok, thank you.
Always learning.
I was precisely trying to avoid opening ports on the firewall etc 🤣

**Comment by SrBrahma** [comment]
For a simple game server, would the ping/delay be large, even if the other player is near me (South america)?

**Comment by TheBoroer** [comment]
@SrBrahma yes the ping would still be affected, even if you two were in the same room. If you use a loca.lt subdomain the other person will be connecting via the internet to the loca.lt server (currently located in Canada) then back through the tunnel to you.

**Comment by SrBrahma** [comment]
I see. Thanks for the quick answer!
