### ISSUE TITLE
Animal name generation?

### ISSUE THREAD

**Issue by euwern** [localtunnel/localtunnel#374]
I wonder how localtunnel generates all these funny animal names like: 'serious-cat', 'cuddly-bat', 'breezy-skunk'...etc.  I couldn't seem to find a list of animal names in this repo.

**Comment by TheBoroer** [comment]
Those names get generated by the localtunnel server using this npm package:

https://www.npmjs.com/package/human-readable-ids

**Comment by euwern** [comment]
awesome thanks @TheBoroer
