### ISSUE TITLE
Axios needs to be updated to >=0.21.1 (Security issue)

### ISSUE THREAD

**Issue by LaravZ** [localtunnel/localtunnel#377]
Regarding this security report https://snyk.io/vuln/SNYK-JS-AXIOS-1038255
Issue on axios: https://github.com/axios/axios/pull/3410

Axios needs to be updated to >=0.21.1 to ensure another project can use localtunnel without security concern

"dependencies": {
  "axios": ">=0.21.1"
}

**Comment by dippas** [comment]
I'm having the same issue, can you please upgrade dependency axios?

**Comment by limonte** [comment]
The latest maintainer's activity in this repo was 16 months ago, so I believe someone needs to fork it in order to resolve this and maybe other issues.

**Comment by TheBoroer** [comment]
I'll ping the maintainer to merge the pull request

**Comment by abbyblachman** [comment]
+1

**Comment by qdraw** [comment]
When is the next npm release planned?

**Comment by d0v3riz** [comment]
I'm still waiting for the latest update

**Comment by mattwelke** [comment]
> I'm still waiting for the latest update

Yep, we all are. You can use this issue to track it.

**Comment by defunctzombie** [comment]
I've released version 2.0.1 which includes updated dependencies.

**Comment by dippas** [comment]
Tank you @defunctzombie

**Comment by englishextra** [comment]
@defunctzombie Zing
