### ISSUE TITLE
Got CORS issue when issue default host

### ISSUE THREAD

**Issue by zcmgyu** [localtunnel/localtunnel#382]
I got a CORS issue when I start a tunnel via the default host.

**Reproduce:** 

Example API: https://github.com/devslopes-learn/simple-express-server

Expose port 6069 of API: `lt --port 6069`

In console of browser, I ran below code:

```
fetch('https://moody-fish-47.loca.lt/ingredients')
  .then(response => response.json())
  .then(data => {
    console.log(data)
  })
  .catch(err => console.log(err))
})()
```

I got a CORS error message:

> Access to fetch at 'https://moody-fish-47.loca.lt/ingredients' from origin 'http://localhost:6069' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

When I changed to this upstream proxy server, I've worked as expected.

> https://serverless.social

**Comment by swieke** [comment]
Faced this similar issue just now, my steps to solve this issue is as below:

1. Visit your local tunnel domain via browser. e.g: https://moody-fish-47.loca.lt
2. Click on continue button or any button prompt from the browser

**Comment by zcmgyu** [comment]
@swieke Thanks
