### ISSUE TITLE
Subdomain performing 50/50 split

### ISSUE THREAD

**Issue by jvadair** [localtunnel/localtunnel#389]
I run a small web server exposed at https://jvadair.loca.lt

Recently another person has also, somehow, claimed this subdomain simultaneously.

Checking the screen in which I run a keep alive program:

`while true; do lt --subdomain jvadair -p 80; done`

The local tunnel is still running, saying I am connected to jvadair.loca.lt

When visiting this site, it will either send you to a Jenkins login page, or my server, which is a simple dark-themed website. If you reload from the Jenkins page, you will either get the same address, or you will receive a 404 from my site (there is no /login page on my site)

If I attempt to run a localtunnel on the same subdomain again, whether the port is changed or not, I receive a randomized subdomain instead (the subdomain is already taken, so I receive a separate one).

# My **theory**:
The code that replaces the custom subdomain with a randomized one if that subdomain is already taken is part of the client. This could mean that someone could modify the code to bypass this.

**Comment by TheBoroer** [comment]
Hmm,
This is really weird and definitely shouldn't be happening. :/ 
I'll have a look this weekend sometime and try to test your theory of bypassing the random subdomain logic
