### ISSUE TITLE
`lt` command hangs

### ISSUE THREAD

**Issue by nero120** [localtunnel/localtunnel#397]
Hi guys, localtunnel (v2.0.1) has been working fine for me for ages but this morning i've tried to open a tunnel and it just hangs:

```
lt -p 8080
```

Tried running on a different machine but same issue, also other colleagues have the same problem. There's no log or error output alluding to the problem - could it be a server issue?

Edit: fix [here](https://github.com/localtunnel/localtunnel/issues/397#issuecomment-789653500)

**Comment by KShivendu** [comment]
Same here.

**Comment by nero120** [comment]
Just checked [`http://localtunnel.me/api/status`](http://localtunnel.me/api/status) and it's online, responds with:

```
{"tunnels":1450,"mem":{"rss":686673920,"heapTotal":219951104,"heapUsed":171431936,"external":2850344}}
```

**Comment by alexandertrev** [comment]
have the same thing

**Comment by S4G4R** [comment]
same here!

**Comment by nero120** [comment]
@defunctzombie any idea what's happening?

**Comment by nero120** [comment]
@TheBoroer any idea if there's an issue with the server?

**Comment by nero120** [comment]
I've got a fix, it works if you explicitly tell the CLI to use `loca.lt`:

```
> lt --host http://loca.lt --port 8080
your url is: https://fluffy-hound-8.loca.lt
```

What changed server-side that stopped `loca.lt` being used as the default tunnel server? Definitly wasn't an npm update.

**Comment by marcinciarka** [comment]
Looks like the certificate is expired on the https domain.

**Comment by maganius** [comment]
I try using this `npx localtunnel --local-host domain.local --port 80 --subdomain customdomain` and not work

**Comment by marcinciarka** [comment]
> I try using this `npx localtunnel --local-host domain.local --port 80 --subdomain customdomain` and not work, yesterday it worked

Try `--host http://loca.lt` option

**Comment by maganius** [comment]
> > I try using this `npx localtunnel --local-host domain.local --port 80 --subdomain customdomain` and not work, yesterday it worked
> 
> Try `--host http://loca.lt` option

thanks it worked

**Comment by TheBoroer** [comment]
Hey everyone! It should be back up and running. There was a problem with certbot not auto-renewing the "localtunnel.me" ssl cert but it worked when I triggered it manually.  'loca.lt' certs worked just fine so you could always just continue using the `--host https://loca.lt` option like others said.   `loca.lt` is just an alias for `localtunnel.me` and they're both hosted by the same server :)

**Comment by maganius** [comment]
it down again?, I can't connect to tunnel

**Comment by TheBoroer** [comment]
@maganius can you please try again? 

*sigh* someone from brazil is hammering the server with thousands of new subdomain requests at the moment. I guess I'll be implementing a rate limiter + request delay middleware for when connection endpoint at some point this week.

**Comment by maganius** [comment]
> @maganius can you please try again?
> 
> _sigh_ someone from brazil is hammering the server with thousands of new subdomain requests at the moment. I guess I'll be implementing a rate limiter + request delay middleware for when connection endpoint at some point this week.

Now working, what kid rat.... they have much free time...

**Comment by nero120** [comment]
Working for me again now without needing the `host` option. Many thanks @TheBoroer for addressing the issue and in general for hosting the service!

**Comment by rajaramcomputers** [comment]
> I've got a fix, it works if you explicitly tell the CLI to use `loca.lt`:
> 
> ```
> > lt --host http://loca.lt --port 8080
> your url is: https://fluffy-hound-8.loca.lt
> ```
> 
> What changed server-side that stopped `loca.lt` being used as the default tunnel server? Definitly wasn't an npm update.



> > > I try using this `npx localtunnel --local-host domain.local --port 80 --subdomain customdomain` and not work, yesterday it worked
> > 
> > 
> > Try `--host http://loca.lt` option
> 
> thanks it worked

Thanks, struggling for 24 hrs, now working....
