### ISSUE TITLE
Geo location change

### ISSUE THREAD

**Issue by TheRealTechWiz** [localtunnel/localtunnel#400]
Is there any option to manually change the connection server location to the nearest physical localtunnel server? I tried it with ngrok and it increases speed drastically. would love to see any ssuch option in  localtunnel as well.

**Comment by TheBoroer** [comment]
Hey @TheRealTechWiz
Unfortunately no. Localtunnel is free and hosted on a couple servers in a single location at the moment; Canada. That would be a cool feature for a self-hosted server/client installation though. Ngrok is a paid service so they can afford having a worldwide network.

**Comment by TheRealTechWiz** [comment]
This is feature is being given in ngrok free version too. But I do understand that giving paid version allows them to afford more servers. I do hope localtunnel gets more servers in future and one near my region too. Anyways thanks for replying.
