### ISSUE TITLE
Localtunnel down?

### ISSUE THREAD

**Issue by yoelcabo** [localtunnel/localtunnel#402]
Hey! it appears the service is down. Running `lt --port 8000` the program gets stuck without outputting anything.

I tried pointing to `loca.lt` as suggested [here](https://github.com/localtunnel/localtunnel/issues/397#issuecomment-789653500) with no luck.

**Comment by spyros-uk** [comment]
Yes, it seems to be down. In my case it started with a 502 response from the server and then it just died...

**Comment by adovbos** [comment]
that is just a right moment to go down, when I need to manually test my code and push it before deadline) I'm lucky)))

**Comment by TheBoroer** [comment]
Thanks for making an issue. I'm taking a look at this now

**Comment by Mr-Slimon** [comment]
Yep can confirm it 
also tried to use another host and the same problem exist

**Comment by Trezub** [comment]
Looks like its working fine now

**Comment by mosaic-vance-tran** [comment]
Working again for me, thank you!

**Comment by spyros-uk** [comment]
Yep, I can confirm that it works as expected for me too. Thanks a lot @TheBoroer !

**Comment by TheBoroer** [comment]
Should be back up now! The server ran out of disk space (due to an unrelated elasticsearch instance growing uncontrollably lol)...sorry everyone! It won't happen again :)

**Comment by yoelcabo** [comment]
Thanks so much for your support @TheBoroer :heart:
