### ISSUE TITLE
Subdomain didn't work properly

### ISSUE THREAD

**Issue by EchConBungBu** [localtunnel/localtunnel#403]
Hi everyone,

I ran into an issue with setup subdomain. I run CMD  **lt -p 8069 -s abcsport**, and it worked well a few times. Later, this subdomain couldn't use anymore. Although I used the subdomain abcsport, I received a random subdomain. I thought that the server kept my subdomain as it thought it was taken... Everyone here could help me with this? How can I use subdomain again?

Thanks,

**Comment by agaertner** [comment]
Got the same problem now. Got a colleague beside me. Changed the subdomain. And after Ctrl+C and trying to restart it was not available anymore. Seems like it doesn't recognize a closed session this way. 
Similarly, it worked for a week just fine.

**Comment by DblK** [comment]
If you restart the localtunnel server it will work again. It seems to be an issue on close.

**Comment by darkhaan** [comment]
I have discovered how to delete subdomain from server. You have to open your tunnel url and get 504 timeout error, after several minutes, your subdomain will be ready for usage.

**Comment by LeandroSQ** [comment]
Using a subdomain, for me, only worked for some hours, regardless of the host 
If you need a fixed url, the best option is to host a tunnel server somewhere (Like AWS free tier, or Heroku) 

In fact, I made a [project](https://github.com/LeandroSQ/cgnat-tunnel) for fun to do exactly that. I'm currently exposing my Raspberry Pi under heroku free dynos with it. Working stable for 2 weeks now.

**Comment by ankitahuja1** [comment]
@EchConBungBu Im using node v16.5 on Ubuntu 20.04 and it works perfectly for me each and every time.

**Comment by EchConBungBu** [comment]
Thanks guys for supporting me! My issue is solved thanks to your all answers. This ticket could be closed!
