### ISSUE TITLE
Disable "friendly reminder" for subsequent browser visits using a CURL request?

### ISSUE THREAD

**Issue by FezVrasta** [localtunnel/localtunnel#407]
Hi, is there any way to disable the friendly reminder from command line so that when I visit the page from a web browser it doesn't show up?

Basically what I'd like to do is to disable the friendly reminder page for my current IP address without going through the web page. I'm not asking to disable it for all the visitors, just for the current IP address.

I'd expect it to be something like:

```
curl -H "Disable-Tunnel-Reminder: true" https://project.loca.lt
```

Alternatively, if I send any request with the existing `Bypass-Tunnel-Reminder` header, it would be very useful if that would also disable the web page on subsequent browser visits.

Thanks for the help.

**Comment by TheBoroer** [comment]
Hi! Yes that's already implemented. Please go to any tunnel reminder page in a browser and scroll down to the section on how to bypass it. There is a header called Bypass-Tunnel-Reminder that you can use :)

**Comment by FezVrasta** [comment]
Thanks for the reply but that doesn't seem to cover my use case, if I make a `curl -H "Bypass-Tunnell-Reminder: true" https://project.loca.lt` call, and then I visit the same page from the browser, I'm still welcomed by the friendly reminder page.

**Comment by homer2017** [comment]
> Hi! Yes that's already implemented. Please go to any tunnel reminder page in a browser and scroll down to the section on how to bypass it. There is a header called Bypass-Tunnel-Reminder that you can use :)

can you tell me detail? i try to do that, but its not working

**Comment by TheBoroer** [comment]
@FezVrasta sorry to circle back on this so late but now that I'm re-reading your latest reply + the new question title, it's not possible to get around the tunnel reminder page on the browser by doing a curl command first.

The best alternative is to self-host an instance of the localtunnel server. 
You can thank automated phishing portal scripts that use local proxy tunnel services like this one for that reminder page :(

**Comment by lowzyyy** [comment]
May i ask what is the point of this package if i cannot go around this reminder page? I mean i am using localtunnel for my API which is hosted on my PC because of the high host cost and website cannot get the data even with header set up making it completely useless.

**Comment by TheBoroer** [comment]
> May i ask what is the point of this package if i cannot go around this reminder page? I mean i am using localtunnel for my API which is hosted on my PC because of the high host cost and website cannot get the data even with header set up making it completely useless.

Hey lowzyy, if you have the header set properly in the request then you should be able to bypass it just fine. Can you give me more details on how are you accessing your localtunnel hosted api (GET fetch request, etc)?

**Comment by lowzyyy** [comment]
I have Next.js website that use their API server-side routes: https://nextjs.org/docs/pages/building-your-application/routing/api-routes

After some time localtunnel became unresponsive, i mean i got error 404 like it does not even exist. Maybe it crashed

In every api route i have for example:
```
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse<Addresses | undefined>
) {
try {
    ...

    const response = await fetch(`${API}/addresses?${q}`, {
      headers: { "Bypass-Tunnel-Reminder": "true" },
    });
    if (!response.status) throw Error(`ERROR ADDRESSES: ${response.status}`);

    const result = await response.json();
    res.status(200).json(result);
  } catch (error: any) {
    res.status(400).json(undefined);
  }
}
```

It seems that it just closes after some time without any message although i said to print that it was closed on close event. When i try to access it manually through the browser, i am asked about ip and when i type the ip, i am waiting around 6-7 seconds until it just returns 404.
This is not happening on my other backend api.....

**Comment by benevalter** [comment]
any solution for this question??

**Comment by TheBoroer** [comment]
> any solution for this question??

Hi, just include the header in your curl/fetch requests (just like it says on the tunnel reminder page) or accept the tunnel reminder on another device on the same network. That way you won't see the reminder again for 7 days on that network.
