### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by Dan1ell** [localtunnel/localtunnel#411]
I'm getting 
**503 Service Temporarily Unavailable.**

On MacOs Big Sur 11.2.1
Used `npm install -g localtunnel`
Running `lt --port 80`
The website is running on docker.

How to fix this?

![503](https://user-images.githubusercontent.com/61538/120733522-bf2a1000-c4bd-11eb-9f33-87d594a6e271.jpg)

**Comment by TheBoroer** [comment]
It should be working now. It was just a temporary public localtunnel server hiccup.
