### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by arnpatel** [localtunnel/localtunnel#420]
Localtunnel website seems to be down and also the `lt` command is not working to start reverse proxy host.

**Comment by nucleiis** [comment]
Same here, localtunnel.me itself 193.34.76.44 seems down!

**Comment by LucasHarvey** [comment]
same issue here

**Comment by stepanic** [comment]
same issue for me :/

**Comment by brunoeduardodev** [comment]
same issue here //

**Comment by asalamfaeq** [comment]
I am having the same issue. Lt command is not working.

**Comment by luciilucii** [comment]
seems to work again

**Comment by TheBoroer** [comment]
@everyone
Everything should be back up and running :)
The datacenter the server is in had some upstream networking issues for the last 2 hours

**Comment by arnpatel** [comment]
Working fine now, thanks @TheBoroer
