### ISSUE TITLE
Localtunnel not working even tough server and client start successfully

### ISSUE THREAD

**Issue by escomputers** [localtunnel/localtunnel#422]
Both server and client start successfully

Server
```
/localtunnel-server# node -r esm ./bin/server --domain cloud.mysite.com
  localtunnel server listening on port: 80 +0ms
```
  
  Client
`  lt --host http://cloud.mysite.com -p 8083 --subdomain web01`

Server response
`  localtunnel:server making new client with id web01 +0ms`

**but when I visit web01.cloud.mysite.com page is unreachable** (no 404 error)

if I visit cloud.mysite.com I get redirected to https://localtunnel.github.io/www/
even if I use human random ids and top level domains such as mysite.com the result is the same
I even tried another domain name!

```
node --version (both server and client)
14.17.2
```
Thanks

**Comment by mridah** [comment]
@escomputers in facing the same issue.  Were you able to solve it?
