### ISSUE TITLE
502 (Bad Gateway)

### ISSUE THREAD

**Issue by GCPins** [localtunnel/localtunnel#434]
502 at https://localtunnel.me 

tunnel never starts from command prompt and any existing tunnels return 502 error also

**Comment by Ancient23** [comment]
Getting this too all of a sudden. May be some dependency update

**Comment by JuanCarlosRC** [comment]
I wanted to try localtunnel now but sadly it is down LOL

**Comment by xenbartolokath** [comment]
I'm getting the same issue

**Comment by saward** [comment]
One of my team found a possible alternative host, though I haven't checked the trustworthiness of it:

`lt -h "http://serverless.social" -p 8080`

**Comment by TheBoroer** [comment]
Sorry guys, docker container crashes randomly for some reason. I think it's we sockets related but it should be up now

**Comment by giuliac1989** [comment]
Down now! :(

**Comment by nucleiis** [comment]
> Sorry guys, docker container crashes randomly for some reason. I think it's we sockets related but it should be up now

It's down again!

**Comment by DavertMik** [comment]
So sad . Still down 😭

Anyway, thanks for running localtunnel it saved me hours of configuring the environment! 🤓

**Comment by TheBoroer** [comment]
I just pushed a fix to my custom localtunnel guard service. I think that'll fix the problems once and for all :)

Still need to implement some more blacklisting and/or rate-limiting stuff though, seems like a botnet from mexico is requesting thousands of subdomains per second...smh 👎     I hope that wont break things for others

**Comment by wiruzman** [comment]
Seems to work now.
