### ISSUE TITLE
Command Help

### ISSUE THREAD

**Issue by sintyx-host** [localtunnel/localtunnel#438]
Can you send me the command to make my website running with port 3000 , subdomain gr-developer, and no friendly reminder page? Pls 
`For Windows`

**Comment by TheBoroer** [comment]
@sintyx-host unfortunately there's no way to get around the friendly reminder page using the public localtunnel server instance (for security and abuse reasons). Feel free to host a localtunnel server on your own domain to avoid having a reminder page :)
