### ISSUE TITLE
Restrict to path under local-host and port?

### ISSUE THREAD

**Issue by frolic** [localtunnel/localtunnel#44]
Often times I'll throw HTML files into a local Nginx server running on 8080 with autoindex turned on to let me browse the file tree. It would be great if I could fire up a localtunnel while restricting requests to a certain path under the Nginx server, e.g.

`lt --port 8080 --path /someproject`

Then all requests from `https://subdomain.localtunnel.me/*` are actually making requests to my `http://localhost:8080/someproject/*`.

**Comment by jeff-h** [comment]
Hmm, that's a real shame. I'd also have loved this. I use MAMP a lot locally and don't bother with setting up vhosts, so all my sites have a subdirectory in my ~/Sites. Would be great to be able to publicly expose just a subdirectory.

**Comment by cchan** [comment]
I agree; this would be very useful as well.

**Comment by michalsvorc** [comment]
I second that. I'm localhosting my dev folder full of other projects, when I want to share only a subfolder, im exposing all my sourcecode
