### ISSUE TITLE
Error: tunnel server offline: certificate has expired

### ISSUE THREAD

**Issue by zlshames** [localtunnel/localtunnel#445]
Hey everyone,

I was having issues connecting using LocalTunnel, so I started debugging a little bit and found that the server's certificate is expired. I am also curious to see if anyone else was having similar issues?

Raw Error: `tunnel server offline: certificate has expired, retry 1s`

It basically just throws this error on repeat... for ever. It never times-out and throws a Promise rejection or anything. Is this something we can expect to be fixed, or should we try other solutions?

Thanks!

**Comment by DaveMitten** [comment]
Yep. I'm getting this now after it running successfully initially.
