### ISSUE TITLE
How to run in the background and not block terminal?

### ISSUE THREAD

**Issue by sayjeyhi** [localtunnel/localtunnel#448]
How to run in the background and not block the terminal?
Is there any option like `-d ` for docker? to run service in the background

**Comment by ffauzan** [comment]
You can use nohup if you are on linux for simplicity
The other solution that is a bit overkill is to run it on docker, you can check [my repo](https://github.com/ffauzan/localtunnel-multiple)

**Comment by sayjeyhi** [comment]
I used [https://www.npmjs.com/package/concurrently](concurrently) with the npm package of `localtunnel` and both solved my problems
