### ISSUE TITLE
localtunnel is down?

### ISSUE THREAD

**Issue by xenbartolokath** [localtunnel/localtunnel#451]
Hi @TheBoroer ,

Seems like localtunnel is not accessible. I am getting this error when I try to access the site:

![Screen Shot 2021-11-22 at 1 24 36 PM](https://user-images.githubusercontent.com/80238429/142805651-9f033f40-bff2-4aec-b482-531cf3aaf1a9.png)

Would appreciate your help in checking this. Thanks! 🙇

**Comment by ajitesh-sivakumar** [comment]
Yes, I guess localtunnel is down. Not able to access it.

**Comment by TheBoroer** [comment]
Hey! The server will be back up shortly. 
I was performing some maintenance to the underlying physical host.

**Comment by shivajipotnuru** [comment]
Is the Local tunnel back online @TheBoroer ??

**Comment by saeedghadiri** [comment]
Hey! thank you for your great project and efforts. is there any estimation about the time that the project is back online?

**Comment by suryarocks11** [comment]
Getting 404 error even after running tunnel.

**Comment by vagran** [comment]
Yes, there is no usual output "your url is:" from the client. No output at all.

**Comment by vagran** [comment]
Seems not yet up. With enabled debug output:
```localtunnel:client tunnel server offline: Request failed with status code 502, retry 1s +2s```

**Comment by hardikpoojara** [comment]
I think it started working

**Comment by suryarocks11** [comment]
> I think it started working
I don't think so.

**Comment by hardikpoojara** [comment]
> > I think it started working
> > I don't think so.

Can you please try to restart that?

**Comment by vagran** [comment]
```localtunnel:client tunnel server offline: Hostname/IP does not match certificate's altnames: Host: localtunnel.me. is not in the cert's altnames: DNS:*.loca.lt, DNS:loca.lt, retry 1s +2s```

**Comment by nucleiis** [comment]
Still down. I am also getting the cert warning like @vagran

**Comment by ajitesh-sivakumar** [comment]
It is Fixed. 💯

**Comment by TheBoroer** [comment]
Hey everyone! it should be up and working now :)  lmk if theres any issues

**Comment by xenbartolokath** [comment]
Seems like it's fixed! Thank you! 🎉

**Comment by andremourasantos** [comment]
I still can't access the website....

**Comment by TheBoroer** [comment]
@andremourasantos 
Could you give me more details on what your having problems with (feel free to open another issue)? e.g. are you having trouble accessing the localtunnel service homepage/domain, or are you seeing errors, etc?

**Comment by andremourasantos** [comment]
> @andremourasantos Could you give me more details on what your having problems with (feel free to open another issue)? e.g. are you having trouble accessing the localtunnel service homepage/domain, or are you seeing errors, etc?

I can't open the localtunnel.me website: my browser says "This site can’t be reached".
![Screenshot 2021-11-29 13 43 39](https://user-images.githubusercontent.com/92397834/143917230-3f548382-760a-483c-99cc-8bd5fd9c768f.png)

I've tried the VS Code extension too, but it simply doesn't do anything when I do "start", even the port number and domain setup steps appear, but after that, nothing happens... No errors or something to share tho

**Comment by TheBoroer** [comment]
It might be a dns or firewall/web-filtering issue on your end (or with your ISP). 
What IP do you see when you ping `localtunnel.me`?

This shows that http and https works worldwide:
http://port.ping.pe/localtunnel.me:443
http://port.ping.pe/localtunnel.me:80


RE: vscode extension
I can't really troubleshoot this one since it's a community made product. Please try the localtunnel cli command. If it works, then you extension should work too.

**Comment by andremourasantos** [comment]
The ip address that I got is: 193.34.76.44.

I tried to run it directly from the terminal too, but nothing happens:
![Screenshot 2021-11-29 14 20 14](https://user-images.githubusercontent.com/92397834/143921856-fb2c2d24-88e0-4de9-93cf-05f06fea75ee.png)

**Comment by TheBoroer** [comment]
That's the right IP. Could you try running `DEBUG=localtulpfile.jsunnel:client lt --port 8080` and check the output for any errors? Feel free to attach the logs

**Comment by andremourasantos** [comment]
Seems like it couldn't run the command and it take way too long to get on it:
![image](https://user-images.githubusercontent.com/92397834/143923254-330f582d-f876-490e-a280-e332f50e74ae.png)

The only log file that I've here is this, it's from morning and I'm not sure what's it:
[2021-11-29T15_41_33_512Z-debug.log](https://github.com/localtunnel/localtunnel/files/7620392/2021-11-29T15_41_33_512Z-debug.log)

I'm a newbie and I'm trying to figure out how to do the things to help 😅

**Comment by TheBoroer** [comment]
Thanks for that. The server is definitely online, with over 2000 active tunnels at the moment and seems to be working fine.
This looks like a firewall/content filtering issue on your end that's blocking access to the LT server. 
Maybe try disabling any firewall/content filtering software or try another internet connection?

**Comment by andremourasantos** [comment]
I tried to access it from my mobile data connection (on the computer), but the same error happens, even when I tried to access from my browser on mobile...
