### ISSUE TITLE
404 error on VPN connections

### ISSUE THREAD

**Issue by memlirestelica** [localtunnel/localtunnel#464]
Localtunnel always returns 404 error when the server-side computer is connected to a private VPN. The connection is done through CatoVPN

**Comment by ghost** [comment]
yeah unfortunately i have this problem too

**Comment by 15ah35** [comment]
how to resolve this? any other tool that can be used?

**Comment by TheBoroer** [comment]
Does your localtunnel client show any errors? or does it seem to connect just fine and displays the tunnel url?

Could one of you guys lmk your tunnel subdomain and ill check to see what your IP looks like on my end (and you can confirm if that's the public IP of your vpn).


Alternatively, try ngrok and see if it works for you through the tunnel.

Edit: i dont think VPNs that switch public IP addresses is supported atm.
