### ISSUE TITLE
Localtunnel is not working with ReactJS project

### ISSUE THREAD

**Issue by dzhoz0** [localtunnel/localtunnel#484]
I cannot use localtunnel with ReactJS, I have tried others ports but it won't work. I tested this against Express.js and it still works fine. What happened? Am I missing something? There are no logs during the execute.

**Comment by TheBoroer** [comment]
Could you give more details on how you're running your react project (how your project is setup, what flags you run the localtunnel client with etc)?

It works fine for me using a simple create react app project

**Comment by dzhoz0** [comment]
> Could you give more details on how you're running your react project (how your project is setup, what flags you run the localtunnel client with etc)?
> 
I used `npx create-react-app` to create app, I ran `lt --port 3000`. I'm using Arch Linux. I also tried my React project using ngrok and it works fine. I also get 504 gateway time-out after waiting it to load.

**Comment by dzhoz0** [comment]
I just tried to setup this with my VPS, looks like it is my computer configuration error.
