### ISSUE TITLE
get me a way

### ISSUE THREAD

**Issue by Nuerfr** [localtunnel/localtunnel#492]
how to bypass tunnel website ahead ? i need it so bad so ye

**Comment by TheBoroer** [comment]
Unfortunately you can only bypass it by passing a custom user agent in the request or include the bypass http header in the request. 

If you really need it to be completely gone, your only option is to host your own server or use something like ngrok

**Comment by Nuerfr** [comment]
how do i build it myself

**Comment by TheBoroer** [comment]
> how do i build it myself

Check out this repo: https://github.com/localtunnel/server
