### ISSUE TITLE
Allow non-HTTP traffic (eg. Minecraft Server, Microsoft Office Sharepoint, Active Directory)

### ISSUE THREAD

**Issue by teknixstuff** [localtunnel/localtunnel#497]
Is it possible to add non-HTTP traffic support to localtunnel?

**Comment by teknixstuff** [comment]
Bump?

**Comment by TheBoroer** [comment]
There are no plans to add TCP tunneling support to localtunnel at this time. Pull requests are welcome though ☺️

For now your best alternative is to use something like ngrok
