### ISSUE TITLE
a weird glitch

### ISSUE THREAD

**Issue by Sonic4Tails** [localtunnel/localtunnel#504]
ok so someone took my subdomain which was still used by localtunnel which was still running and now its taken so who was it that took the most weird name for a sogebot admin page

**Comment by dheerajdlalwani** [comment]
Hey @Sonic4Tails . This does seem like a weird issue. Are you sure the subdomain was still in use? Also, have you tried uninstalling localtunnel and installing it again? Because this was one of the earlier issues that if say one was using a localtunnel and it crashed for whatever reason, one was not able to reuse the same subdomain for a couple of hours. This issue is now fixed so, please uninstall and install the latest version again.

**Comment by tamouse** [comment]
I'm wondering how "fixed" it is, since it didn't crash, I just terminated the process with ^C and now my chosen subdomain seems to be unavailable.

```
lt --version
2.0.2
node -v
v16.15.0
```

I just installed it today.

**Comment by dheerajdlalwani** [comment]
This seems weird. It does work for me. What operating system are you on? Also, are you sure you did ctrl + c and not ctrl + z?

**Comment by tamouse** [comment]
> This seems weird. It does work for me. What operating system are you on? Also, are you sure you did ctrl + c and not ctrl + z?

MacOS 12 something

**Comment by TheBoroer** [comment]
I think this _might_ be fixed now. if your subdomain is still unavailable you might have to wait up to 30s for the socket to timeout and release the domain.

closing this for now but lmk if it's still happening (even after waiting 30s)

**Comment by onepointfive-REAL** [comment]
still broken

**Comment by TheBoroer** [comment]
> still broken

You're experiencing the issue at the moment where your subdomain gets taken by someone else or is unusable for a bit of time?? Have you tried to wait a bit and request your subdomain again a bit later? 

Would love to get more info from you to help me debug and figure out what's going on

**Comment by onepointfive-REAL** [comment]
> > still broken
> 
> You're experiencing the issue at the moment where your subdomain gets taken by someone else or is unusable for a bit of time?? Have you tried to wait a bit and request your subdomain again a bit later?
> 
> Would love to get more info from you to help me debug and figure out what's going on

It took over 30 seconds like a couple of minutes is how long it took
