### ISSUE TITLE
Cannot proceed request in browser

### ISSUE THREAD

**Issue by sogener** [localtunnel/localtunnel#506]
Why am i getting error when i'm trying to **press** the continue button?
Page just reloads and nothing more.

Request with **Bypass-Tunnel-Reminder** works fine.

Everything was fine yesterday :(

![Screenshot from 2022-07-07 10-03-46](https://user-images.githubusercontent.com/50992188/177696192-231e70c7-6bcb-4cea-9ac6-722e744ea77f.png)

![Screenshot from 2022-07-07 10-04-18](https://user-images.githubusercontent.com/50992188/177696255-7a34e372-ee0e-4729-91df-a992c2fa2cfa.png)

**Comment by deepaksinghsolanki1989** [comment]
I am facing the same issue since morning. I have tried the below solutions:

1. Set and send a Bypass-Tunnel-Reminder request header (its value can be anything).
2. Set and send a custom / non-standard browser User-Agent request header.
3. Set Disable-Tunnel-Reminder to true using the below command
curl -H "Disable-Tunnel-Reminder: true" https://myhost7861.loca.lt

Does anyone know any solution to fix this issue?

**Comment by riuss** [comment]
Same problem for me. So I think it's a general problem on their side. 
Apparently, you can write anything.loca.lt and it shows this friendly reminder...
The positive is that I can stop debugging my system :-)

**Comment by sogener** [comment]
is local tunnel is up? 
`lt --port 80` is not running at all at this moment :)

**Comment by swati-malhotra** [comment]
> is local tunnel is up? `lt --port 80` is not running at all at this moment :)

Its not, could this mean that they are working on this?! 😁

**Comment by icarreiralamas** [comment]
> @icarreiralamas could you elaborate on that? Do you mean it was solved for you?

Sorry for not explaining myself. I have been all morning with the same problem with the friendly reminder, I have not been able to send any request successfully. Last week there was a problem, and it seems that now we are in the same situation. No matter how much I run the command lt --port 8080 I can't get the url at any time.

**Comment by alejandro-mouras** [comment]
It's up and running

**Comment by TheBoroer** [comment]
Hey all, we had some issues with the localtunnel public server over the last few weeks.

I think everything's back up and running how it should, so i'll be closing this issue. Feel free to @ me if the issue still is happening and I'll re-open it again.

**Comment by skychik** [comment]
@TheBoroer still happening
