### ISSUE TITLE
Server seems to be down

### ISSUE THREAD

**Issue by pjmartorell** [localtunnel/localtunnel#509]
Running `lt` command is not responding nor giving any output

**Comment by pandectesio** [comment]
http://localtunnel.me is down as well

**Comment by cozmoc** [comment]
This one works like a charm! 🚀

https://github.com/localtunnel/localtunnel/issues/503#issuecomment-1171307621

**Comment by cozmoc** [comment]
This one is a good replacement! 

`npx st -p <your port> -s <your subdomain>`

Credits to https://github.com/localtunnel/localtunnel/issues/503#issuecomment-1171307621

**Comment by quiquelhappy** [comment]
> This one is a good replacement!
> 
> `npx st -p <your port> -s <your subdomain>`
> 
> Credits to [#503 (comment)](https://github.com/localtunnel/localtunnel/issues/503#issuecomment-1171307621)

why not just host your own instance of https://github.com/localtunnel/server at that point? I'been using https://localhost.run/ and it is working in the very same way localtunnel does, other than the custom subdomains. Hopefully localtunnel is back up soon.

**Comment by suryarocks11** [comment]
I guess the server is still down.

**Comment by quiquelhappy** [comment]
yep... :(

**Comment by wladiston** [comment]
I gave up waiting and set up my own server on AWS. Took me couple hours but it works

**Comment by quiquelhappy** [comment]
> I gave up waiting and set up my own server on AWS. Took me couple hours but it works

what did you use? https://github.com/localtunnel/server or just deployed your entire thing there?

**Comment by sshishov** [comment]
How to make 5-10 different urls pointing to different localhosts. We were using it for callbacks on development machines. If we have 10+ developers, what we should do to substitute the `localtunnel` currently? We were using custom subdomain for each developer

**Comment by anirudhmalik** [comment]
@sshishov you can forward your local machine to your public remote server by
- `ssh -R 8080:192.168.2.2:3000 user@<remote_server_ip>` for developer running `192.168.2.2:3000` machine
- `ssh -R 8081:192.168.2.3:3000 user@<remote_server_ip>` for developer running `192.168.2.3:3000` machine
-  `ssh -R 8082:192.168.2.4:3000 user@<remote_server_ip>` for developer running `192.168.2.4:3000` machine
- ....
- .....
- so on.. run these commands from one machine
- now use `http://<remote_server_ip>:8080` url for developer 1 i.e `192.168.2.2:3000` 
- now use `http://<remote_server_ip>:8081` url for developer 2 i.e `192.168.2.3:3000` 
- now use `http://<remote_server_ip>:8082` url for developer 3 i.e `192.168.2.4:3000` 

This is `ssh reverse port forwarding` further you can point free subdomain to these remote ip with under different port

**Comment by blasco** [comment]
Is localtunnel still down?

**Comment by Bellisario** [comment]
For me yes...

**Comment by Clemzd** [comment]
Yes i confirm

**Comment by chan-dev** [comment]
> @quiquelhappy you could just use `ssh reverse port forwarding`
> 
> * setup your ubuntu server
> * in /etc/ssh/sshd_config edit `GatewayPorts no` to `GatewayPorts yes`
> * then `sudo service sshd restart`
> * now use terminal to ssh reverse port forward by command `ssh -R 80:localhost:3000 user@<remote_server_ip>`
> * now your `localhost:3000` can be accessed from `http://<remote_server_ip>:80` i.e public now

@anirudhmalik, thanks a lot for this useful information. May i ask how do i approach it if i want the  public server to be served in `https` and it must use `http2` protocol? How do i put the SSL certificate in this case?

**Comment by anirudhmalik** [comment]
@chan-dev 
### Installing Nginx

```
apt install nginx
```
#### Delete the default server configuration

```
 rm /etc/nginx/sites-available/default
```

```
 rm /etc/nginx/sites-enabled/default
```

#### First configuration
```
 nano /etc/nginx/sites-available/myserverconfig
```
- Add the following server config
```
 server {
  listen 80;
  server_name chan.mylocaltunnel.com;
  location / {
    proxy_pass http://<remote_server>:80;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    }
 }

server {
  listen 80;
  server_name chan2.mylocaltunnel.com;
  location / {
    proxy_pass http://<remote_server>:81;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    }
 }
server {
  listen 80;
  server_name chan3.mylocaltunnel.com;
  location / {
    proxy_pass http://<remote_server>:82;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    }
 }
```
- `server_name chan.mylocaltunnel.com;`
- ` proxy_pass http://<remote_server_ip>:80;` // 80, 81, 82 is in this case is -R 80,81,82.... `ssh -R 80:localhost:3000 user@<remote_server_ip>`
- 
```
ln -s /etc/nginx/sites-available/myserverconfig /etc/nginx/sites-enabled/myserverconfig

```
##### Start Nginx
```
systemctl start nginx
```

## SSL Certification
```
apt install certbot python3-certbot-nginx
```

Make sure that Nginx Full rule is available
```
ufw status
```

```
certbot --nginx -d example.com -d www.example.com
```

Let’s Encrypt’s certificates are only valid for ninety days. To set a timer to validate automatically:
```
systemctl status certbot.timer
```

**Comment by chan-dev** [comment]
> @chan-dev
> 
> ### Installing Nginx
> ```
> apt install nginx
> ```
> 
> #### Delete the default server configuration
> ```
>  rm /etc/nginx/sites-available/default
> ```
> 
> ```
>  rm /etc/nginx/sites-enabled/default
> ```
> 
> #### First configuration
> ```
>  nano /etc/nginx/sites-available/myserverconfig
> ```
> 
> * Add the following server config
> 
> ```
>  server {
>   listen 80;
>   server_name chan.mylocaltunnel.com;
>   location / {
>     proxy_pass http://<remote_server>:80;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection 'upgrade';
>     proxy_set_header Host $host;
>     proxy_cache_bypass $http_upgrade;
>     }
>  }
> 
> server {
>   listen 80;
>   server_name chan2.mylocaltunnel.com;
>   location / {
>     proxy_pass http://<remote_server>:81;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection 'upgrade';
>     proxy_set_header Host $host;
>     proxy_cache_bypass $http_upgrade;
>     }
>  }
> server {
>   listen 80;
>   server_name chan3.mylocaltunnel.com;
>   location / {
>     proxy_pass http://<remote_server>:82;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection 'upgrade';
>     proxy_set_header Host $host;
>     proxy_cache_bypass $http_upgrade;
>     }
>  }
> ```
> 
> * `server_name chan.mylocaltunnel.com;`
> * ` proxy_pass http://<remote_server_ip>:80;` // 80, 81, 82 is in this case is -R 80,81,82.... `ssh -R 80:localhost:3000 user@<remote_server_ip>`
> 
> ```
> ln -s /etc/nginx/sites-available/myserverconfig /etc/nginx/sites-enabled/myserverconfig
> ```
> 
> ##### Start Nginx
> ```
> systemctl start nginx
> ```
> 
> ## SSL Certification
> ```
> apt install certbot python3-certbot-nginx
> ```
> 
> Make sure that Nginx Full rule is available
> 
> ```
> ufw status
> ```
> 
> ```
> certbot --nginx -d example.com -d www.example.com
> ```
> 
> Let’s Encrypt’s certificates are only valid for ninety days. To set a timer to validate automatically:
> 
> ```
> systemctl status certbot.timer
> ```

Wow, you took some time for this one. Many thanks. It's very timely that I'm also learning about nginx and setting up https. Will try this one, and see how it goes. Cheers.

**Comment by bolavefasfas** [comment]
> > This one is a good replacement!
> > `npx st -p <your port> -s <your subdomain>`
> > Credits to [#503 (comment)](https://github.com/localtunnel/localtunnel/issues/503#issuecomment-1171307621)
> 
> why not just host your own instance of https://github.com/localtunnel/server at that point? I'been using https://localhost.run/ and it is working in the very same way localtunnel does, other than the custom subdomains. Hopefully localtunnel is back up soon.

I tried hosting my own LT server I failed if you could make a 5 mins video how to set up it would be helpful or a wiki guide Please I need tunnelling badly as my isp blocks my all ports doube nat and cant use cloudflare tunnels work for https apps but my media server we cant use it cloudflare banns account and  so please make a video for hosting lt server on vps

**Comment by bolavefasfas** [comment]
> I gave up waiting and set up my own server on AWS. Took me couple hours but it works

can you write a wiki on how did you set up your own server i am unable to do so please help

**Comment by TheBoroer** [comment]
Hey everyone! Sorry I was out of town with limited internet. 
Not sure why the ubuntu instance fully froze but it should be working again now. 
Please lmk if something's still broken.

**Comment by conorpirie** [comment]
im not getting any response when running `lt`. is there anything i need to do to reset on my end?

**Comment by stfsy** [comment]
It's up but now ssl certificate validation fails because the certificate is only valid for localtunnel.me
