### ISSUE TITLE
Enable connecting to localtunnel proxy through a corporate proxy

### ISSUE THREAD

**Issue by brandondrew** [localtunnel/localtunnel#51]
(Sorry if this is already possible, and documented somewhere: I couldn't find it.)

I'm trying to connect to localtunnel.me from a PC that's behind a corporate proxy.  I'd like to be able to configure `lt` to go through our internal corporate proxy in order to reach the localtunnel.me server. 

As things stand, when I type `lt --port 8000`, I get 

```
tunnel server offline: connect ECONNREFUSED, retry 1s
```

over and over and over...

**Comment by BigBird0** [comment]
I have the same issue.@defunctzombie,what is PR?

**Comment by jessiewestlake** [comment]
@BigBird0 

PR is a Pull Request here on GitHub. He's letting everyone know that if someone feels like writing their own solution to this issue, he would integrate it into the official project.
