### ISSUE TITLE
Is localtunnel down now, today Jul 18, 2022?

### ISSUE THREAD

**Issue by silvanet** [localtunnel/localtunnel#510]

**Comment by Clemzd** [comment]
😔

**Comment by RohitGadhave** [comment]
Jul 21, 2022.

Still down

**Comment by jimmy-sandoval** [comment]
Jul 21, 2022.

Still down

**Comment by jonlitwack** [comment]
Still down

**Comment by TheBoroer** [comment]
Hey everyone! Sorry I was out of town with limited internet. Not sure why the ubuntu instance fully froze but it should be working again now. Please lmk if something's still broken.

**Comment by dheerajdlalwani** [comment]
> Still not working for me. Also the HTTPS certificate is pointing to incorrect domain. Could you please check, @TheBoroer

Not working for me too.

**Comment by silvanet** [comment]
Closed?
