### ISSUE TITLE
Local tunnel again not working. 23/07/2022

### ISSUE THREAD

**Issue by dheerajdlalwani** [localtunnel/localtunnel#513]
I just don't get a response when I run: `lt --port 8000`

**Comment by denisovan31415** [comment]
It worked once yesterday for me (it returned a url). Then it stopped working again.

**Comment by Cager1** [comment]
Not working for me either. Anyone have any alternative hosts?

**Comment by KyleMoran138** [comment]
Not working for me either :(

**Comment by joeyfigaro** [comment]
Hosted version seems to be unreliable as of late–you guys can always [host it yourselves](https://github.com/localtunnel/server) 🚀

**Comment by sushantawalekar** [comment]
Not working for me either

**Comment by eyedean** [comment]
Not working for me either

**Comment by NRicode** [comment]
> Hosted version seems to be unreliable as of late–you guys can always [host it yourselves](https://github.com/localtunnel/server) 🚀

Doesn't it needs port forward to work? I thought it defeats the whole purpose of localtunnel at the first place

**Comment by robkuz** [comment]
What is the issue that is plaguing localtunnel lately? Why is it down so often?

**Comment by akulamartin** [comment]
Yep. It's also down on my end.

**Comment by khanifikhsanudin** [comment]
Why still not working yet? sometimes i need localtunnel to test my API :(

**Comment by dheerajdlalwani** [comment]
It's working now. So, closing this issue.
