### ISSUE TITLE
Is  localtunnel down?

### ISSUE THREAD

**Issue by niraj-khatiwada** [localtunnel/localtunnel#519]
All the tunneled url returns NGINX error for me.
![image](https://user-images.githubusercontent.com/51436631/184836973-df550477-9ce3-4de4-bd25-e04fed18b126.png)

**Comment by CosJames** [comment]
Yes

**Comment by biscuits4cheese** [comment]
Yes it's down.

**Comment by niraj-khatiwada** [comment]
Any alternatives other than ngrok? Have any one tried beame-insta-ssl on Linux?

**Comment by CosJames** [comment]
It is ok now. Fixed

**Comment by biscuits4cheese** [comment]
Good player! Thanks!

**Comment by niraj-khatiwada** [comment]
Thank god

**Comment by niraj-khatiwada** [comment]
Thank god🎉
