### ISSUE TITLE
Allow dashes in custom subdomain

### ISSUE THREAD

**Issue by aeharding** [localtunnel/localtunnel#52]
Please -- this would make it clearer and easier when namespacing.

Is there any technical reason to restrict subdomain requests to only 4-20 alphanumerics?

**Comment by wilmoore** [comment]
A use-case we have is to grab the `$npm_package_name` and append the `$USERNAME` to create a valid subdomain for developers via `package.json` scripts. This allows one to run `npm run tunnel` to get started. Having this randomly fail is not a fun experience.
