### ISSUE TITLE
Domain option (to use my Own domain Name)

### ISSUE THREAD

**Issue by garder500** [localtunnel/localtunnel#528]
Hey, i want to use localtunnel to run multiple website (for sure i use the server on my own machine)
I want to run some website like that : sitea.com and siteb.com (On the same Localtunnel server) but i don't want to use a subdomain.site.com i really want to use a "sitea.com". Like it only tunnel my site port (same as how nginx do it), how i can accomplish this with localtunnel ?

**Comment by bolavefasfas** [comment]
https://www.youtube.com/watch?v=VCH8-XOikQc

**Comment by bolavefasfas** [comment]
> Hey, i want to use localtunnel to run multiple website (for sure i use the server on my own machine) I want to run some website like that : sitea.com and siteb.com (On the same Localtunnel server) but i don't want to use a subdomain.site.com i really want to use a "sitea.com". Like it only tunnel my site port (same as how nginx do it), how i can accomplish this with localtunnel ?

https://www.youtube.com/watch?v=VCH8-XOikQc

**Comment by Oussamaosman02** [comment]
Other great way, and i think is the best one, is lookin at the server part of this project, where you can setup your own domain.
[Server Part](https://github.com/localtunnel/server)

**Comment by TheBoroer** [comment]
I don't think this would be built into the current public server. Your best bet is to fork the server portion and modify it to suit your goal and host it on a small vps somewhere or see if there's other tools that will work better for you
