### ISSUE TITLE
local tunnel is down?

### ISSUE THREAD

**Issue by TommasoRonchin** [localtunnel/localtunnel#530]
Localtunnel send me an error 503. why? please help me, thanks.

**Comment by TheBoroer** [comment]
Sorry about that, the server will be back up shortly.

**Comment by jagadeeshkoka** [comment]
Is it still down ? 

I tried this `lt -p 8084 -h "https://myapp.localtunnel.me" `

It gives me nothing, please help

**Comment by TheBoroer** [comment]
Hey @jagadeeshkoka, the service should be up.
your command seems to be off though, it should be:
`lt -p 8084 -s myapp` and that'll try to give you the subdomain myapp.loca.lt

**Comment by jagadeeshkoka** [comment]
> Hey @jagadeeshkoka, the service should be up. your command seems to be off though, it should be: `lt -p 8084 -s myapp` and that'll try to give you the subdomain myapp.loca.lt

I tried that its not returning anything

**Comment by TheBoroer** [comment]
Hey @jagadeeshkoka can you try again. Seems like the ssl cert was expired for `localtunnel.me`
