### ISSUE TITLE
Is there an option to list requests?

### ISSUE THREAD

**Issue by nandor23** [localtunnel/localtunnel#532]
Did I miss something or the incoming requests cannot be listed to the terminal? For testing purposes it is great to see if a GET method is sent more than once. 

I'm referring to something like this:

<img src="https://user-images.githubusercontent.com/63061477/195509496-5d7767ba-ddf2-4196-b79e-94142c996ccd.png" width=500/>

**Comment by acidclear** [comment]
if you use local tunnel's API you can write a nodejs wrapper to run local tunnel as a child process.  within the child process you can intercept the data and log out the requests to your terminal or to a file/wherever.  i capture the requests using the API in a similar manner to ngrok.

**Comment by nandor23** [comment]
Thank you for answering! I will try it out.

**Comment by TheBoroer** [comment]
you can see incoming requests by including the `--print-requests` when running the `lt` client

e.g. `lt -p 3000 -s coolsubdomainhere --print-requests`

which would output each request like this:
```
your url is: https://coolsubdomainhere.loca.lt
Wed May 17 2023 10:03:28 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:29 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:29 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:30 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:30 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:30 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:30 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:31 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:31 GMT-0400 (Eastern Daylight Time) GET /
Wed May 17 2023 10:03:32 GMT-0400 (Eastern Daylight Time) GET /
```
