### ISSUE TITLE
No cookie setting after response from backend

### ISSUE THREAD

**Issue by AngyDev** [localtunnel/localtunnel#534]
Hi, 

I'm developing a web application with node.js and express as server and React for front end. I'm using authentication and setting the information in the cookies. I send the cookies in the response after the login, the call is ok but when the front end makes a new request to the server I have an error on tokens missing. In local I do not have this error, maybe it is not possible to set the cookies with localtunnel. 

Do you have any idea about it? Thanks.
Angela

**Comment by acidclear** [comment]
i use the same setup with localtunnel, and i don't seem to have any issue passing cookies over the `.loca.lt` domain.  have you tried your setup against a production/staging type environment outside of localhost, or over a domain you control?

**Comment by AngyDev** [comment]
No, unfortunately, I still don't have any environment available other than the local one. Do you have any option to save the cookies on the front end or does just the backend sends the cookies and the browser save them?
Thanks @acidclear

**Comment by acidclear** [comment]
@AngyDev normally the backend will create the cookie and serve it up the front-end, verifying client/server connection in the process.  the browser will then retrieve the cookie and use it to communicate with the server in future calls.  depending on your implementation, the cookie could possible be misconfigured for the domain.  for an example, one of the projects i am working on now i use cookie to do social auth and retrieve the bearer token for a social login.  then i set a cookie in express and send to my react frontend.  my react frontend consumes the cookie, which contains the token, and reads the token value of the cookie to communicate with the server.  one thing to add, make sure your cookie is signed for the right domain.

```
     res.cookie('my_cookie', "my cookie value", {
            domain: '.loca.lt',
            expires:  new Date().setMonth(new Date().getMonth() + 1),
            sameSite: 'None',
            path: '/',
            secure: true,
          });
```

**Comment by AngyDev** [comment]
Thanks a lot @acidclear!! I'm doing the same thing, I'll try this solution and let you know. 😊

**Comment by AngyDev** [comment]
Hi @acidclear! I changed the options in the `res.cookie`, and it's working. But I have another question, I have a doubt, I'm using the localtunnel to expose the whole application, I mean I use the command `lt --port 9000` where the port is the port of the frontend. Is it right? I tried to rich the application from another device but I have a 500 error, I don't understand why. Do you have any idea?
Thanks

**Comment by acidclear** [comment]
Hi @AngyDev I am glad it worked for you!  For your question though I'm not 100% sure, but depending on how your application is setup will depend on which port to expose.  I run _two_ local tunnels, one pointing to my front-end react app (port 3000) and one pointing to my backend api (port 8000).  If you are developing locally with create-react-app, or something similar, you may need to run two tunnels.

However, it sounds like your react app is served up from your express app and you are running everything over port 9000.  In that case, the 500 error could be something  misconfigured on your backend.  Any requests on the backend will now have to point to your local tunnel domain, like any calls to localhost.   I usually manage these domain changes with an `env` file.  I would try logging the errors out and see what the backend says when the 500 error is reported.  On your express app in your root route, toss a `try/catch` and log out the error in the catch.  It should give you some insight as to what happened when you hit the server.

**Comment by AngyDev** [comment]
Hi @acidclear! I see, I'm in your first case. I have the FE developed using webpack and runs on the 9000 port and the BE runs on the 3000 port. Maybe, I am making a mistake by running one tunnel only on the FE port. I have the env file too. The error I don't know why doesn't give any specifications. I'll try also with the express log, but I think it's a FE error when the call to the API starts. Thanks for your time 🙏

**Comment by acidclear** [comment]
Thanks @AngyDev yes, that makes sense.  You will need to run two tunnels.  One will point to the front-end of your react app and the other will point to the back-end.  For these, I setup a node script to launch Local Tunnel as two child processes.  You can achieve the same effect by running local tunnel in two terminals.  Point one tunnel to your front-end and one to your back-end.  Make sure your change your front-end URL's to hit the local tunnel backend.  Point the other tunnel to your back-end and give that a try.  This is the same way you would host a service if you used production, only you would use a storage system like Amazon S3 to host the react app, and a server to host the back-end.  The two services will have two different URL's, your main URL will point to your react app and your react app will call your back-end URLs.

Edit to add:  This is also why local tunnel is valuable for using cross-compatible domain cookies.  And why to set `res.cookie` domain to `.loca.lt`.  It means the cookie will pass between the front-end URL and the back-end URL, as long as those URLs are hosted over a domain on `.loca.lt`

**Comment by AngyDev** [comment]
Thank you very much @acidclear!!! It's working 🎉
