### ISSUE TITLE
Least dependable and buggiest tool

### ISSUE THREAD

**Issue by shjee-afridi** [localtunnel/localtunnel#535]
It legit decided to throw random url to a specificed subdomain when i gave my application out to public never using again

**Comment by brendan** [comment]
Skill issue

**Comment by acidclear** [comment]
valuable lesson learned though, don't give dev URLs out to the public and expect 100% uptime

**Comment by MeemeeLab** [comment]
I agree. I feel this is for development (staging) perpose and you should not use it for production

**Comment by shjee-afridi** [comment]
.
