### ISSUE TITLE
localtunnel down again

### ISSUE THREAD

**Issue by juergenr** [localtunnel/localtunnel#536]
Seems to be down again.

**Comment by jurgob** [comment]
same here. After long time the connection is hanging, I receive this response: 


```
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.17.9</center>
</body>
</html>
```

**Comment by juergenr** [comment]
Interestingly the C# client https://github.com/angelobreuer/localtunnel.net
is working!

**Comment by TheBoroer** [comment]
Hey @juergenr, the service seems to be up and working normally. Have you tried to restart the local tunnel client?

Are you doing stuff like long polling? If yes then this service won't work for you since the reverse proxies I've setup have a timeout setting set

**Comment by juergenr** [comment]
Hi @TheBoroer, thanks for your replay.
No, I'm not doing long polling. My first test is a simple webserver with http or https.
I've done several test, give admin rights, restart several times, use different ports, use different webservers - it always hangs.
While https://github.com/angelobreuer/localtunnel.net (which uses the same backend) and ngrok works.
It would be really nice, if the nodejs client also would work.
Thanks!

**Comment by TheBoroer** [comment]
Hmm that's weird. Did the npm version work for you before? Seems like it's a local issue with your setup since the npm version works for me on two different laptops. Have you tried reinstalling local tunnel?

**Comment by juergenr** [comment]
I'm using: npm version 8.13.2 and node version v18.6.0
Reinstall doesn't change the problem.

**Comment by juergenr** [comment]
I have used a total fresh Windows machine, installed node v18.12.0 and npm 8.19.2, then installed localtunnel and get the same behavior. 
I see the page: "Friendly Reminder" but the button "Click to Continue" does nothing (hangs).

**Comment by alzedd** [comment]
`lt --port xxxx` hangs for me too, even trying to get an url in my app for my dev env is impossibile today.

**Comment by alecmestroni** [comment]
Down again also for me

**Comment by alecmestroni** [comment]
Some news? Is still down for me
@TheBoroer

**Comment by juergenr** [comment]
The nodejs client still hangs for 3 days, now.
The astonishing is, that the .Net client still works fine with the same backend *.loca.lt
So there must be some problem with the nodeJs client ...
So you can use the .Net client as work-around (it works like a charm).

**Comment by alecmestroni** [comment]
localtunnel not working for a week.
Its works sporadically 10% of the time

**Comment by weskified** [comment]
the only way to fix the nodejs client is to allow http tunneling from it like what the C# client does

**Comment by gempir** [comment]
Seems to have issues again. (I'm running the node client)

**Comment by weskified** [comment]
> Seems to have issues again. (I'm running the node client)

You should use the C# version instead and tunnel it by http

**Comment by coolerdoncooper** [comment]
Worked for me for a few weeks and all of a sudden it won't register. lt --port xxxx just hangs there, never returns.
