### ISSUE TITLE
localtunnel.me is down (Connection timeout)

### ISSUE THREAD

**Issue by MeemeeLab** [localtunnel/localtunnel#539]
localtunnel.me seems to be down.

![image](https://user-images.githubusercontent.com/57629983/201472264-37999704-96c9-42fa-a765-e41b98423315.png)

**Comment by RobSchilderr** [comment]
Yeah having the same, guess we have to go outside?

**Comment by acidclear** [comment]
same for me cc @TheBoroer

**Comment by quincyhut** [comment]
same here

**Comment by TheBoroer** [comment]
Should be back up everyone! Datacenter had some networking issues 😭
