### ISSUE TITLE
Unable to use custom subdomain. Seems likes  "lt --port 4400 -h http://loca.lt --subdomain cli20322" Not working | Domain Gives 502 Error

### ISSUE THREAD

**Issue by suryarocks11** [localtunnel/localtunnel#540]

**Comment by suryarocks11** [comment]
![image](https://user-images.githubusercontent.com/19253016/205510294-6cceabd4-3d91-4f8a-8787-11c76f03e89b.png)
Get this error on the domain

**Comment by 107zxz** [comment]
I'm also getting this error, but for randomly generated subdomains as well

**Comment by zakariaeljaz** [comment]
Same here...

**Comment by julianlbs** [comment]
I'm having the same error. I changed to ngrok and it's working fine.

**Comment by suryarocks11** [comment]
I think it's fixed now. So Closing the issue.  Thanks for fixing.
