### ISSUE TITLE
Localtunnel domain loca.lt is down

### ISSUE THREAD

**Issue by XCOD33** [localtunnel/localtunnel#543]
Pls check up the server bcz i have response 504 bad gateway
![image](https://user-images.githubusercontent.com/33880217/210198886-271d4b29-9de8-4846-a154-d52512cc1f3d.png)

**Comment by msaspence** [comment]
Getting the same

**Comment by VeryEvilHumna** [comment]
502 now

![изображение](https://user-images.githubusercontent.com/90103432/212268530-6309bd75-fbbf-469b-8c76-fac36f2d5c6b.png)

**Comment by ThaDaVos** [comment]
Getting a 502 too - it's sad as I use it daily for development

**Comment by TheBoroer** [comment]
Hey all, how often does this happen?
I'm checking the logs but dont see anything that would cause the 502s...

**Comment by ThaDaVos** [comment]
Today? Only thing I saw, tried for 4 hours and all i got where 502's

**Comment by TheBoroer** [comment]
hmm, let me try something. There'll be temporary 502's while i tweak the docker containers a bit. Please try again in like 15min

**Comment by yuriymacdev** [comment]
Perhaps it's worth setting up some kind of a cron job that periodically checks whether it is down?

P.s. the site is still down

**Comment by VeryEvilHumna** [comment]
502...

**Comment by malhanafi** [comment]
It was working for me in past week, but last two days nothing working, after running command, absolutely nothing happens, even in any port, #343 I have checked this issue, but nothing works.

I hope they fix it soon.

**Comment by kishaningithub** [comment]
Its working for me now

**Comment by XCOD33** [comment]
> Its working for me now

no man, it's still 504 gateway timeout

**Comment by kishaningithub** [comment]
@XCOD33 Below is a screenshot of it working

## Startup screenshot
<img width="800" alt="Screenshot 2023-01-27 at 2 40 19 PM" src="https://user-images.githubusercontent.com/763760/215049595-a3436741-1401-46e3-8abc-c726fda3ae81.png">

## Curl Request response screenshot
<img width="800" alt="Screenshot 2023-01-27 at 2 42 15 PM" src="https://user-images.githubusercontent.com/763760/215049926-4a6d72b0-6352-46ce-aca1-5378b579a6f0.png">

**Comment by Jonathan-Alexander-Norberg** [comment]
It worked for me about 1 hour ago, and now it's down.
