### ISSUE TITLE
error 504: bad gateway  

### ISSUE THREAD

**Issue by sofiejb** [localtunnel/localtunnel#545]
Hi, localtunnel has been working for me yesterday, but today when I try to run "lt --port 8080" I get the message "504: bad gateway" when I follow the url. I know for certain that my service is running on that port (works when I go to localhost). What could be the issue?

**Comment by eduwardo** [comment]
Me too, "502 Bad Gateway", seems down.

Already reported here https://github.com/localtunnel/localtunnel/issues/543
