### ISSUE TITLE
Uncaught TypeError: class heritage Transform is not an object or null

### ISSUE THREAD

**Issue by skychik** [localtunnel/localtunnel#549]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `localtunnel@2.0.2` for the project I'm working on.

I had problems with using localtunnel in react in browser, and found, that the solutions after reading this: https://stackoverflow.com/a/73652215/16134912. Idk actually, if this solution won't break something, but it worked for me

The problem: in browser logs I can see: `Uncaught TypeError: class heritage Transform is not an object or null`.

I'm using Vite, btw

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/localtunnel/lib/HeaderHostTransformer.js b/node_modules/localtunnel/lib/HeaderHostTransformer.js
index 18813ef..c588ffd 100644
--- a/node_modules/localtunnel/lib/HeaderHostTransformer.js
+++ b/node_modules/localtunnel/lib/HeaderHostTransformer.js
@@ -1,4 +1,4 @@
-const { Transform } = require('stream');
+const { Transform } = require('readable-stream');
 
 class HeaderHostTransformer extends Transform {
   constructor(opts = {}) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by LucaVas** [comment]
Hi!
I am having the same issue with Vue3. Is there any update on this?
Quick background: as I build a mailer module and run it with node, it works fine. As soon as I import it to my component, I get the same error:
![image](https://github.com/localtunnel/localtunnel/assets/104051992/6484c22f-aeb7-437c-9e2e-23f7f001303f)

**Comment by TheBoroer** [comment]
I don't think you can run the actual localtunnel client in the browser.
Please run it from a new terminal alongside `vite` or any other server/serving build tools.
