### ISSUE TITLE
Suspended tunnel initialization

### ISSUE THREAD

**Issue by leungkinghin-ct** [localtunnel/localtunnel#550]
Today we found that the tunnel initializtion process got suspended and timeout, which still worked on last Friday.

```
await localtunnel({
        port : 3002,
        subdomain: 'ctp-adyen-integration-tests',
      })
```

We have ever changed the port number but it didn't help. Can your team help to check what is going wrong?
Thanks.

**Comment by pcieszkowski** [comment]
SSL certificate is expired, you can try connecting to localtunnel.me using http not https.

**Comment by leungkinghin-ct** [comment]
It has been resumed today. thx
