### ISSUE TITLE
LocalTunnel 'lt' Currently Hanging

### ISSUE THREAD

**Issue by biscuits4cheese** [localtunnel/localtunnel#551]
Hello,
My 'lt' commands are currently hanging (23/01 @ 08:43GMT).

Anyone else having issues?

**Comment by kseniyaleutseyevasnmt** [comment]
I'm currently having the same issue

**Comment by LeeCrey** [comment]
lt -p portValue -h http://localtunnel.me --subdomain your-sub-domain

**Comment by quincyhut** [comment]
> -h http://localtunnel.me

this works for me

**Comment by biscuits4cheese** [comment]
@LeeCrey  and @quincyhut 
Thanks for the suggestions.  This works for me too, but this is the _first_ occasion that I've needed to add -g http://localtunnel.me to my command line.

I wonder why?

Thanks again.

**Comment by marek-veber** [comment]
Subject: localtunnel.me
Issuer: R3
Expires on: 22. 1. 2023
Current date: 23. 1. 2023

?

**Comment by charlycator** [comment]
Hi! 

Had the same issue. As suggested by @LeeCrey , adding the `-h http://localtunnel.me/ `works for me as well.

Thanks @LeeCrey !

**Comment by pcieszkowski** [comment]
yep, looks like SSL certificate expired, so only **http** connection works right now


```
Server Key and Certificate #1
--
Subject | localtunnel.me
Fingerprint SHA256: 4db81187499c437b1228f2df69d21ba01bab82a737276116a8906569a8ad3040Pin 
SHA256: dQd0Krfy8Phsqchgar3fQ/svJNkMHcapT9MWoXtR2so=
Common names | localtunnel.me
Alternative names | localtunnel.me www.localtunnel.me
Serial Number | 046c0608c8235a94ab18b60b973c85b4f154
Valid from | Mon, 24 Oct 2022 16:57:07 UTC
Valid until | Sun, 22 Jan 2023 16:57:06 UTC (expired 20 hours and 45 minutes ago)   EXPIRED
Key | RSA 2048 bits (e 65537)
Weak key (Debian) | No
Issuer | R3AIA: http://r3.i.lencr.org/
Signature algorithm | SHA256withRSA
Extended Validation | No
Revocation information | OCSPOCSP: http://r3.o.lencr.org
Revocation status | Unchecked
```

**Comment by jcjpsa** [comment]
Anybody experienced `408` error on their subdomain? I am on Windows 11 + WSL the 1st request returns `404` then subsequent requests returns `408`?

**Comment by joshuakcockrell** [comment]
This issue seems to happen every 6 months: https://github.com/localtunnel/localtunnel/issues/501#issuecomment-1171613799

Localtunnel is really an incredibly useful service for webhook testing. It's amazing that it's free. I can't imagine the amount of spammy/abusive actors that the maintainers have to deal with.

I'd gladly pay $5/month for a production level service. If it were up to me, localtunnel would have a highly restricted free tier (no https, rate limits) and a paid option. Not hard to make the pricing look great compared to ngrok's crazy $25/month. Also the ease of use. I love that localtunnel is just a node package.

**Comment by biscuits4cheese** [comment]
@joshuakcockrell I could not agree more. It's just so easy to use. There are alternative 'solutions' out there most of which claim to be free until you want to use custom or subdomains. Localtunnel is a genuine and extremely useful service that I don't take for granted.

**Comment by tcaruchet** [comment]
@LeeCrey Now, with this command it's not longer work. 408 within 1 minute... I have a school project based on localtunnel and I'm disapointed... :(

**Comment by jcjpsa** [comment]
> @LeeCrey Now, with this command it's not longer work. 408 within 1 minute... I have a school project based on localtunnel and I'm disapointed... :(

Try running it behind a proxy: https://github.com/localtunnel/localtunnel/issues/547#issuecomment-1400767211 haven't tried it yet but I think it's unstable on Windows for me.

**Comment by TheBoroer** [comment]
closing since it should be running fine again. lmk if i need to re-open
