### ISSUE TITLE
Link not generating.

### ISSUE THREAD

**Issue by imsimgaa022** [localtunnel/localtunnel#552]
`npx localtunnel --port 8000`

All i get is this message:
`npx: installed 22 in 3.114s`

**Comment by TommasoRonchin** [comment]
i've same problem

**Comment by ernst77** [comment]
same

**Comment by joshuakcockrell** [comment]
Happening for me too. Trying to connect through `await localtunnel(...)` hasn't been working for me all weekend. Thought I was going crazy.
