### ISSUE TITLE
ATTENTION: Scheduled Downtime/Maintenance - January 23, 2023

### ISSUE THREAD

**Issue by TheBoroer** [localtunnel/localtunnel#553]
Hi all,

The localtunnel public server will be offline for a few hours today. The datacenter it's hosted in is undergoing some network and power maintenance so the server will be off until that's completed as a precaution.

Sorry for the inconvenience 😬 😅

**Comment by cjerrington** [comment]
Linking to following as they seem related to the maintenance and time frame: 
- #551 
- #552

**Comment by david100awesome** [comment]
when is the eta for it being up?

**Comment by Parking-Master** [comment]
Thanks for the information. I was wondering why my website and the loca.lt site wasn’t loading

**Comment by Parking-Master** [comment]
@david100awesome probably tomorrow. He said a few hours and it looks like it’s not going to be up tonight.

**Comment by TheBoroer** [comment]
Everything should be back up now! :) 
Lmk if something's not working for anyone

Thanks for the patience everyone!

**Comment by mattbarnicle** [comment]
@TheBoroer When I start lt, it prints out a URL but then shuts down. Doesn't print any message about why. I'm running Docker within a traefik network for my proxied endpoint, so I'm using the `--local-*` flags in order to accomplish that. This was working no more than a week ago. Any ideas on what I can look at? Is there a way to print debugging info? Thanks. 

```lt \
  --local-host domain.local \
  --local-https true \
  --local-cert ~/docker/traefik/certs/domain-cert.pem \
  --local-key ~/docker/traefik/certs/domain-key.pem \
  --local-ca ~/.local/share/mkcert/rootCA.pem \
  --port 443 \
  --print-requests
```

**Comment by italodeandra** [comment]
https://isitup.org/localtunnel.me `localtunnel.me seems to be down 💥`

Is everything okay?

**Comment by Parking-Master** [comment]
Yeah me too seems to be down. No information provided. It also looks like the entire system is down because the main website isn't loading either. I'm sure it will work soon because this type of thing happens about every month or so.
