### ISSUE TITLE
When I start `lt`, it prints out a URL but then exits immediately after

### ISSUE THREAD

**Issue by mattbarnicle** [localtunnel/localtunnel#555]
Doesn't print any message about why. I'm running Docker within a traefik network for my proxied endpoint, so I'm using the `--local-*` flags in order to accomplish that. This was working no more than a week ago.

I tried running a basic proxy with the command `lt --port 8001` and that worked as expected. So this seems to be something to do with the `--local-*` flags. But this was working well for me previously. I haven't changed the args either.

This is the command that isn't working now:

```
lt \
  --local-host domain.local \
  --local-https true \
  --local-cert ~/docker/traefik/certs/domain-cert.pem \
  --local-key ~/docker/traefik/certs/domain-key.pem \
  --local-ca ~/.local/share/mkcert/rootCA.pem \
  --port 443 \
  --print-requests
```

`lt --version` is `2.0.2`. System is Void Linux. Not sure what else I need to include.

**Comment by kavishdevar** [comment]
Seems the issue is with the localhttps/ca/key/cert arguments.

This fixed the issue for me.

https://github.com/localtunnel/localtunnel/issues/472#issuecomment-1447562993

**Comment by ItsMeKoder** [comment]
Seems the issue is with the localhttps/ca/key arguments.

This fixed the issue for me.

https://github.com/localtunnel/localtunnel/issues/472#issuecomment-1447562993

**Comment by mattbarnicle** [comment]
> Seems the issue is with the localhttps/ca/key/cert arguments.
> 
> This fixed the issue for me.
> 
> [#472 (comment)](https://github.com/localtunnel/localtunnel/issues/472#issuecomment-1447562993)

thanks. I'll check that out.

**Comment by mattbarnicle** [comment]
i'm not sure why i had to do it, but by adding `--allow-invalid-cert true` to the args, my problem went away. will close the issue.

**Comment by ShaneBurkhart** [comment]
Just FYI for anyone that comes looking, add environment variable `DEBUG=localtunnel:client` to debug errors.
