### ISSUE TITLE
lt command : Custom sub-domain names no longer work.

### ISSUE THREAD

**Issue by biscuits4cheese** [localtunnel/localtunnel#556]
Hello,

Recently  I observed a lt command of the form:

_**lt --port port_no --subdomain sub_domain_name**_

which had worked well for many months suddenly stopped working.

This was circumvented by using a command of the form:

**_*lt --port port_no--host http://localtunnel.me --subdomain sub_domain_name*_**

which has worked successfully for over a week.

Today (30/01 @ 10:30am GMT) I am now finding that custom sub-domain names no longer work.  Specifically, I get a randomised sub-domain name instead of my expected custom sub-domain name.

Has anyone also observed this, and are there any suggestions on how to circumvent?

Thanks

**Comment by biscuits4cheese** [comment]
As a point of note lt commands of the form:

lt --port port_no --subdomain sub_domain_name

still just hang.

And looking at recent raised issues other fundamental functionality no longer works either.

Perhaps a service reboot is appropriate here?

**Comment by biscuits4cheese** [comment]
Having waited 25mins and reattempting 

**_lt --port port_no--host http://localtunnel.me/ --subdomain sub_domain_name_**

The sub-domain feature appears to work again.

In view of this (and the previous issues raised) I will try to run my own server locally when I get time.

**Comment by RobSchilderr** [comment]
same issue

**Comment by TheBoroer** [comment]
it should work! hanging usually means there's an issue with the server. I recently fixed a memory leak on the same instance that the public server is hosted on so that may have been causing localtunnel to hang once every few hours.

lmk if it's still an issue and i'll re-open
