### ISSUE TITLE
localtunnel not working

### ISSUE THREAD

**Issue by MirYeh** [localtunnel/localtunnel#557]
I'm running localtunnel locally and seems like there's some issue, couldn't find an update on this online.

To replicate, simply run `lt --port 8080` - it hangs without returning a response.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/15251650/215515043-bbfecc21-021e-46f3-be06-909ffe41a88b.png">

**Comment by christopherglennreed** [comment]
Same. his website appears to be down as well. So I would guess localtunnel is down.

**Comment by codeundercoverdev** [comment]
localtunnel is down

**Comment by RobSchilderr** [comment]
Its down quite often recently unfortunately haha. He should make this a paid thing and guarantee uptime. @TheBoroer could you check whats going on?

**Comment by acidclear** [comment]
> Its down quite often recently unfortunately haha. He should make this a paid thing and guarantee uptime

i wouldn't mind paying for localtunnel, but they'd need to get a WAF for their domains.  ngrok had no WAF and thus exposed it's users to ongoing attacks unless you were explicitly watching the requests.  it's the reason i switched to localtunnel.

**Comment by christopherglennreed** [comment]
looks to be backup up now.  Total Downtime: 05:14:55

**Comment by MirYeh** [comment]
Confirming that `localtunnel` is now working, I'll close this issue for now.
