### ISSUE TITLE
Localtunnel down again!

### ISSUE THREAD

**Issue by acke1337** [localtunnel/localtunnel#560]
Localtunnel is again down... I can't believe...

**Comment by Parking-Master** [comment]
It’s been down since noon yesterday. I don’t know what’s going on and why it keeps going out every 2 days!

**Comment by acke1337** [comment]
> It’s been down since noon yesterday. I don’t know what’s going on and why it keeps going out every 2 days!

I started a project last night and the tunnel shut down. It hasn't shown any signs of life since then, and I really like this option. If this continues I will have to get a static ip address and make my own host. It's not worth it like this anymore. I already have a website that is functional and doing my job, clients are waiting for me and I can't explain to them that the problem is not my fault.

**Comment by Parking-Master** [comment]
I have a project called Simple-Mailer that I finished last year. It used to work all the time and there were problems here and there, but not as many as now. My website barely runs anymore and it's annoying because I even use my own project on some other projects.

**Comment by Parking-Master** [comment]
I may have to unstar this project. It basically doesn't even work anymore

**Comment by niraj-khatiwada** [comment]
Localtunnel is not reliable for me these days. Does anyone know any better alternatives?

**Comment by Parking-Master** [comment]
Upon ny research localtunnel is the best. Ngrok is insecure and you have to pay for it, and I don’t know of any other services. If you don’t need to use server side code, you can use github pages to host your website. I even have multiple free domains from freenom.com that are really easy to remember.

**Comment by samuelmorais** [comment]
Who maintains localtunnel, anyway? Is there a server being hosted anywhere (sorry if it is a stupid question, I am just a little bit lazy today to search for it).

**Comment by TheBoroer** [comment]
Sigh sorry guys. The datacenter I'm hosting this in is having network issues again so things aren't working atm. Unfortunately I can't switch to another host due to the huge amount of abuse notices that i get.

Should be up in a couple hours 😅

**Comment by acke1337** [comment]
> 

Sorry to hear that. Can you tell me whats going on in Serbian language? I think you're Serbian guy.

**Comment by samuelmorais** [comment]
Hi @TheBoroer , thank you for the info! Sorry to bother you. Congrats for this work.

**Comment by Parking-Master** [comment]
Ok, thanks for the update. Now I know my website won’t have any more problems

**Comment by aintHuman** [comment]
> Sigh sorry guys. The datacenter I'm hosting this in is having network issues again so things aren't working atm. Unfortunately I can't switch to another host due to the huge amount of abuse notices that i get.
> 
> Should be up in a couple hours 😅

Are those abuse notices from disgruntled developers that are tired of the unreliability of localtunnel?

**Comment by TheBoroer** [comment]
> Are those abuse notices from disgruntled developers that are tired of the unreliability of localtunnel?

Most definitely not 😂 if you're unhappy feel free to check out ngrok or self host your own private instance of localtunnel.

The flood of abuse notices are because bad people use localtunnel to host phishing or malware portals

**Comment by Parking-Master** [comment]
Localtunnel is amazing. Even know it’s free, and very unreliable, it still works pretty good. Thank you for making this free @TheBoroer

**Comment by maxtpham** [comment]
Could you please let us know when the service backonline? As we done a deep integration inside Nodejs Server so can not switch over :((

**Comment by biscuits4cheese** [comment]
Hello, 07:39GMT 06/02 and still down. Please please restore service.  Thanks.

**Comment by leungkinghin-ct** [comment]
still down

**Comment by SebastianMaung** [comment]
No pressure! Thank you for this service!

**Comment by acke1337** [comment]
Guys :) As @TheBoroer said, they are having networking issues in their data center. Boro can't do anything, he's waiting for the technicians ( ISP technicians ) to solve the problem.

**Comment by JonoHall** [comment]
If reliability is an issue for you, you can set up your own server:
https://github.com/localtunnel/server

It takes a bit of tinkering, but I figured it out in a few hours.

If you've got a server with docker installed somewhere handy (I have a Synology NAS with docker on it), you set up the container using a config such as host dev.xxx.ddns.etc, port 3000. Then use Synology's built in Reverse Proxy to point your domain dev.xxx.synology.me:443 to localhost:3000.

You will also need to open ports 443:80 to your NAS (could already be done if you access your NAS externally), then ports 30,000-50,000,3000 also to your NAS for Local Tunnel.

I'm now able to access my local development server via https://dev.xxx.ddns.etc/ without any extra port info (thanks to the reverse proxy).

_**Ps. I'm no security expert, so take this post with a grain of salt. Exposing ports to internal network computers can/will be dangerous.**_

_**I'm really not in the position to provide support in making this solution work. If you're able to work it out with the set up guide provided on the localtunnel/server github page, then you probably shouldn't be doing it.**_

**Comment by irumata** [comment]
Thanks guys for these service, we are very waiting when this comes back!

**Comment by Parking-Master** [comment]
It should be back up around 2:00-4:00 P.M. today.

**Comment by acke1337** [comment]
> It should be back up around 2:00-4:00 P.M. today.

How do you know?

**Comment by aintHuman** [comment]
My OCD is on overdrive right now because of a zillion failed stripe webhook events on my local development server ...

**Comment by Parking-Master** [comment]
@acke1337 He said a few hours it should be up. He has the same time zone as me and I'm sure he's not staying up all night to fix this. I feel like localtunnel usually comes back in the afternoon too when it's down. I'm just estimating the time, I don't actually know but we'll see.

**Comment by Parking-Master** [comment]
I really depend on localtunnel to be up. One of my projects/games I'm currently in development with uses a project I made last year to send emails. One of the pages won't load on my game, and I figured out it's from localtunnel being down. The page on my website hasn't loaded since 2 days ago

**Comment by Packjackisback** [comment]
I last used it 2 hours ago, it was down

**Comment by shaipetel** [comment]
> Sigh sorry guys. The datacenter I'm hosting this in is having network issues again so things aren't working atm. Unfortunately I can't switch to another host due to the huge amount of abuse notices that i get.
> 
> Should be up in a couple hours 😅

Hey, maybe I can help with more reliable hosting, depending on resource usage/costs. feel free to reach out to me on reddit user @sirp1nky or twitter @shpetel

**Comment by acidclear** [comment]
i think everyone here needs to treat localtunnel as a dev tool and realize they can't rely on a free service for production level reliability.   i use localtunnel to regularly debug my mobile apps and rest api's because it easily lets me share a domain without having to setup too much crazy network wizardry.  it's an awesome tool and as others have pointed out it's more secure than ngrok.  localtunnel should be used (as the name implies) to host your localtunnel.  not a production-capable application.

imo, application code shared with external clients should be behind a secure system (digital ocean/azure/aws) in a proper staging or development environment.

**Comment by Packjackisback** [comment]
I use it as a temporary server for a friend, or for testing. Relying on a 3rd party like this is a terrible idea for anything important

**Comment by Parking-Master** [comment]
Guess I was wrong. This is ridiculous, it’s been down for exactly 3 days now. Please come back

**Comment by ciclon5** [comment]
> Guess I was wrong. This is ridiculous, it’s been down for exactly 3 days now. Please come back

they cannot do anything. this is an issue with the service provider local tunnel uses as host. its beyond the creator,s control.

**Comment by JonoHall** [comment]
> Guess I was wrong. This is ridiculous, it’s been down for exactly 3 days now. Please come back

Have you got a plan when they decide this free service is too much hassle and they close it down?

Keep in mind that LocalTunnel and its server are both open source, you can run you own server. You should only be using this for non-critical development and testing and be thankful they supply this service at all.

I'm not sure who pays to keep this server up, but I'm thankful it's been a pretty solid service for the couple of years I've used it.

**Comment by Parking-Master** [comment]
It’s fine if it’s down, I don’t need it that bad. But I mean, what happened that made it go down for more than 3 days?

**Comment by TheBoroer** [comment]
> It’s fine if it’s down, I don’t need it that bad. But I mean, what happened that made it go down for more than 3 days?

If you scroll up, i left a note saying why it's down 😅 sorry guys but it's kinda out of my control atm.

https://github.com/localtunnel/localtunnel/issues/560#issuecomment-1418269714

**Comment by Parking-Master** [comment]
@TheBoroer Do you know of anyone’s fixing the servers? How long it’s going to take and how bad it is?

**Comment by TheBoroer** [comment]
Yep! They're working on it. It's not the server that's busted its the networking routes to the server 😞

Unfortunately no ETA, they said they might have it going tonight or early tomorrow

**Comment by Parking-Master** [comment]
Ok, thank you

**Comment by AdityaZagadeCT** [comment]
Still down

**Comment by MarkusSagen** [comment]
Thanks for working on this @TheBoroer, Localtunnel has been very convenient dev tool
It's not going to go faster or slower by commenting if it's still "down", you can easily check it with:
https://www.isitdownrightnow.com/

**Comment by Parking-Master** [comment]
> you can easily check it with:
> https://www.isitdownrightnow.com/

lol, I’ve just been going to loca.lt myself and seeing if it loads. Either way works

**Comment by Parking-Master** [comment]
Another day goes and it is still down, my hopes go out to everyone that it will be back up tomorrow.

**Comment by TheBoroer** [comment]
Sigh... I very sorry for the downtime everyone.
I got an update that things should be up tomorrow...so I'm hopeful. For those who know what BGP is, there's some bgp issues at the datacenter. I'm trying to figure out some alternatives to get stuff back up and running asap

**Comment by maxtpham** [comment]
Thank you @TheBoroer, very appriciate for your support to the community!

**Comment by zapletnev** [comment]
@TheBoroer thanks for the update and great product!

**Comment by yash-sharma1** [comment]
Appreciate your support and the work you've done for the community @TheBoroer.

**Comment by Parking-Master** [comment]
Yes! It’s back up! Thanks to the people who worked all of that time fixing it.

**Comment by aintHuman** [comment]
Thankyou.

**Comment by biscuits4cheese** [comment]
Thanks for your hard work getting this service back online.  Your effort is greatly appreciated!

**Comment by EmilioP94** [comment]
back up but down again or is it just me?

**Comment by Parking-Master** [comment]
Lol down again

**Comment by Parking-Master** [comment]
It can't even stay up for more than a day now

**Comment by SebastianMaung** [comment]
It seems ok for me...

**Comment by Parking-Master** [comment]
Ok, it’s back up now. Hopefully it will still be back up tomorrow lol. You can close this issue now

**Comment by carelesswhisp** [comment]
is it back down?

**Comment by Parking-Master** [comment]
@carelesswhisp no, it’s working fine. It hasn’t been down for a week.

**Comment by askeijaz** [comment]
localtunnel is giving 504 Gateway Time-out error.

Installed it for the 1st time today. Is this the usual scenario with LocalTunnel?

Any idea if there is any maintenance issue happening and if so, by when it is going to up and running?

**Comment by Parking-Master** [comment]
Looks like it’s working fine
