### ISSUE TITLE
Localtunnel down again? (February 27, 2023)

### ISSUE THREAD

**Issue by Developer-07** [localtunnel/localtunnel#570]

**Comment by TheBoroer** [comment]
Yup there seems to be some network uplink issues going on again at the data center smh. I don't expect it to be down long though 🤞

**Comment by Parking-Master** [comment]
@TheBoroer ok thanks for the info. Hopefully it will be back up soon (not for an entire week lol)

**Comment by dgknca** [comment]
Come on babe. I can't wait any longer.

**Comment by TheBoroer** [comment]
Hold onto your socks everyone, I'm working on a fix!

**Comment by AbdelrhmanNile** [comment]
its back!

**Comment by Parking-Master** [comment]
I think you know why I’m commenting again

**Comment by Parking-Master** [comment]
It’s down

**Comment by AbdelrhmanNile** [comment]
i confirm, not stable

**Comment by TheBoroer** [comment]
Investigating! The host seems to have problems reaching the docker hub registry for some reason so new docker images aren't being pulled -_-

**Comment by TheBoroer** [comment]
Oh also let's move chats over to #574 😅
