### ISSUE TITLE
Is https://localhost supported?

### ISSUE THREAD

**Issue by SimeonC** [localtunnel/localtunnel#58]
I'm running my server as a https of localhost - special node.js server - and it seems that I only get 504 bad gateway errors. I think this is because the following startup: `lt --port 3443` still tries to redirect down to `http://localhost:3443`. Is there any way of having a https option available?

I probably shouldn't develop in https with self signed certs, but as I use node I have redirects in to force https.

**Comment by jimmypuckett** [comment]
I know that this is an old thread, but @defunctzombie do you think that you will be adding this feature?

**Comment by defunctzombie** [comment]
@jimmypuckett I would review a PR for it if someone got around to doing it, but I myself don't have the time to code it up anytime soon.

**Comment by jimmypuckett** [comment]
@defunctzombie I totally understand, and I was thinking about doing it, but did not want to invest time if you were 95% done ;-).

I will see what we can do.  Thanks!
