### ISSUE TITLE
local tunnel is not availabe - 502 Bad Gateway

### ISSUE THREAD

**Issue by elihayananas** [localtunnel/localtunnel#583]
it seems the bad gateway issue from a few weeks ago is happening again :(

**Comment by alberchou** [comment]
Same problem here... Yesterday it was working :(

**Comment by alberchou** [comment]
It is working now!! :D

**Comment by faizan-glowlogix** [comment]
> It is working now!! :D

thanks for informing

**Comment by biscuits4cheese** [comment]
Thank you for fixing. Much appreciated!
