### ISSUE TITLE
localtunnel : Currently not receiving webhooks from third party application.

### ISSUE THREAD

**Issue by biscuits4cheese** [localtunnel/localtunnel#585]
Hello,
As at 12:08 GMT on 12/04/23 can anybody please confirm if their 'localtunnel' connections are currently working?
Thanks.

**Comment by Mhaxym** [comment]
Same problem here, it's returning 502.

**Comment by biscuits4cheese** [comment]
Thanks @Mhaxym

**Comment by amdradeonhd6950** [comment]
Me too, I'm getting 502 bad gateway since about 3 hours ago.

**Comment by biscuits4cheese** [comment]
Thanks @amdradeonhd6950

**Comment by alberchou** [comment]
Still down :(

**Comment by Jeffersonceo** [comment]
still no answers?

**Comment by TheBoroer** [comment]
Should be back up! Lmk if it's not and I'll reopen this issue

**Comment by biscuits4cheese** [comment]
@TheBoroer Thanks for fixing
