### ISSUE TITLE
502 Bad Gateway again 😢

### ISSUE THREAD

**Issue by amdradeonhd6950** [localtunnel/localtunnel#588]
![20230416_080940](https://user-images.githubusercontent.com/82917025/232256871-93108721-6e7d-4b7e-ab24-d0e68aae0976.jpg)
😢😢

**Comment by Yggdrasil777** [comment]
I can also vouch for that one. It is currently giving the error at this time. Appears to be down at the moment.

**Comment by Parking-Master** [comment]
I get the same thing but @TheBoroer is like superman lol he’ll get it under control

**Comment by Parking-Master** [comment]
It’s back up now. You can close this issue

**Comment by amdradeonhd6950** [comment]
Thanks to administrators of Localtunnel!

**Comment by TheBoroer** [comment]
Sorry guys, I haven't had the time to look into wth is causing these issues but a quick restart seems to have fixed it 😅

**Comment by Parking-Master** [comment]
@TheBoroer have you tried turning it off and on again? 😂
