### ISSUE TITLE
Connection Resets are crashing the tunnel

### ISSUE THREAD

**Issue by surajreddy** [localtunnel/localtunnel#59]
I'm getting the following error when a user resets their connection

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
```

**Comment by devill** [comment]
I have the same issue with version 1.7.0. It keeps crashing every few minutes. :(

**Comment by 3thanZ** [comment]
Same here. I'm on OSX 10.10.5 using localtunnel 1.7.0. I'm running the command from terminal and seem to get this problem as soon as I hit the generated URL the first time.
