### ISSUE TITLE
Stopped working - cli hangs

### ISSUE THREAD

**Issue by asimen1** [localtunnel/localtunnel#591]
Attempting to browse to [https://localtunnel.me/](https://localtunnel.me/) url bring "certificate expired" warning - probably related (see image).

![SCR-20230424-kewq](https://user-images.githubusercontent.com/12048798/233938633-f24ebda7-52b8-4f5c-9d1d-a3f2b34579f0.png)

**Comment by AdityaZagadeCT** [comment]
lt --port 3000

Attempting to tunnel to your local server is also not working.

**Comment by alberchou** [comment]
lt --port XXXXX not returning any URL

**Comment by rannooo** [comment]
Temporary workaround is to specify the non-https server host, until the cert issue gets resolved:
`localtunnel --port 3000 --host http://localtunnel.me`

**Comment by TheBoroer** [comment]
fixed! sorry everyone!
