### ISSUE TITLE
Absolutely not working

### ISSUE THREAD

**Issue by Andriy0289** [localtunnel/localtunnel#592]
`% sudo npx lt -p 3000
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy/.npm/_logs/2023-04-24T15_48_27_804Z-debug-0.log
% sudo npx lt -p 3000
Password:
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy/.npm/_logs/2023-04-24T16_00_30_059Z-debug-0.log
% brew uninstall localtunnel
Uninstalling /usr/local/Cellar/localtunnel/2.0.2... (242 files, 1MB)
 % npm install -g localtunnel

added 22 packages in 670ms

3 packages are looking for funding
  run `npm fund` for details
 % npx localtunnel --port 8000
^C
% lt --port 8000 
^C
% lt --help     
Usage: lt --port [num] <options>

Опції:
  -p, --port                Internal HTTP server port              [обов'язково]
  -h, --host                Upstream server providing forwarding
                                    [за замовчуванням: "https://localtunnel.me"]
  -s, --subdomain           Request this subdomain
  -l, --local-host          Tunnel traffic to this host instead of localhost,
                            override Host header to this host
      --local-https         Tunnel traffic to a local HTTPS server     [boolean]
      --local-cert          Path to certificate PEM file for local HTTPS server
      --local-key           Path to certificate key file for local HTTPS server
      --local-ca            Path to certificate authority file for self-signed
                            certificates
      --allow-invalid-cert  Disable certificate checks for your local HTTPS
                            server (ignore cert/key/ca options)        [boolean]
  -o, --open                Opens the tunnel URL in your browser
      --print-requests      Print basic request info                   [boolean]
      --help                Show this help and exit                    [boolean]
      --version             Показати версію                            [boolean]
% lt --version
2.0.2
% 
% 
`

**Comment by bdhanoa** [comment]
The certificate for domain https://localtunnel.me/ is expired. Please fix.

Following is the error from google chrome:

"This server could not prove that it is localtunnel.me; its security certificate expired in the last day."

**Comment by TheBoroer** [comment]
fixed! 

Sorry about that, i gotta switch the server to use traefik instead of a custom nginx setup for localtunnel when i get some free time...
