### ISSUE TITLE
Localtunnel keep stopping after some time with no errors

### ISSUE THREAD

**Issue by azuzii** [localtunnel/localtunnel#596]
After sometime of starting the web all using lt --port 3000 --subdomain <subdomain> it works fine bu5 after some time ( it random there is no exact time ) it stops, before it was throwinf an error that had to do something with the firewall but I disabled firewall and now it just stops with no error ot like someone came a pressed "ctrl + c".
And about the firewall thing even if I allow it, it still does the same thing.

**Comment by Parking-Master** [comment]
That happens a lot actually, it’s nothing new. My server froze a little while ago but I did not check the error. A simple restart put it back up so it’s working again.

PS: I use “forever” which is an NPM package if you didn’t know. It prevents this error and keeps your server up for even months. I notice that when I use plain “node {file.js}” (for testing) it does do that after a while. I recommend forever, it’s really easy to use: https://www.npmjs.com/package/forever

```bash
# To start:
forever start file.js

# To stop:
forever stop file.js

# Stop every process:
forever stopall
```

Hope this gives you some information and helps 😀

**Comment by azuzii** [comment]
> That happens a lot actually, it’s nothing new. My server froze a little while ago but I did not check the error. A simple restart put it back up so it’s working again.
> 
> PS: I use “forever” which is an NPM package if you didn’t know. It prevents this error and keeps your server up for even months. I notice that when I use plain “node {file.js}” (for testing) it does do that after a while. I recommend forever, it’s really easy to use: https://www.npmjs.com/package/forever
> 
> ```shell
> # To start:
> forever start file.js
> 
> # To stop:
> forever stop file.js
> 
> # Stop every process:
> forever stopall
> ```
> 
> Hope this gives you some information and helps 😀

Ok thanks I will try it, and do you know if it works with nodemon?

**Comment by Parking-Master** [comment]
@azuzii I have never used nodemon but I’m sure it does. Let me check…

**Comment by Parking-Master** [comment]
Ok, it does support it, says it on the top of the documentation

**Comment by azuzii** [comment]
> Ok, it does support it, says it on the top of the documentation

Thanks 👍

**Comment by azuzii** [comment]
> That happens a lot actually, it’s nothing new. My server froze a little while ago but I did not check the error. A simple restart put it back up so it’s working again.
> 
> PS: I use “forever” which is an NPM package if you didn’t know. It prevents this error and keeps your server up for even months. I notice that when I use plain “node {file.js}” (for testing) it does do that after a while. I recommend forever, it’s really easy to use: https://www.npmjs.com/package/forever
> 
> ```shell
> # To start:
> forever start file.js
> 
> # To stop:
> forever stop file.js
> 
> # Stop every process:
> forever stopall
> ```
> 
> Hope this gives you some information and helps 😀

I'm back, it works fine but the problem I mentioned is not with "node server.js" it "lt --port PORT" that stops after X time and it got worse today, just after mins of launching it stops (same as before it loke someome came and pressed ctrl+c to exit) i frustrating, I tried pm2 so that it will keep restarting the cmd if it exits or fails and still same issue.

**Comment by Parking-Master** [comment]
@azuzii I know you get the same firewall error if you use javascript to start your server or if you use a command. Here’s my script (never gives me firewall errors):

```javascript
(async () => {
  const tunnel = await localtunnel({ port: 8080, host: "http://loca.lt" });

  console.log(tunnel.url);

  tunnel.on("close", () => {
    console.log("\nTunnel closed");
  });

  process.on("SIGINT", () => {
    tunnel.close();
    process.exit(0);
  });
})();

app.listen(8080);
```

Put this code at the end of your main file, then start that file using “forever start file.js”. Your server will run forever until using “forever stop file.js”. Forever will get rid of this firewall error, leave your script running even when closing the terminal, and when there is an error or stopping the script, the “process.exit(0)” function at the end of the code will stop your server automatically.

Please try my above advice and code, then let me know if you still get this error.

**Comment by azuzii** [comment]
> @azuzii I know you get the same firewall error if you use javascript to start your server or if you use a command. Here’s my script (never gives me firewall errors):
> 
> ```javascript
> (async () => {
>   const tunnel = await localtunnel({ port: 8080, host: "http://loca.lt" });
> 
>   console.log(tunnel.url);
> 
>   tunnel.on("close", () => {
>     console.log("\nTunnel closed");
>   });
> 
>   process.on("SIGINT", () => {
>     tunnel.close();
>     process.exit(0);
>   });
> })();
> 
> app.listen(8080);
> ```
> 
> Put this code at the end of your main file, then start that file using “forever start file.js”. Your server will run forever until using “forever stop file.js”. Forever will get rid of this firewall error, leave your script running even when closing the terminal, and when there is an error or stopping the script, the “process.exit(0)” function at the end of the code will stop your server automatically.
> 
> Please try my above advice and code, then let me know if you still get this error.

I will give this a try, thanks :)

**Comment by Parking-Master** [comment]
No problem! Hope it works :)
