### ISSUE TITLE
502 Bad Gateway on all tunnels

### ISSUE THREAD

**Issue by AutumnalModding** [localtunnel/localtunnel#599]
Title.

**Comment by biscuits4cheese** [comment]
I concur.  As at 08:54GMT all my third-party webhooks to my middleware have stopped working.  Command line 'lt' command starts ok though (does not terminate with any errors).

I've double checked the third-party app logs and the web hooks appear to have been submitted, but I don't receive them.

**Comment by GilEliyahu23** [comment]
Hi, I also get this error..

**Comment by uriariel** [comment]
:nightmare:

**Comment by kdha0528** [comment]
Me too

**Comment by TheBoroer** [comment]
Hi, is it working for you guys now?

**Comment by biscuits4cheese** [comment]
@TheBoroer 
Yes thank you very much. It is! Cheers!
