### ISSUE TITLE
localtunnel error: no active client for ....

### ISSUE THREAD

**Issue by GeoffreyPlitt** [localtunnel/localtunnel#60]
Hi,

I'm following all instructions and my tunnels used to work. I haven't changed anything, but now tunnels that should work are showing "localtunnel error: no active client for ....".

Is the service down? It would be nice if it gave a different error when the service itself is down, vs if it thinks my local service is not responding (which it is).

**Comment by antton** [comment]
Hi, 
Which are the ports we need to keep open? I'm not able to make it work, and I think is for the company firewall.
Any Wiki or Doc to know about it?

Thanks!

**Comment by moeyayzatt** [comment]
why??
localtunnel error : no active client for ....
