### ISSUE TITLE
"Not connected to the internet" but other websites load

### ISSUE THREAD

**Issue by Parking-Master** [localtunnel/localtunnel#608]
Ok I'm just going to guess that the localtunnel servers are down?

Every other site on my device is loading except any localtunnel site.

It's weird because it doesn't respond with "The server is not responding" it responds with "Not connected to the internet"

I am away on a vacation currently so I could understand why something could go wrong, but then I remotely connected to my Raspberry Pi hosting it back home and it won't load on there either.

__Update__: When using "node server.js" I can see it never prints the URL or throws an error

**Comment by noah-haub** [comment]
I think localtunnel servers are down. My dev tunnels are not being created, and the website localtunnel.me can't be reached.

**Comment by Parking-Master** [comment]
@noah-haub I think so too. I think it stopped working around 2:30AM (est)

**Comment by locksiDesmond** [comment]
How long do we have to wait before its back up?

**Comment by acidclear** [comment]
halp halp

**Comment by TheBoroer** [comment]
Should be back up now!

**Comment by Parking-Master** [comment]
@TheBoroer thanks so much! It's working now.
