### ISSUE TITLE
Wordpress not working

### ISSUE THREAD

**Issue by minthemiddle** [localtunnel/localtunnel#61]
When I run Wordpress using Mamp on localhost, port 8888, custom URL `http://localhost:8888/wordpress` and I try to tunnel that using `$ lt --port 8888`, I will just see the tree at `http://localhost:8888` with a link to folder `wordpress`. When I click that however, loading will fail.

How can I forward my local Wordpress installation using localtunnel?

**Comment by palomnik** [comment]
I'm sure that there is a more elegant solution, but what I have had to do (assuming the site is on localhost) is:

1. Start localtunnel
2. You should still be able to access the site via localhost.
3. Add the plugin "better search and replace" - use it to replace all instances of localhost to the URL for localtunnel. It should now work.
4. Do the reverse switch with "better search and replace" from the localtunnel URL back to localhost.

If there is a better way to do this, I have not found it yet.
