### ISSUE TITLE
502 Bad Gateway on all tunnels

### ISSUE THREAD

**Issue by taylor-kang** [localtunnel/localtunnel#610]
same as title.

**Comment by biscuits4cheese** [comment]
I concur.

**Comment by markgarrigan** [comment]
Same here

**Comment by jBernavaPrah** [comment]
Same here.

**Comment by evoinea** [comment]
same

**Comment by Kissabi** [comment]
same :(

**Comment by jobinelenjical-cometchat** [comment]
Any update when it will be fixed. :(

**Comment by jordyfontoura** [comment]
same ç.ç

**Comment by Parking-Master** [comment]
Should be fixed soon everyone! I've had this problem before it should take 2 hours start to finish, the servers should just need a reset and it will be fixed.

**Comment by jobinelenjical-cometchat** [comment]
guys its working now :)

**Comment by Parking-Master** [comment]
@jobinelenjical-cometchat thanks!

**Comment by biscuits4cheese** [comment]
Belated thanks for fixing this issue.

**Comment by ThibaultJanBeyer** [comment]
it’s down again 😅

**Comment by Parking-Master** [comment]
@ThibaultJanBeyer yeah, I can confirm lol

**Comment by Parking-Master** [comment]
lol, ok, it just seems like it was a soft reset. It's been back up for hours now.

**Comment by aloker** [comment]
I'm getting 502s right now

**Comment by francovoisardshoelace** [comment]
Same here

**Comment by Parking-Master** [comment]
Yep, seems like a simple server restart is needed @TheBoroer

**Comment by TheBoroer** [comment]
Thanks for the ping @Parking-Master ! 

indeed restarting the docker containers fixed it 😂  not sure what happened though..

**Comment by Parking-Master** [comment]
@TheBoroer thanks!

**Comment by mrfijas** [comment]
I believe it's down again :cry:

**Comment by Parking-Master** [comment]
Appears to be slow, but back up!

**Comment by aldoportillo** [comment]
for me i just had to switch from `https` to `http`
