### ISSUE TITLE
504 Gateway Timeout Using Local Tunnel

### ISSUE THREAD

**Issue by jBernavaPrah** [localtunnel/localtunnel#616]
I'm trying to use `localtunnel` but starting this morning I get `504 Gateway Timeout`.

Is this happening to someone else?

**Comment by chrisk-7777** [comment]
I've noticed this on and off the last few weeks. It never lasts longer than 5mins, but it always comes back pretty quickly.

**Comment by Parking-Master** [comment]
@chrisk-7777 it's been doing it for hours today

**Comment by LindomarRodrigues** [comment]
@Parking-Master Any news?

**Comment by Parking-Master** [comment]
@LindomarRodrigues don't think so, the 504 error is gone but the website still takes forever to load

**Comment by Parking-Master** [comment]
Ok, it's back up! You can close this issue now. Thanks to everyone who helped fix the issue.

**Comment by ReEnMikki** [comment]
The error is still happening to me :|
And of course I double checked the port to make sure I wrote the right one

**Comment by Lamer217** [comment]
Still happens.
<img width="880" alt="image" src="https://github.com/localtunnel/localtunnel/assets/62716818/2e118c40-3f0f-4463-95ca-35a816440a86">

**Comment by Parking-Master** [comment]
@Lamer217 it's not happening to me, the website is working perfectly

**Comment by Parking-Master** [comment]
http://shiny-pianos-rule.loca.lt/

The website loads fine
