### ISSUE TITLE
Localtunnel Outage (Possibly)

### ISSUE THREAD

**Issue by biscuits4cheese** [localtunnel/localtunnel#617]
Hello,
As at 08/08/23 @ 09:00 GMT.

Can anyone please confirm to me that localtunnel is working properly please?

Thanks

**Comment by biscuits4cheese** [comment]
Hello,
Further to my original post, I can confirm that localtunnel is currently offline.

I can't provide any further information on the cause I'm afraid.

Thanks in advance.

**Comment by Parking-Master** [comment]
Yes, it's been offline as of yesterday morning (EST)

**Comment by biscuits4cheese** [comment]
Hello,
As at 08:38GMT on 08/08/23 the service is now working.

Initially the tunnels kept collapsing but this has now stabilised.

Thank you very much for fixing this issue.  Much appreciated.

**Comment by biscuits4cheese** [comment]
As previous comment.

**Comment by biscuits4cheese** [comment]
BTW thank you @Parking-Master for taking the time and trouble of confirming the status of the service yesterday.

**Comment by Parking-Master** [comment]
@biscuits4cheese you're welcome! Always here to help :D
