### ISSUE TITLE
 Localtunnel Not Functioning Properly as of 08/08/23

### ISSUE THREAD

**Issue by NaNshekhar04** [localtunnel/localtunnel#618]
I wanted to bring to your attention an issue I am facing with Localtunnel, a tool I've been using for some time now. As of 08/08/23 at 16:00 GMT, I have encountered a problem where Localtunnel is not functioning as expected.

**Description**:

Upon attempting to establish a tunnel using Localtunnel, I consistently encounter a stucked failure. The tunnel fails to be created, preventing me from accessing my local server remotely through the generated URL.

**Steps to Reproduce:**

1. Open a terminal.
2. Run the command localtunnel your-port-number.
3. It won't move further and will get stucked

_Expected Behavior:_
I expected the tunnel creation to be successful, resulting in the generation of a URL that I could use to access my local server remotely.

_Actual Behavior:_
Contrary to my expectations, the tunnel creation consistently fails. The command gets stucks after hitting enter.

**Environment**:
Operating System: Windows 10
Node.js Version: v18.16.0
Localtunnel Version: v2.0.2
Additional Information:

I have attached a screenshot that captures the behavior I receive for your reference. This should provide more context about the issue I'm facing.

Thank you : )
![Screenshot (9)](https://github.com/localtunnel/localtunnel/assets/110991877/f64152b2-1f15-4562-864b-69541ba0c96c)

**Comment by Parking-Master** [comment]
#617 loclatunnel has an outage possibly

**Comment by Parking-Master** [comment]
You'll have to wait until it comes back up

**Comment by ultan-kearns-revium** [comment]
I'm having a few issues myself, tunnel seems to be creating fine but having issues sending and receiving data.  Anyone else experiencing this?

**Comment by Parking-Master** [comment]
@ultan-kearns-revium yes

**Comment by narcis-fv** [comment]
Having issues as well.

**Comment by Ahmad-anility** [comment]
Same here

**Comment by willianqa** [comment]
👀

**Comment by TheBoroer** [comment]
Hey all, it should be up and working again. Can someone confirm and I'll close this ticket?

**Comment by Parking-Master** [comment]
@TheBoroer yep! It's been up for about a few days now. Feel free to close this issue
