### ISSUE TITLE
localtunnel: Possible outage?

### ISSUE THREAD

**Issue by biscuits4cheese** [localtunnel/localtunnel#620]
Hello,
As of 13/09/2023 @ 13:00 GMT I have discovered my tunnels no longer work.

As I'm using them through a third-party application, it's difficult to apportion responsibility to localtunnel or the third-party app.

Could someone please confirm if localtunnel is currently working?

Thanks.

**Comment by p-Jimenez** [comment]
#619 Looks like that might be the case, I'm too getting a 502 response

**Comment by biscuits4cheese** [comment]
Thanks for confirming p-Jimenez

As at 14/09 @08:20 GMT the issue seems to have been resolved.  Thanks to all involved.

**Comment by biscuits4cheese** [comment]
As at 14/09 https://github.com/08:20 GMT the issue seems to have been resolved. Thanks to all involved.

**Comment by biscuits4cheese** [comment]
As at 14/09 https://github.com/08:20 GMT the issue seems to have been resolved. Thanks to all involved.
