### ISSUE TITLE
Possible Outage

### ISSUE THREAD

**Issue by biscuits4cheese** [localtunnel/localtunnel#622]
Hi,
As on 28/09 @ 09:20GMT my tunnel no longer functions.

Can anyone please confirm if they concur (I can't as I'm using  a third party webhook).

Thanks in advance.

**Comment by f3bw** [comment]
Mine also does not work at the moment.

**Comment by biscuits4cheese** [comment]
Thanks for confirming @fabricewerger

**Comment by pauliclark** [comment]
Nor for me

**Comment by biscuits4cheese** [comment]
Thanks everyone

**Comment by kseniyaleutseyevasnmt** [comment]
I'm currently getting 502 error.

**Comment by martinGerez** [comment]
Same here

**Comment by biscuits4cheese** [comment]
Please note as of 28/09 @ 14:48GMT 'localtunnel' is working.  If necessary I will close this issue after a period of use.

Thanks to all concerned.

**Comment by biscuits4cheese** [comment]
Thanks for fixing this issue.

**Comment by corbt** [comment]
Localtunnel has been hanging when trying to establish a tunnel for the last few hours every time I try.
