### ISSUE TITLE
Website Unauthorized with Qbittorrent web UI

### ISSUE THREAD

**Issue by BGFAKE** [localtunnel/localtunnel#624]
![image](https://github.com/localtunnel/localtunnel/assets/146627971/3b621386-9bf1-4001-b0eb-3b3033602c6e)
It says Unauthorized but it works over local network!
![tempsnip](https://github.com/localtunnel/localtunnel/assets/146627971/5400c179-aa35-452b-913c-fe273dd9f9e7)

What is the problem, local tunnel doesn't allow qbittorrents website?

**Comment by TheBoroer** [comment]
It's not an issue with localtunnel. That "unauthorized" comes from your local server. It might have a setting Todo with host header validation. You should allow all or allow localhost and your localtunnel subdomain
