### ISSUE TITLE
Support Node 21

### ISSUE THREAD

**Issue by chenrui333** [localtunnel/localtunnel#629]
looks like localtunnel 2.0.2 does not work properly with node 21 (just hanging in the terminal while running `lt --port 8082` against node 21)

relates to https://github.com/Homebrew/homebrew-core/pull/151438

**Comment by k0d3r1s** [comment]
this is not related to node 21, it's related to #630. once that one is fixed, it should work on node 21 as well

**Comment by Parking-Master** [comment]
You can close this issue.

**Comment by chenrui333** [comment]
I see, closing now. Thanks for the pointer!

**Comment by chenrui333** [comment]
yeah, just tested out the formula, works fine for me now. Thanks @k0d3r1s @Parking-Master!

**Comment by Parking-Master** [comment]
@chenrui333 you're welcome. Glad it's working!
