### ISSUE TITLE
LocalTunnel is down for you too ?

### ISSUE THREAD

**Issue by Gabrixl-m** [localtunnel/localtunnel#630]
I'm trying to create a link with lt --port 8080 and the terminal is not responding to me, do you also have the same problem?

**Comment by lox0123** [comment]
Yes 😔 i found non solution for thé moment

**Comment by Gabrixl-m** [comment]
> Yes 😔 i found non solution for thé moment

I think it's because of an expired SSL certificate, we just have to wait, The website is also no longer available

**Comment by Kamal-Moha** [comment]
I'm having the same problem. Local tunnel not working

**Comment by williamisnotdefined** [comment]
Local tunnel is not working for me since last Friday afternoon.

**Comment by leogm360** [comment]
Yes. Seems like the SSL certs from the server `https://localtunnel.me/` expired at 10/20/23, all calls are reverse proxied from there (to my understanding). If you have your own reverse proxy server you can try the  `--host` option, it changes the default (localtunnel.me) host.

For the ones who doesn't have it, we will need to await someone to revalidate the certs. They could use the [certbot](https://certbot.eff.org/) from [Let's Encrypt](https://letsencrypt.org/). It enables a automatic renew of SSL certs.

**Comment by bmasias1** [comment]
Any alternative that can be recommended in the meantime?

**Comment by Parking-Master** [comment]
You can use _serveo_ for now.

```
ssh -R yoursubdomain.serveo.net:80:localhost:8080 serveo.net
```

Replace "yoursubdomain" and "8080" with your custom subdomain and port.

**Comment by kggayo** [comment]
here as well. Its been down since yesterday

**Comment by TheBoroer** [comment]
Hey all! I'm aware of the issue and will be fixing it tomorrow! I'm going to try to switch from nginx+certbot to traefik so that it can do the http and DNS challenges for SSL without it messing up every few months 😅

I'll post an update here once it's fixed!

**Comment by Parking-Master** [comment]
@TheBoroer thank you so much!

**Comment by greensplendid** [comment]
Still doesnt work
![111](https://github.com/localtunnel/localtunnel/assets/148444019/0956a7c3-598f-45d1-a773-e91bf562fb0d)

**Comment by oxyo** [comment]
I have found some alternatives here - https://github.com/anderspitman/awesome-tunneling

**Comment by brunos3d** [comment]
> Any alternative that can be recommended in the meantime?

My team decided to migrate to [Cloudflared](https://github.com/cloudflare/cloudflared), the implementation is quite simple and took just a few minutes.

**Comment by Parking-Master** [comment]
@TheBoroer it seems to be fixed, my tunnels are up and the main site is up, but it's really slow for some reason.

**Comment by TheBoroer** [comment]
> @TheBoroer it seems to be fixed, my tunnels are up and the main site is up, but it's really slow for some reason.

You're right! It's back up but tunnels might be slow. Traefik is great but it seems to constantly use 70% of the CPU (all cores) smh. I'm going to look into fixing that or going back to nginx and make certbot scripts that does http challenges for localtunnel.me and DNS challenges via cloudflare for loca.lt. 

If anyone has any tools or certbot forks that can be setup on docker and do it all in one container plz lmk! 🙏

**Comment by Parking-Master** [comment]
@TheBoroer ok thank you for the info! Actually it's back to normal now. I think it might even be faster than before 😂

**Comment by misilot** [comment]
> If anyone has any tools or certbot forks that can be setup on docker and do it all in one container plz lmk! 🙏



would [Caddy](https://caddyserver.com/) be a possibility?

**Comment by Gabrixl-m** [comment]
After generating my url and after entering my IP address it loads without displaying my home page, do you also have a problem or is it just me?

**Comment by oxyo** [comment]
works fine for me

**Comment by Gabrixl-m** [comment]
@TheBoroer You can help me, I have a big problem, After generating my url and after entering my IP address it loads without displaying my home page, I tried with ngrok and it works fine, I don't understand no why it doesn't load with localtunnel

**Comment by Gabrixl-m** [comment]
@TheBoroer it's after pressing the "click to submit" button that it loads without stopping, I use a Flask script so it's supposed to show me another page but there it loads without stopping

**Comment by williamisnotdefined** [comment]
it's working fine for me now, but a bit unstable going down after some minutes, I think it will be fine after a while.

**Comment by k0d3r1s** [comment]
for now it is like 2 out of 3 requests goes through. bit hard to work with but better than not working at all :)

**Comment by Parking-Master** [comment]
@TheBoroer my website keeps getting taken every few days now, by some malicious looking website in another language!! Why does this keep happening all the sudden?

**Comment by williamisnotdefined** [comment]
the tunnel was normal for me, but today it is getting down often.

**Comment by lox0123** [comment]
Yes,  was afraid it was just me ^^

**Comment by Gabrixl-m** [comment]
for me I've had the same problem from 1 week, it's after entering my IP address, it loads without displaying my "home page", for the moment I'm using ngrok, if you have a solution please tell me...

before he had SSL certificate problems, it worked well for me.

**Comment by Parking-Master** [comment]
Is everyone's problems solved? @TheBoroer I think you can close this issue now :)

**Comment by Gabrixl-m** [comment]
Yes for me everything came back normal, thank you all.
