### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by UtterDonkey** [localtunnel/localtunnel#635]
Is it possible to serve from a custom domain that I own by setting a CNAME record? If not, is it a possibility for a future feature?

**Comment by TheBoroer** [comment]
Hi,
If you self-host an instance of the localtunnel server, then i think cname should work.
If you mean you'd like to point cname to the public localtunnel.me server then no that will not work at the moment, and probably won't work unless localtunnel.me becomes freemium and offers that as a paid feature.
