### ISSUE TITLE
Huge latency when starting localtunnel ?

### ISSUE THREAD

**Issue by Aerowiel** [localtunnel/localtunnel#638]
Hello,

I'm experiencing huge latency lately with npx localtunnel, is it global ?

**Comment by bowenwr** [comment]
I'm also experiencing this. Tunnels fail to start, go down shortly after, or otherwise take a long time.

(I understand it's a free project and I'm very grateful) 🙏

Is there something we could do to help?

**Comment by TheBoroer** [comment]
Hey all! I saw the server experienced some internet issues yesterday and today but it seems to have gone away.
Lmk if you still see this and i'll investigate more

**Comment by bowenwr** [comment]
@TheBoroer Thanks for the response! I'm still currently seeing huge latency and non-delivery of webhooks. My URL was `neat-ghosts-press.loca.lt`. POST requests weren't coming through at all. GET requests would 404 (as expected) after about 30 seconds.

**Comment by TheBoroer** [comment]
hmm, strange... what country are you connecting from?

**Comment by bowenwr** [comment]
>hmm, strange... what country are you connecting from?

San Francisco, CA USA.

**Comment by bowenwr** [comment]
Now that I said something and regenerated a new URL it worked for me. 😅

Edit: I spoke too soon. First webhook worked and then it seems subsequent deliveries are 20-30 seconds+ with the same size webhooks

**Comment by TheBoroer** [comment]
thanks! ping from there looks fine to me (around 75ms) but i see the localtunnel server's cpu usage is kinda high most of the time.. 

Looks like traefik reverse proxy is eating up most of the CPU 😭
Let me try to tune it more and maybe bump up the cpu cores from 4 to 8 and see how it goes.

**Comment by bowenwr** [comment]
>Looks like traefik reverse proxy is eating up most of the CPU 😭

Thanks again and let me know if I can help!

**Comment by TheBoroer** [comment]
> Thanks again and let me know if I can help!
Thank you! 

I just bumped the cpu to 8 cores and doubled the ram so let's see if it makes it any better. 
I'll investigate this more a bit later today but please lmk how it's working for you now @bowenwr

**Comment by bowenwr** [comment]
Thanks! We're using it for a small workshop today so we'll definitely find out. 😅

I really appreciate the quick action and response.

**Comment by bowenwr** [comment]
It went great!

We had 26 workshop attendees use `localtunnel` successfully without incident to receive some local webhooks in an ad hoc developer workshop. Everything worked beautifully. Major kudos and what a boon that a freely provided open source project achieved this. 🤩

**Comment by TheBoroer** [comment]
> It went great!
> 
> We had 26 workshop attendees use `localtunnel` successfully without incident to receive some local webhooks in an ad hoc developer workshop. Everything worked beautifully. Major kudos and what a boon that a freely provided open source project achieved this. 🤩

Yay!! I'm very happy it worked great for you! 🤗 I'll keep everything running as is and see if the latency/slowness issue creeps back in (but i hope it doesnt haha)
