### ISSUE TITLE
Network authentication required error when using static local tunnel in google colab 

### ISSUE THREAD

**Issue by Tejnium** [localtunnel/localtunnel#640]
1. This is the code i am running in google colab to serve from static url 
```

# !npm install -g localtunnel
# !pip install flask
# !pip install flask-cors

from flask import Flask, request, jsonify
from flask_cors import CORS
import threading

app = Flask(__name__)
cors = CORS(app, resources={r"/": {"origins": "*"}})

@app.after_request
def after_request(response):
  # response.headers.add('Access-Control-Allow-Origin', '*')
  # response.headers.add('Access-Control-Allow-Headers', 'Content-Type')
  response.headers.add('Access-Control-Allow-Headers', '*')
  return response

# @app.route('/', methods=['POST','OPTIONS'])
# def home():
#     return "Hello, Flask on Google Colab!"

@app.route('/', methods=['POST'])
def add():
    data = request.get_json()
    print(data)
    print(data)
    x = data['x']
    y = data['y']
    result = x + y
    return jsonify({'result': result})



def run_flask_app():
    app.run(port=5005)

threading.Thread(target=run_flask_app).start()

!lt --port 5005 --subdomain olive12312-walls1-cough3-103-181-222-27

```

and this is the output for it 

```
* Serving Flask app '__main__'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5005/
INFO:werkzeug:Press CTRL+C to quit
your url is: https://olive12312-walls1-cough3-103-181-222-27.loca.lt/

```

after that i wrote an html code to serve the static url..

this is the html code 

```


<!DOCTYPE html>
<html>
<head>
    <title>Addition</title>
</head>
<body>
    <input id="x" type="number" placeholder="Enter first number">
    <input id="y" type="number" placeholder="Enter second number">
    <button onclick="addNumbers()">Add</button>
    <h1 id="output"></h1>
    <script>
        function addNumbers() {
            var x = document.getElementById('x').value;
            var y = document.getElementById('y').value;

            fetch('https://olive12312-walls1-cough3-103-181-222-27.loca.lt/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({x: parseInt(x), y: parseInt(y)}),
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('output').innerText = 'Result: ' + data.result;
            });
        }
    </script>
</body>
</html>

```

and this is what i see in the google colab 
`
INFO:werkzeug:127.0.0.1 - - [27/Jan/2024 03:26:45] "OPTIONS / HTTP/1.1" 200 -
`
and in the console i am getting this error 
```

staticserver.html:16
       POST https://olive12312-walls1-cough3-103-181-222-27.loca.lt/ 511 (Network Authentication Required)


```

what i am doing wrong ? 

My main goal is to serve the google colab through static url provided by localtunnel just like pythonanywhere.com or some other hosting platform. 
anyone can provided

**Comment by TheBoroer** [comment]
Hi,
This happens because your html/js runs in a regular browser. The 511 error is the tunnel reminder page being shown in the request.

The workaround is to just open your tunnel url in a new tab onetime first and enter your tunnel password (the google colab public ip), after that your html/js fetch() will work

**Comment by Tejnium** [comment]
hey I would love if you can have an authtoken just like ngrok or pyngrok have and limit the number of request per min so that people does not need to see the friendly reminder page also people who are working for development purpose can also avoid it completely and also stop spam by abusers as well.

**Comment by TheBoroer** [comment]
Auth token could be a good idea but I don't have npm push permissions so I can't push any updates to the client.

Actually, can you try adding the custom header to your fetch()? Take a look at the bottom of the tunnel reminder page details on how to bypass using custom headers

**Comment by Tejnium** [comment]
custom headers works well.  thanks.
