### ISSUE TITLE
State of the repo?

### ISSUE THREAD

**Issue by Marvin-Brouwer** [localtunnel/localtunnel#643]
Hi,

I'm pretty happy about not being stuck with ngrok, so I'm pretty happy with this npm package.
However, there seem to be quite some issues still open and even a rather large number of PRs.

I can see the last update was 2 years ago, what is the current plan with this repository?
I know I can just simply fork it and fix the issues I need, but, I kind of like the name of this npm package and I'd rather just contribute to this repo.

Is this project dead? And if not who owns it?

**Comment by priamjain** [comment]
Why are you not using ngrok? Being an enterprise company it is quicker in resolving issues.

**Comment by Marvin-Brouwer** [comment]
Well they changed something in the implementation of their warning page, breaking my dev setup.
So i started looking elsewhere.
Also, I like that I have the option here to apply for a subdomain without having to pay first.

Anyway, let's not start discussing whether I should use ngrok or Cloudflare tunnels. As that would distract from my question here.
I'm mostly just interested in the state of this repo, since they're obviously still hosting.

**Comment by TheBoroer** [comment]
Hey Marvin,

I currently maintain and host the public localtunnel.me server instance. I'm also the one that implemented the tunnel warning page. Could you explain your use-case and lmk what exactly broke your dev setup and I can see if I can tweak it without letting phishing portals slip through.


### RE: state of the project
I think it's kind of in coast mode when it comes to npm package updates. I have access to the localtunnel git repos and could make changes + merge in the PRs etc but I don't have permissions to push updates to the npm packages. 
The only person that has access to that is @defunctzombie. So he'd have to either push the new package releases to npm or give me access to the npm package too so I could push releases for us

An alternative is that I could publish a fork and pull PRs from here into that fork but I think there's several forks already floating around (not sure how actively maintained they are though)

**Comment by defunctzombie** [comment]
> give me access to the npm package too so I could push releases for us

Happy to give you access - what's your npm username?

**Comment by TheBoroer** [comment]
> > give me access to the npm package too so I could push releases for us
> 
> Happy to give you access - what's your npm username?

Oh that'd be amazing, thanks Roman!  My npm username is [theboroer](https://www.npmjs.com/~theboroer) 🙏

**Comment by Marvin-Brouwer** [comment]
> Hey Marvin,
> 
> I currently maintain and host the public localtunnel.me server instance. I'm also the one that implemented the tunnel warning page. Could you explain your use-case and lmk what exactly broke your dev setup and I can see if I can tweak it without letting phishing portals slip through.
> 
> ### RE: state of the project
> I think it's kind of in coast mode when it comes to npm package updates. I have access to the localtunnel git repos and could make changes + merge in the PRs etc but I don't have permissions to push updates to the npm packages. The only person that has access to that is @defunctzombie. So he'd have to either push the new package releases to npm or give me access to the npm package too so I could push releases for us
> 
> An alternative is that I could publish a fork and pull PRs from here into that fork but I think there's several forks already floating around (not sure how actively maintained they are though)

Hi @TheBoroer, 

Thanks for getting back to me.
For some clarity, it's ngrok that broke my setup, that's how I got here.
It appears that you need to click an approve button per device, as to where localtunnel only requires an approval per public IP, which helps me a lot. So no changes necessary there.

About the state of the repo:
I see, you have npm access now :pray: so that's good news.
I'm happy to help review some of the PR's.
I think #311 is a good addition for example.

I have to be honest, I'm having some issues I'm trying to fix with a server that may be unresponsive for short periods of time (vite/astro/rollup when building) so I forked the repo and started to rebuild for my needs. I'm happy to show you around once I figure out how I'd like to solve my issues if you're interested.

For now, thanks for sharing!

**Comment by TheBoroer** [comment]
I'd love to see what improvements you'll have in your fork, keep me posted @Marvin-Brouwer

I haven't been added to npm yet but can't wait! FYI @defunctzombie in case you missed it, my username is `theboroer` thank you!)

**Comment by defunctzombie** [comment]
@TheBoroer added

**Comment by Marvin-Brouwer** [comment]
@TheBoroer I told you I'd let you know more about my implementation.
I'm still not completely done but I have some cool improvements.

I basically started from scratch using typescript and vite, everything gets compiled and checked by a watcher now.
Also, I added a fallback page when there's no local connection available.
This helps when you start the tunnel before your local server.
It'll show this:
![image](https://github.com/localtunnel/localtunnel/assets/5499778/749230e2-7e45-472a-a9df-4293aa065914)
And try to connect local every 5 seconds, when it gets a connection it switches over and you now have a normal tunnel.

This however, is not my end goal. I would like this page to be shown on any local connection error.
Currently though, as soon as an `ECONNREFUSED` gets send to the server the connection gets dropped.
So, I'll need to figure out how to handle that.

I'm gonna be cleaning up todo's the couple of weekends, and, I'm planning to play around with automated deployments to npm using either `releaseme` or `semantic-release`.
But, if you like we can setup a discord call before that and I can show around my setup.

Let me know!

**Comment by babblebey** [comment]
> I'm gonna be cleaning up todo's the couple of weekends, and, I'm planning to play around with automated deployments to npm using either `releaseme` or `semantic-release`.

Do use @semantic-release 😉
