### ISSUE TITLE
IP password is not being accepted

### ISSUE THREAD

**Issue by KosmicDaKerbal** [localtunnel/localtunnel#648]
![image](https://github.com/localtunnel/localtunnel/assets/88624986/e19faed9-b5d2-40b2-81a8-e2ef2e03c6ce)
i go to `https://loca.lt/mytunnelpassword` and just copied and pasted the returning value, but it says its not correct.
how do i use the `bypass-tunnel-reminder` request? i really do not want this hassle to re-appear.

**Comment by TheBoroer** [comment]
Hey, You're inputting the wrong IP. The password for your tunnel atm should be `152.58.17.241` please check your internet/wifi/vpn setup to make sure you're visiting https://loca.lt/mytunnelpassword from the same public IP as where your localtunnel instance is running.

to use the header, you'll have to use a chrome extension to add it to all your browser requests OR just use it when doing a request via postman or something.
