### ISSUE TITLE
This is why?

### ISSUE THREAD

**Issue by 157476PayneGissing** [localtunnel/localtunnel#651]
![image](https://github.com/localtunnel/localtunnel/assets/162010509/52bdb964-a6a2-4afb-a33c-5e618e9f14bb)

![image](https://github.com/localtunnel/localtunnel/assets/162010509/8a6045d5-8211-4572-8c37-12e5600a2ba0)

**Comment by TheBoroer** [comment]
Your localtunnel client isn't connecting, it should show you the URL in the terminal if it's connected.

I don't think you can have underscores in a subdomain. Can you try your subdomain but with dashes instead?
