### ISSUE TITLE
How do I reset my password

### ISSUE THREAD

**Issue by AtGbemiga** [localtunnel/localtunnel#652]
Due to an error when inputting my password on the password prompt screen, I now get the response when I try to visit the URL.
Error: Cannot GET /api/v1/mypath/myotherpath
localtunnelURL: https://fav-work.loca.lt/ap1/v1/paystack/callbackurl

Steps I took to get the prompt screen again which don't work 
Uninstall & reinstall localtunnel so I can get the prompt screen again (npm install -g localtunnel)
Change my local app running port number
lt -n <port_number>
lt ./localtunnel -n <port_number>

Before inputting the wrong password, when I visit https://loca.lt/mytunnelpassword, I see no response but now I see the response of the wrong password which I need to change. How do I change my password?

**Comment by TheBoroer** [comment]
The tunnel password is based off of your public IP at the time you created the tunnel. If you've previously entered in the correct password (at the time you entered it), you won't see the prompt for 7 days unless you switch to a different Internet connection (e.g. hotspot or a different WiFi network).

Can you give more details on your "cannot GET" error? What's the http status code etc.

All that https://loca.lt/mytunnelpassword does is show you your public IP. If it's a new IP you've never seen before you'll have to restart the tunnel client to get it to set that up as the password.

**Comment by AtGbemiga** [comment]
The "cannot GET" error is unrelated to the tunnel. The issue is resolved for me.
