### ISSUE TITLE
Error: endpoint IP is not correct. Please try again or contact whoever gave you this link for the correct public IP.

### ISSUE THREAD

**Issue by itszavier** [localtunnel/localtunnel#659]
Hi, am using local tunnel to test a website on my local network, but getting this error when I use react client side with local tunnel, it works fine when used it with server side but not on the client side. 

I used `https://loca.lt/mytunnelpassword` to get my password but it's  not working.

```js
const startLocaltunnel = async () => {
      try {
        const tunnel = await localtunnel({
          port: 3000,
          subdomain: "narrate-frontend",
        }); // Change port to your frontend port
        console.log("Localtunnel URL:", tunnel.url);
      } catch (error) {
        console.error("Error starting Localtunnel:", error);
      }
    };
```

**Comment by itszavier** [comment]
it's working, localtunnel npm package 
is not supported on the client side that's why it wasn't working

**Comment by Lore228295** [comment]
just stop using localtunnel because you just givving away your ip adress to anyone

**Comment by TheBoroer** [comment]
> just stop using localtunnel because you just givving away your ip adress to anyone

I've replied in your GH issue #669. Every free tunnelling service exposes your IP (including ngrok) due to phishing and malware abuse. We want the bad guys to get busted. 

If you care about privacy then either host your own solution or pay for ngrok
