### ISSUE TITLE
Support of wildcard subdomains

### ISSUE THREAD

**Issue by jonatrey** [localtunnel/localtunnel#66]
Feature: wildcard subdomain
  Scenario: I want to catch everything in front of the subdomain
    Given as a developer of an application with multiple domains (www.mydev.me, console.mydev.me, ...)
    When I execute the command lt --port 80 --subdomain *
    Then localtunnel should create catch www.localtunnel.me, test.localtunnel.me and console.localtunnel.me

**Comment by JohnRoux** [comment]
This would be incredibly useful for testing multi-tenant type applications
