### ISSUE TITLE
local tunnel's service is down

### ISSUE THREAD

**Issue by yuki-2025** [localtunnel/localtunnel#662]
Currently, local tunnel's service is not available.
What's the problem?

**Comment by TheBoroer** [comment]
You'll need to be more specific that that. The site and server seem to be up. What exactly is your problem? Screenshots or error messages you're seeing would help

**Comment by yuki-2025** [comment]
> You'll need to be more specific that that. The site and server seem to be up. What exactly is your problem? Screenshots or error messages you're seeing would help

![image](https://github.com/localtunnel/localtunnel/assets/159591455/e6058683-7283-4331-ad63-9f7e09e30cef)

It was good just now, but it failed in both Colab and GCP now.

**Comment by fones** [comment]
@TheBoroer I am getting 503 and this is not my service ;)

![image](https://github.com/localtunnel/localtunnel/assets/2134294/6534c8bc-b7da-4502-a03f-53a066bace61)

**Comment by mcorcias** [comment]
It happens to me too, today.
Service Unavailable

**Comment by greatwolf** [comment]
Getting the same here too,

```
wget olive-pots-stay.loca.lt
--2024-07-04 03:40:42--  http://olive-pots-stay.loca.lt/
Resolving olive-pots-stay.loca.lt (olive-pots-stay.loca.lt)... 193.34.76.44
Connecting to olive-pots-stay.loca.lt (olive-pots-stay.loca.lt)|193.34.76.44|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2024-07-04 03:40:42 ERROR 503: Service Unavailable.
```

**Comment by fones** [comment]
@mcorcias @greatwolf  It's working now - slowly, but its working.

**Comment by ruscon** [comment]
Currently, local tunnel's service is not available again (fully).

```Error: read ECONNRESET```

**Comment by Vorelli** [comment]
Connection is pretty intermittent, unfortunately. Can't complain too much since it's free :shrug:

**Comment by TheBoroer** [comment]
Ah.. I _think_ we should be all fixed up again atm. 

Seems like the server was getting spammed and was causing traefik to max out all CPU cores :/ 
I switched to using a plain nginx reverse proxy so it should be speedier and work more reliably now (even though we're still getting spammed atm).

I'll close this for now but lmk if i missed anything🫡
