### ISSUE TITLE
LocalTunnel Down?

### ISSUE THREAD

**Issue by annuraggg** [localtunnel/localtunnel#666]
I am unable to access localtunnel for about an hour now

**Comment by azzamalzid** [comment]
until now, it's not responding,
I'm really need it, my graduation project based on it, please any help

**Comment by annuraggg** [comment]
Up Now, Thankyou

**Comment by TheBoroer** [comment]
You're welcome! Hopefully it stays up for good now. Im trying to hunt down what causes the CPU to be at 100% randomly.

It works now but I still see a 502 error randomly for a second then it works again 🤔
