### ISSUE TITLE
the new security is just dangerous

### ISSUE THREAD

**Issue by Lore228295** [localtunnel/localtunnel#669]
the "security" just need expose ur ip everywhere like why do you have to put password as your ip??? it does make any sense. can you guys remove security that just make it riskier.

**Comment by janaka** [comment]
>expose ur ip everywhere
where is everywhere?

**Comment by TheBoroer** [comment]
The IP-as-a-password was put into place to fight phishing portals (protect random visitors from seeing them). It was the quickest thing I could do to prevent a ton of phishing abuse notices flooding my way...

This service isn't meant to hide your IP or anonymize you in any way. It's meant to give you a quick, easy, free way of exposing your localhost site to the world for testing or development purposes. 

Other services like ngrok also expose your tunnel IP via http headers so I don't see the "security" issue here. 😂
