### ISSUE TITLE
LocalTunnel seems to be down

### ISSUE THREAD

**Issue by akmalmzamri** [localtunnel/localtunnel#670]
Hi. I believe localtunnel have been down for a few hours now

**Comment by Asi889** [comment]
you are right.
im not getting anything or any url .
its not logging the tunnel at all.
would love to hear for updates on this if there are.

**Comment by JasjitBansia** [comment]
Apart from creating local tunnels, localtunnel's websites themselves are not responding as well such as localtunnel.me or test.loca.lt. It has been unstable for a few days now

**Comment by kvnzrch** [comment]
did you find any alternative server?

**Comment by moetezch** [comment]
> did you find any alternative server?

you can use https://serveo.net/

**Comment by desatatufuria** [comment]
hi! 

Localtunnel is down!!...

**Comment by TheBoroer** [comment]
Hey all! Yup the datacenter's fiber connection where this is hosted in was cut last night and they're trying to fix it asap 😔 

All I can do is wait for them to fix it and look into ways to make the localtunnel server distributed in the future 😅

**Comment by lastlink** [comment]
https://localtunnel.me/ is down

https://theboroer.github.io/localtunnel-www/ works

**Comment by h-campos** [comment]
Hi guys, now works for me !

**Comment by akmalmzamri** [comment]
Looks like it's back online. Closing this issue
