### ISSUE TITLE
Local tunnel is down?

### ISSUE THREAD

**Issue by Vipul7513** [localtunnel/localtunnel#677]
Server is being run but unable to access web page

**Comment by burn-in-soul** [comment]
`localtunnel:client tunnel server offline: connect EHOSTUNREACH 193.34.76.44:443, retry 1s +0ms`

**Comment by ASproson** [comment]
I have the issue where the command just hangs in the terminal, too

**Comment by subhamb04** [comment]
The public url is not generated for me too.

**Comment by aelmancy** [comment]
me too, The public url is not generated

**Comment by SwapnilSoni1999** [comment]
The website is down since ages. 
I guess the project has been abandoned.. not sure though

**Comment by burn-in-soul** [comment]
> The website is down since ages. I guess the project has been abandoned.. not sure though

yesterday its was working

**Comment by TheBoroer** [comment]
Server or project isn't abandoned. Server is having issues at the moment. I'll check what's going on tomorrow morning 🫡

**Comment by myke11j** [comment]
Thanks a lot @TheBoroer

**Comment by NJHHBJSJKAsjdsasa** [comment]
....

**Comment by CJskii** [comment]
Same issue here, starting local tunnel from the terminal but it just hangs there

**Comment by katehuratakeshi220** [comment]
I have 2 production servers, and I am experiencing the same issue

**Comment by DevJoaoLucas** [comment]
Thx @TheBoroer

**Comment by NJHHBJSJKAsjdsasa** [comment]
When will it be resolved

**Comment by onurcagan** [comment]
Waiting for a fix, thanks for your contribution @TheBoroer.

**Comment by NJHHBJSJKAsjdsasa** [comment]
Perfect

**Comment by TheBoroer** [comment]
Should be back up! Some fiber optic lines apparently were cut and it took them 25hrs to fix it

**Comment by DevJoaoLucas** [comment]
It's running here! thx a lot @TheBoroer
