### ISSUE TITLE
Getting 502 Bad Gateway

### ISSUE THREAD

**Issue by suryarocks11** [localtunnel/localtunnel#684]
Hello ,
I am getting Getting 502 Bad Gateway.

**Comment by TheBoroer** [comment]
fixed!

**Comment by jake-wickstrom** [comment]
I am still seeing 502 Bad Gateway

**Comment by TheBoroer** [comment]
hey @jake-wickstrom can you try now? 

nginx needed a good ol' restart for some reason 😅
