### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mscarchilli** [localtunnel/localtunnel#86]
Do you have some more documentation on how to use all of the options? If not it would be super helpful if you put up some basic instructions.

One thing I'm trying to do (not sure localtunnel can) is to open a specific directory within xampp and to use that as the base of the url. I'm able to do this via editing my hosts, httpd.conf and httpd-vhosts.conf, but it would be great if localtunnel could do it easily via command line so no editing of those files would be necessary.

Thanks!

**Comment by defunctzombie** [comment]
The readme has the relevant documentation.
