### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by adrienrn** [localtunnel/localtunnel#88]
Hi,

A quick test seem to show that localtunnel.me does not provide SSL support but I may have missed something.

```
lt --port 443 --local-host something.dev --subdomain somethingdev
```

This gets me a 'Bad Request', as if localtunnel does not forward HTTPS.

```
Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
```

Thanks!

**Comment by defunctzombie** [comment]
It does not. PR would be welcome but in general this is not something I have found to be of much value since the localtunnel client connects to a local dev service and you don't need ssl for that. The goal of localtunnel is for simple public exposure during development so ssl on the dev machine has not been a focus.

**Comment by adrienrn** [comment]
Thanks for the clarification.
Let me just say that your work is brilliant, works like a charm!

Well, I might be a particular case but : 
- I'm integrating a payment API. So, my local site (even in sandbox) must be in https.
- Therefore the tunnel must be https for the webhooks (from that API).

**Comment by defunctzombie** [comment]
HTTPS is already available for each tunnel

**Comment by dseferlis** [comment]
I'm facing the problem described here. When the service on localhost runs on ssl is not accessible by localtunnel address.
Any progress on this?

**Comment by defunctzombie** [comment]
I do not understand the issue here. Localtunnel already provides https endpoints. I am closing this because in reading the original issue I don't see how it is correct. Localtunnel does provide ssl endpoints :)

**Comment by dseferlis** [comment]
I have Visual Studio running iisexpress using ssl on port 44300. So my address is https://localhost:44300/. Using "lt --port 44300 --subdomain demoapp" and visiting https://demoapp.localtunnel.me/ doesn't open my running site. If i disable ssl, so my address is http://localhost:44300/ then it works.

**Comment by defunctzombie** [comment]
Your localhost server does not (and cannot be serving requests over ssl). You should run the local server on a regular non-ssl port and then your demo will work. You don't need to run the local server with ssl because the localtunnel server (the one that handles the web request to demoapp.localtunnel.me will terminate the SSL for you.

**Comment by dseferlis** [comment]
Why can't? It's an app i m working like this for several months. What if i want to integrate oauth2, paypal and so many other services requiring ssl?

**Comment by adrienrn** [comment]
I actually need the local server to be https. :)

I'm working with a payment API that requires the SSL even for localhost / sandboxing. Therefore, I have created a self-signed certificate for my local server and reach my vhost with https.

Might be a special case though.

**Comment by defunctzombie** [comment]
> I'm working with a payment API that requires the SSL even for localhost / sandboxing

Is this API public? I can take a look. To me it seems that if the service requires the site to load over ssl, then loading the localtunnel subdomain (which is over ssl) would work. Your backend would not need to be ssl. I know for a fact that would be the case cause I have done similar :)

**Comment by defunctzombie** [comment]
If however you have resources loading on an https page trying to load over http or something else misconfigured when accessing via the localtunnel subdomain, then maybe you will have issues. But it does not have to do with requiring backend to be ssl since as far as any internet facing access is concerned your site IS ssl when access via localtunnel https.

**Comment by nickcolley** [comment]
I'm trying to test a http2 server vs a http1, be useful to be able to do this through localtunnel.. Do you know what main changes would be needed to support this usage?

**Comment by bugs181** [comment]
@defunctzombie You said "Localtunnel already provides https endpoints". Where in the code does it do this exactly?

Viewing `proxy.js` line `23` you use this code:
`self.server = net.createServer();`

Tracking down `/node_modules/http-proxy/lib/index.js` line `123`, function `ProxyServer.prototype.listen` is never called. 

Which does support SSL.
`  this._server  = this.options.ssl ?
    https.createServer(this.options.ssl, closure) :
    http.createServer(closure);`

For the life of me, I can't get SSL to be forwarded correctly. The web browser immediately closes any connection attempts, even after providing SSL certs in the `server.js` file.

**Comment by wisniewski94** [comment]
This feature would be great since http/2 based apps are getting more and more popular.

**Comment by markestocapio** [comment]
For our use case, we need HTTPS on our local server so that we are able to access the camera via the browser (Zxing QR code scanner plugin). Chrome doesn't allow non secured access unless you change chrome settings.

Local HTTPS support would be a great feature to have.

**Comment by 0nix** [comment]
++ am testing an http/2 server
