### ISSUE TITLE
Subdomain gets stuck on restarts.

### ISSUE THREAD

**Issue by Pradeek** [localtunnel/localtunnel#90]
I use this with a fixed subdomain with a local Django server. By default, it prevents the Django server from auto-reloading on changes, and so I end up stopping localtunnel and starting it back up again. After a couple of times of restarting, the subdomain ends up not getting updated and constantly times out despite my tunnel being stopped. After a certain period of time, it becomes available again.

**Comment by mradzinski** [comment]
+1

**Comment by pori** [comment]
+1

**Comment by imjared** [comment]
> a certain period of time

any idea how long this usually is? running into this error and wondering if i should wait a few minutes, hours, or try again tomorrow

**Comment by henriquesobral** [comment]
+1

**Comment by evserykh** [comment]
the same issue. anyone was able to fix it?
