### ISSUE TITLE
discussion: allow client to receive arbitrary data

### ISSUE THREAD

**Issue by morganrallen** [localtunnel/localtunnel#95]
In developing a custom server I'm finding the need to send more data to the client than just the url, id, etc.

From this chunk of code it's clear the data is strictly controlled to 5 keys.
https://github.com/localtunnel/localtunnel/blob/master/lib/Tunnel.js#L62

Is there a specific reason the client would want to prohibit extra data that 99.9999% of the time wouldn't exist? Possible security implications is the best guess I can provide, but cannot actually think of a specific issue. If that's the case possibly hide it behind an option so only module authors consuming localtunnel can enable it.

Happy to make a PR or two demoing different approaches if this is even reasonable.

**Comment by defunctzombie** [comment]
Nope, there is no reason other than there was no extra data since the client implementation evolved with the server. If you have a specific use case or need for more data I would be interested to hear it.

**Comment by morganrallen** [comment]
So it turns out this didn't actually suit my needs as I want data to be returned after the tunnel is opened, but I'll share the use case for reference.

The project I'm working on doesn't require a public facing tunnel but rather exposes the tunnel to an internal testing services. The tunnel server and testing services reside on the network, after the tunnel is established the server dispatches the test server to test on the generated domain.

The desire was to send the results back over that original HTTP request, but as the server doesn't establish the tunnel until after the request ends I ended up just using a second request to fetch the results.
