### ISSUE TITLE
connection issues

### ISSUE THREAD

**Issue by JamesKyburz** [localtunnel/localtunnel#97]
Having alot of connection timeouts when running with zuul together with saucelabs since yesterday.

The error I'm getting is
```
Error: connection refused: localtunnel.me:35448 (check your firewall settings)
```

Do you have any tips or is there currently an issue?

**Comment by Acconut** [comment]
Me too. None of my tests have passed in the last days because of this behaviour. I would be very pleased about more information on this issue. :)

**Comment by JamesKyburz** [comment]
Closing that as is a duplicate of https://github.com/localtunnel/localtunnel/issues/81
