### ISSUE TITLE
localtunnel.me 504 Time-Out

### ISSUE THREAD

**Issue by n3ssi3** [localtunnel/localtunnel#98]
I love tocaltunnel for the functionality : lt --port 8000 --subdomain mydomain --local-host mydomain.localhost

Today I wanted to use the functionality again, but I get an 504 Gateway Time-out (nginx/1.7.8).
I can not tell exactly when I was using it last, maybe a month ago, and there it worked perfectly fine.

I recently updated to OSX 10.11 I am not sure if that does make any difference, but I don't think so.
I also don't get an error in my terminal, so I think it is an error on you side.

Cheers

**Comment by jimmyn** [comment]
+1

**Comment by defunctzombie** [comment]
If the website goes down or some other thing breaks users might see this for a few moments until things are back up. If things are offline for a while the best approach is to ping me on twitter @defunctzombie
