### ISSUE TITLE
it does not support live changes for Meteor Framework

### ISSUE THREAD

**Issue by shaunstanislaus** [localtunnel/localtunnel#99]
i was wondering if you would fix it to work for framework such as Meteor Framework?

**Comment by defunctzombie** [comment]
This is not a framework specific tool and I have no idea what it would mean to "fix" it to work with meteor.

**Comment by shaunstanislaus** [comment]
@defunctzombie 
i know its not a framework specific tool, its a dns wrapper that helps in NAT a local ip address to face to the public to be accessible.

in case you do not know, MeteorJS by itself when its run. whatever changes i made to the file, it will automatically refresh the server with the new update, and when i mask over with your `local tunnel` by doing `lt --port 3000` for example , yes it does work but it doesn't refresh automatically.
